import type { Authored } from "../curriculum.ts";

/** Candlestick patterns, at Foundations level. Placed after Market Structure so context comes
 *  before pattern, which is the course's own rule. Every named shape is taught with what it
 *  records and what it cannot record — and the module ends by arguing you can drop the names. */
export const candlesContent: Record<string, Authored> = {
  "FND-CANDLE-001": {
    plain: "A candlestick pattern is a name given to one candle, or a few in a row, that share a recognisable shape.",
    detail: "The shape is a shorthand for what happened: where price opened and closed, and how far it travelled beyond that. Naming shapes is useful because it lets you compare situations quickly — and the name adds nothing that the four prices did not already contain.",
    example: "A candle with a small body at the top and a long line below it gets called a hammer. The name is a label for 'fell hard, closed back near the high'.",
    interaction: "candle_pattern",
    flow: "define",
    question: "What does giving a candle shape a name add?",
    choices: ["New information about the market", "A quicker way to describe what the four prices already showed", "A prediction of the next candle", "Confirmation from other traders"],
    correct: 1,
    correctFeedback: "Correct. The name is compression, not evidence. Everything it refers to was already in the open, high, low and close.",
    incorrectFeedback: "A pattern name summarises the four prices. It cannot contain more than they do.",
    takeaway: "A candlestick pattern is a name for a shape. The shape holds the information; the name just speeds up describing it.",
  },
  "FND-CANDLE-002": {
    plain: "A doji is a candle that opened and closed at almost the same price after travelling in both directions.",
    detail: "The body is tiny and the wicks are long, so the period covered ground and gave it all back. It is usually described as indecision, which is accurate: neither side kept what it took.",
    example: "Open 100.40, high 103.20, low 97.60, close 100.50. Nearly six points of travel and five paise of net change.",
    interaction: "candle_pattern",
    flow: "define",
    question: "What makes a candle a doji?",
    choices: ["Long wicks", "The open and close being almost identical", "A red colour", "Low volume"],
    correct: 1,
    correctFeedback: "Correct. A tiny body is the definition. Long wicks usually come with it but are not what names it.",
    incorrectFeedback: "The defining feature is that the period finished where it started — the body, not the wicks or the colour.",
    takeaway: "Doji = open and close almost equal. It records a period that went nowhere, however far it travelled.",
  },
  "FND-CANDLE-003": {
    plain: "A hammer is a candle with a long lower wick and a small body near the top, appearing after a fall.",
    detail: "It records price dropping well below where it finished — sellers reached a level and could not hold it. The 'after a fall' half is not optional: the same shape means something different in a rising market.",
    example: "Two down candles, then one that opens at 100.60, trades as low as 95.40, and closes at 100.90. Five points of decline inside the period, all recovered.",
    interaction: "candle_pattern",
    flow: "classify",
    question: "A hammer forms after a two-week decline. What has it recorded?",
    choices: ["That the decline has ended", "That price fell inside the period and closed back near its high", "That buyers are stronger than sellers", "That the next candle will be green"],
    correct: 1,
    correctFeedback: "Correct. It records one period being rejected at its lows. What happens next is a separate question.",
    incorrectFeedback: "A hammer describes what one period did. It cannot say whether the decline is over.",
    takeaway: "Hammer = long lower wick, small body near the top, after a fall. A rejected low, and nothing more.",
  },
  "FND-CANDLE-004": {
    plain: "A shooting star is a candle with a long upper wick and a small body near the bottom, appearing after a rise.",
    detail: "It is the hammer's mirror. Price pushed well above where it finished, so the high was reached and given back. In a strong advance this happens repeatedly without the advance ending.",
    example: "Open 99.80, high 105.20, low 99.40, close 100.10. More than five points above the close, none of it held.",
    interaction: "candle_pattern",
    flow: "classify",
    question: "A shooting star forms during a strong three-month advance. What does it establish?",
    choices: ["The advance is over", "One period reached higher and did not hold it", "Sellers have taken control", "A reversal is likely tomorrow"],
    correct: 1,
    correctFeedback: "Correct. Advances make and reject highs on the way up. One rejection is one observation.",
    incorrectFeedback: "A rejected high is a single period's record. Sustained advances produce them regularly.",
    takeaway: "Shooting star = long upper wick, small body near the bottom, after a rise. A rejected high, once.",
  },
  "FND-CANDLE-005": {
    plain: "A bullish engulfing is an up candle whose body completely covers the down candle before it.",
    detail: "The second period opens below where the first closed and finishes above where the first opened, so a full period of decline is undone in one. The comparison is between the bodies — the wicks are not part of the definition.",
    example: "First candle: 101.40 down to 99.20. Second: opens 98.80, closes 102.90. The second body starts below and ends above the first.",
    interaction: "candle_pattern",
    flow: "define",
    question: "Which two prices decide whether a candle is engulfing?",
    choices: ["The high and the low", "The open and close of each candle — the bodies", "The volume of each candle", "The close and the previous high"],
    correct: 1,
    correctFeedback: "Correct. Bodies engulf bodies. A candle with a longer wick but a smaller body is not engulfing.",
    incorrectFeedback: "Engulfing compares bodies: this candle's open and close against the previous candle's open and close.",
    takeaway: "Bullish engulfing = an up body that spans the previous down body. Bodies, not wicks.",
  },
  "FND-CANDLE-006": {
    plain: "A bearish engulfing is a down candle whose body completely covers the up candle before it.",
    detail: "The mirror image: the period opens above the previous close and finishes below the previous open, erasing a full period of gain. Like its opposite, it describes what one period did rather than who is left to do it again.",
    example: "First candle: 98.80 up to 101.20. Second: opens 101.80, closes 98.20. The gain of the first is entirely gone.",
    interaction: "candle_pattern",
    flow: "compare",
    sides: {
      left: "Bullish engulfing",
      right: "Bearish engulfing",
      rows: [
        ["Follows a down candle", "Follows an up candle"],
        ["Opens below its close, ends above its open", "Opens above its close, ends below its open"],
        ["A period of decline undone", "A period of gain undone"],
      ],
    },
    question: "What do the two engulfing patterns have in common?",
    choices: ["Both predict reversals", "Both record one period completely undoing the previous one", "Both require high volume", "Both appear only on daily charts"],
    correct: 1,
    correctFeedback: "Correct. They are the same observation pointing in opposite directions.",
    incorrectFeedback: "Neither predicts anything. Both record a period whose body covers the previous body.",
    takeaway: "Engulfing, either direction, records one period undoing the last. Direction is the only difference.",
  },
  "FND-CANDLE-007": {
    plain: "A harami is a small candle whose body sits entirely inside the body of the much larger candle before it.",
    detail: "It is the opposite arrangement to engulfing: instead of one period covering the last, this period is contained by it. What it records is a move that stopped extending — which is a smaller claim than a move that reversed.",
    example: "A large down candle from 105.20 to 99.80, then a small candle trading only between 100.60 and 102.60 — well inside the previous body.",
    interaction: "candle_pattern",
    flow: "compare",
    sides: {
      left: "Engulfing",
      right: "Harami",
      rows: [
        ["The new body covers the old one", "The new body sits inside the old one"],
        ["A period undone", "A period paused"],
        ["Movement", "Contraction"],
      ],
    },
    question: "What does a harami record that an engulfing does not?",
    choices: ["A stronger reversal", "A pause — the move stopped extending rather than reversed", "Higher volume", "A gap"],
    correct: 1,
    correctFeedback: "Correct. Contraction after a large move is a modest claim, and treating it as a reversal signal overstates it.",
    incorrectFeedback: "A harami is contained by the previous candle. That describes a pause, not a reversal.",
    takeaway: "Harami = a small body inside the previous large one. It records a pause, which is a small claim.",
  },
  "FND-CANDLE-008": {
    plain: "A morning star is three candles: a large fall, a small indecisive period, then a strong recovery.",
    detail: "The three periods tell a small story — decline, hesitation, reversal — and the useful requirement is that the third candle closes back inside the first candle's body. Without that, the recovery has not undone enough to be worth the name.",
    example: "A candle from 105 down to 100.80, then a small one between 98.90 and 100.90, then one closing at 104 — back inside the first body.",
    interaction: "candle_pattern",
    flow: "sequence",
    steps: [
      "A large down candle — the decline in progress.",
      "A small-bodied candle, often gapped lower — the decline stops extending.",
      "A strong up candle that closes back inside the first candle's body.",
      "Without that third close, the shape is a pause rather than a morning star.",
    ],
    question: "What is the requirement most often left out when naming a morning star?",
    choices: ["The gap between the first two candles", "The third candle closing back inside the first candle's body", "High volume on the third candle", "A doji in the middle"],
    correct: 1,
    correctFeedback: "Correct. Without that close, the recovery has not undone enough of the decline to mean much.",
    incorrectFeedback: "The gap and the volume are common but optional. The third candle reaching back into the first body is the substance.",
    takeaway: "Morning star = fall, pause, recovery closing back inside the first body. That third close is the pattern.",
  },
  "FND-CANDLE-009": {
    plain: "An evening star is the same three-candle shape upside down: a strong rise, a stall, then a decisive fall.",
    detail: "Its fragile part is the middle candle. A small body says the advance stalled; a slightly larger one means it simply continued and paused, which is a different and much more common thing.",
    example: "A candle up to 103.20, then a small one between 103.40 and 104.80, then one closing at 99.60 — back inside the first body.",
    interaction: "candle_pattern",
    flow: "classify",
    question: "The middle candle of a would-be evening star has a fairly large body. What do you have?",
    choices: ["A stronger evening star", "Not an evening star — a stall is what the small body was recording", "A doji", "A bearish engulfing"],
    correct: 1,
    correctFeedback: "Correct. The small middle body is the observation. Enlarge it and the shape no longer records a stall.",
    incorrectFeedback: "A large middle body means the advance kept going. The pattern depends on that period being indecisive.",
    takeaway: "Evening star = rise, stall, decisive fall. The stall is the small middle body, and it is not optional.",
  },
  "FND-CANDLE-010": {
    plain: "A hammer and a hanging man are exactly the same shape — only what came before them differs.",
    detail: "Long lower wick, small body near the top. After a decline it is called a hammer and read as buyers defending; after an advance it is called a hanging man and read as selling appearing. Identical candle, opposite readings, decided entirely by context.",
    example: "The same candle — open 100.60, low 95.40, close 100.90 — has two different names depending only on whether the previous fortnight rose or fell.",
    interaction: "candle_pattern",
    flow: "compare",
    sides: {
      left: "Hammer",
      right: "Hanging man",
      rows: [
        ["Identical shape", "Identical shape"],
        ["Appears after a decline", "Appears after an advance"],
        ["Read as a low being rejected", "Read as selling appearing mid-period"],
      ],
    },
    question: "Two charts show the identical candle shape but carry different names. What decides which name applies?",
    choices: ["The volume", "The move that came before it", "The size of the body", "The colour of the candle"],
    correct: 1,
    correctFeedback: "Correct. This is the clearest proof in the course that a candle shape has no meaning of its own.",
    incorrectFeedback: "The shapes are identical by definition. Only the preceding move separates the two names.",
    takeaway: "The same shape has two names and two readings. Context, not shape, supplies the meaning.",
  },
  "FND-CANDLE-011": {
    plain: "In every one of these patterns, the close matters more than any other price.",
    detail: "The high and low record where price visited; the close records where it was left when the period ended. That is why every definition here is about bodies — engulfing, harami, the morning star's third candle. Where price finished is the part that stuck.",
    example: "A candle reaching 105.20 and closing at 100.10 tells you 105.20 was visited and not held. Had it closed at 104.90, the same high would mean something quite different.",
    interaction: "candle_pattern",
    flow: "cause",
    question: "Why do candlestick definitions keep referring to bodies rather than wicks?",
    choices: ["Bodies are easier to see", "The body is bounded by the close, which is where price was left at the end of the period", "Wicks are often inaccurate", "Bodies have more volume"],
    correct: 1,
    correctFeedback: "Correct. Visiting a price and finishing at it are different, and the body is what records the second one.",
    incorrectFeedback: "The body spans open to close, and the close is where the period actually ended. That is what makes it the load-bearing price.",
    takeaway: "The close is the price that stuck. That is why patterns are defined on bodies.",
  },
  "FND-CANDLE-012": {
    plain: "A confirmation candle is the next period, used to check whether the pattern led anywhere.",
    detail: "Waiting for it costs you a worse price and buys you evidence that the shape was followed by something. It does not make the pattern reliable — it converts a one-period observation into a two-period one, which is a modest improvement honestly described.",
    example: "A hammer forms at 100.90. Acting on it means buying near 101. Waiting for a close above the hammer's high means buying near 101.30 with one more period of evidence.",
    interaction: "candle_pattern",
    flow: "cause",
    question: "What does waiting for a confirmation candle actually buy?",
    choices: ["A reliable signal", "One more period of evidence, in exchange for a worse price", "A tighter stop", "A higher win rate guaranteed"],
    correct: 1,
    correctFeedback: "Correct. Two periods of evidence instead of one, paid for in entry price. That is the whole trade.",
    incorrectFeedback: "Confirmation adds one period of evidence and costs you price. It does not make a pattern reliable.",
    takeaway: "Confirmation trades a better price for one more period of evidence. Describe it that modestly.",
  },
  "FND-CANDLE-013": {
    plain: "Candlestick patterns are common, and most of them are followed by nothing in particular.",
    detail: "Engulfing candles and doji appear constantly on any chart you look at. If a shape appears several times a month in a single stock, it cannot by itself be a rare and valuable signal — which is why these patterns are used to refine timing inside a plan, not to generate trades.",
    example: "Scanning a year of daily candles for one stock turns up dozens of engulfing candles. A handful preceded a real move; most preceded ordinary trading.",
    interaction: "candle_pattern",
    flow: "cause",
    question: "A pattern appears dozens of times a year in one stock. What follows from its frequency?",
    choices: ["It is a reliable signal because it recurs", "It is too common to be a rare edge on its own", "It only works on longer timeframes", "It should be traded every time"],
    correct: 1,
    correctFeedback: "Correct. Something that happens constantly and precedes a big move occasionally is describing normal trading.",
    incorrectFeedback: "Frequency works against significance here. A common shape cannot carry a rare edge by itself.",
    takeaway: "These shapes are common. Use them to refine timing within a plan, not to find trades.",
  },
  "FND-CANDLE-014": {
    plain: "Everything these names describe can be read straight off the candle without naming it at all.",
    detail: "'Bullish engulfing' means today undid yesterday. 'Hammer' means it fell and closed back up. Reading the description rather than reciting the label keeps you attentive to degree — how far, how much was recovered, how it compares with recent candles — all of which the name throws away.",
    example: "Instead of 'that is a hammer', say 'it fell five points inside the period and closed back near the high, which is twice the recovery of the last three candles'.",
    interaction: "candle_pattern",
    flow: "define",
    question: "What does describing a candle rather than naming it preserve?",
    choices: ["Speed", "Degree — how far, how much was recovered, and how it compares with recent candles", "Accuracy of the high and low", "Volume information"],
    correct: 1,
    correctFeedback: "Correct. Names are categories, and categories discard magnitude. The magnitude is usually the interesting part.",
    incorrectFeedback: "Naming is faster; describing keeps the degree. A small hammer and a huge one share a name and not much else.",
    takeaway: "Read what the candle did rather than what it is called. The name discards the degree.",
  },
};
