import type { Authored } from "../curriculum.ts";

/** Foundations additions: trading horizons, and the first idea of narrowing a market down
 *  to a handful of names. Same house rules as the rest of Level 1 — plain first sentence,
 *  no index vocabulary, and nobody is asked to predict anything. */
export const horizonsContent: Record<string, Authored> = {
  // ── Trading Horizons ────────────────────────────────────────────────────────
  "FND-HZN-001": {
    plain: "Your trading horizon is simply how long you intend to hold before selling.",
    detail: "It is a decision you make before entering, not something you discover afterwards. Almost everything else — which chart you read, how far away the stop goes, how many shares you buy, how much the costs matter — follows from this one choice.",
    example: "Two people buy the same share at ₹640. One plans to sell by 3 p.m. today; the other plans to hold until March. They are running two completely different trades.",
    interaction: "horizon",
    flow: "define",
    question: "Two traders buy the same stock at the same price with different holding periods. What is true?",
    choices: ["They are making the same trade", "They are running different trades, with different charts, stops and sizes", "The shorter horizon is safer", "The longer horizon is safer"],
    correct: 1,
    correctFeedback: "Correct. The entry price is the only thing they share. Everything that manages the trade differs.",
    incorrectFeedback: "Same price, different trade. Horizon decides the chart, the stop, the size and how much costs matter.",
    takeaway: "Horizon is chosen before entry, and everything else in the trade follows from it.",
  },
  "FND-HZN-002": {
    plain: "Intraday means you open and close the position on the same day, holding for minutes to hours.",
    detail: "Nothing is carried overnight, so news that breaks after the close cannot touch you. In exchange you get a hard deadline: the position must be closed whether or not your idea has had time to work.",
    example: "Buy at 10:20 a.m. at ₹646, sell at 1:40 p.m. at ₹658. The position never existed outside that one session.",
    interaction: "horizon",
    flow: "define",
    question: "What does an intraday trader give up in return for having no overnight risk?",
    choices: ["Access to liquid stocks", "Time — the idea must work before the session ends", "The ability to use a stop", "Lower brokerage"],
    correct: 1,
    correctFeedback: "Correct. The deadline is the price of avoiding overnight exposure.",
    incorrectFeedback: "Overnight safety is bought with time. The trade must resolve inside one session or be closed anyway.",
    takeaway: "Intraday removes overnight risk and adds a deadline. Both are consequences of the same rule.",
  },
  "FND-HZN-003": {
    plain: "Swing trading means holding for a few days to a few weeks.",
    detail: "You are trying to capture one move rather than one session, so you read daily charts and accept that the position sits through nights and weekends. That means gaps: price can reopen well away from where it closed, past your stop.",
    example: "Buy on Tuesday at ₹1,595, hold through nine sessions, sell at ₹1,720. The chart you watch is daily, and you check it once a day rather than continuously.",
    interaction: "horizon",
    flow: "define",
    question: "What risk does a swing trader accept that an intraday trader does not?",
    choices: ["Slippage", "Overnight gaps that can open past the stop", "Brokerage", "Illiquidity"],
    correct: 1,
    correctFeedback: "Correct. A stop protects you while the market is open. A gap happens while it is shut.",
    incorrectFeedback: "Both face costs and slippage. Only the swing trader is exposed while the market is closed.",
    takeaway: "Swing trading holds for days to weeks and accepts gap risk in return for not needing to watch every tick.",
  },
  "FND-HZN-004": {
    plain: "Positional trading means holding for several weeks to several months.",
    detail: "At this length the individual day barely matters. What matters is whether the broader move is still intact, which is why positional traders use wider stops, smaller positions for the same rupee risk, and pay attention to results announcements that a day trader can simply avoid.",
    example: "Buy in August, hold through three sets of quarterly results, sell in December. Roughly sixty daily candles pass, most of which you ignore.",
    interaction: "horizon",
    flow: "define",
    question: "Why does a positional trader use a wider stop than a swing trader?",
    choices: ["Because longer trades are riskier", "Because the position must survive ordinary movement across weeks, not days", "Because brokers require it", "Because wider stops are more accurate"],
    correct: 1,
    correctFeedback: "Correct — and a wider stop means fewer shares, so the rupee risk stays the same.",
    incorrectFeedback: "The stop must sit outside the noise of the holding period. Weeks of noise is wider than days of noise.",
    takeaway: "Positional holds run weeks to months, which means wider stops and correspondingly smaller positions.",
  },
  "FND-HZN-005": {
    plain: "Investing means holding for months to years, betting on the business rather than the price move.",
    detail: "The chart stops being the main input. You are relying on the company earning more over time, which means the questions change: what it sells, whether that is growing, what it owes. Price movement that would stop out a trader is simply ignored.",
    example: "Buy in 2024 and still hold in 2028. A 20% fall during that period is uncomfortable, but it does not by itself end the position.",
    interaction: "horizon",
    flow: "compare",
    sides: {
      left: "Trading",
      right: "Investing",
      rows: [
        ["Betting on a price move", "Betting on the business earning more"],
        ["A stop ends the position", "A change in the business ends the position"],
        ["Read the chart", "Read the company"],
      ],
    },
    question: "What ends an investing position, if not a stop-loss?",
    choices: ["A fall of more than 20%", "Evidence that the business itself has changed", "The end of the financial year", "A moving-average crossover"],
    correct: 1,
    correctFeedback: "Correct. If the bet is the business, the exit signal has to come from the business.",
    incorrectFeedback: "Price levels do not end an investing thesis, because price movement was never the bet.",
    takeaway: "Investing bets on the business over years. The exit signal comes from the company, not the chart.",
  },
  "FND-HZN-006": {
    plain: "The chart you read should match how long you plan to hold.",
    detail: "An intraday trader lives on 1- and 5-minute candles; a swing trader on daily; a positional trader on daily and weekly. Reading a chart much finer than your holding period fills the screen with movements too small to affect your decision — and each one invites you to act.",
    example: "A two-week trade watched on a 1-minute chart shows roughly 5,000 candles. About four of them matter.",
    interaction: "horizon",
    flow: "compare",
    sides: {
      left: "Chart too fine for the horizon",
      right: "Chart matched to the horizon",
      rows: [
        ["Thousands of irrelevant movements", "Only moves large enough to matter"],
        ["Constant temptation to act", "A decision every day or two"],
        ["Noise looks like information", "Structure is visible"],
      ],
    },
    question: "You plan to hold for three weeks. Which chart should be your main one?",
    choices: ["1-minute", "5-minute", "Daily", "It does not matter"],
    correct: 2,
    correctFeedback: "Correct. Daily bars are roughly the size of the decisions a three-week trade actually makes.",
    incorrectFeedback: "Match the bar size to the decision size. For a multi-week hold, that is the daily chart.",
    takeaway: "Match the chart to the horizon. Detail finer than your decisions is temptation, not information.",
  },
  "FND-HZN-007": {
    plain: "The longer you hold, the further away your stop has to be — and the fewer shares you can buy.",
    detail: "A stop must sit outside the ordinary movement of your holding period. Days of ordinary movement is a small distance; months of it is a large one. Since the rupee you risk stays fixed, a wider stop simply means a smaller position.",
    example: "₹2,000 of risk. An intraday stop ₹4 away allows 500 shares. A positional stop ₹40 away allows 50 shares. Same risk, same idea, one-tenth the position.",
    interaction: "horizon",
    flow: "calculate",
    question: "Risk budget ₹2,000. Your stop widens from ₹5 to ₹25 because you extended the horizon. What happens to the position?",
    choices: ["It stays at 400 shares", "It falls from 400 shares to 80", "It rises to 2,000 shares", "The risk budget must rise"],
    correct: 1,
    correctFeedback: "Correct: ₹2,000 ÷ ₹5 = 400, and ₹2,000 ÷ ₹25 = 80. The rupee risk never changed.",
    incorrectFeedback: "Divide the budget by the risk per share each time: 2,000 ÷ 5, then 2,000 ÷ 25.",
    takeaway: "A longer horizon needs a wider stop, and a wider stop means a smaller position for the same rupee risk.",
  },
  "FND-HZN-008": {
    plain: "Short horizons pay more in costs; long horizons carry more exposure to events.",
    detail: "Every round trip costs the same whether you held for an hour or a year, so trading often multiplies a fixed cost against smaller moves. Holding longer avoids that, and instead exposes you to results announcements, policy decisions and overnight news you cannot trade around.",
    example: "Twenty intraday trades a month at ₹85 each is ₹1,700 of cost. One positional trade held three months costs ₹85 — and sits through two sets of quarterly results.",
    interaction: "horizon",
    flow: "compare",
    sides: {
      left: "Short horizon",
      right: "Long horizon",
      rows: [
        ["Costs paid many times over", "Costs paid once"],
        ["Small moves to work with", "Large moves to work with"],
        ["Almost no event exposure", "Sits through results and news"],
      ],
    },
    question: "What does a trader trade away by holding longer?",
    choices: ["Lower costs", "Control over events — results and news arrive whether you like it or not", "Access to stops", "The ability to use a chart"],
    correct: 1,
    correctFeedback: "Correct. Fewer trades means lower costs and more exposure to things you cannot time.",
    incorrectFeedback: "Longer holds reduce costs. What they add is exposure to scheduled and unscheduled events.",
    takeaway: "Short horizons pay in costs; long horizons pay in event exposure. Neither escapes both.",
  },
  "FND-HZN-009": {
    plain: "The right horizon is the one that matches the time and attention you actually have.",
    detail: "Intraday trading requires being at the screen through the session. Swing trading requires a daily check. Positional needs a weekly review. Choosing a horizon your life cannot support means you will manage the trade badly — not because the method is wrong, but because you are not there.",
    example: "Someone with a full-time job choosing intraday trading ends up glancing at a phone between meetings and making the worst decisions of the session.",
    interaction: "horizon",
    flow: "cause",
    question: "Someone who can only look at the market once each evening chooses intraday trading. What is the likeliest outcome?",
    choices: ["It works if the strategy is good", "The method fails because it needs attention they cannot give", "Costs will be lower", "The stops will be wider"],
    correct: 1,
    correctFeedback: "Correct. A method that requires continuous attention cannot be run intermittently.",
    incorrectFeedback: "A sound intraday method still fails when nobody is watching the session it depends on.",
    takeaway: "Pick the horizon your attention can support. A method you cannot supervise is not a method you can run.",
  },

  // ── Finding Stocks to Trade ─────────────────────────────────────────────────
  "FND-PICK-001": {
    plain: "Trade ideas have to come from somewhere, and 'a stock I heard about' is the worst source.",
    detail: "There are roughly 2,000 actively traded shares on the Indian exchanges. Ideas that arrive by tip, headline or social media arrive after everyone else has seen them, and they arrive without any of the context you would need to size the trade.",
    example: "A stock mentioned in a WhatsApp group at ₹318 comes with no liquidity figure, no trend, no level where you would be wrong — three things you need before you can buy anything.",
    interaction: "ranking",
    flow: "cause",
    question: "What is actually missing from a tip that says 'buy this stock'?",
    choices: ["The company's name", "Everything needed to size and manage it: liquidity, trend, and where the idea fails", "The current price", "The sector"],
    correct: 1,
    correctFeedback: "Correct. A name and a price is not a trade. Without an invalidation level you cannot size the position at all.",
    incorrectFeedback: "The gap is not information about the company — it is the information the trade needs: liquidity, structure, and where you would be wrong.",
    takeaway: "An idea without liquidity, structure and an invalidation point is not yet a trade.",
  },
  "FND-PICK-002": {
    plain: "Before anything else, check that enough shares trade each day for you to get out.",
    detail: "If a share trades 2 lakh shares a day and you need to sell 20,000, you are a tenth of the day's volume. Getting out will move the price against you — and this happens exactly when everyone else wants out too. Liquidity is the first filter because failing it makes every other quality irrelevant.",
    example: "Two stocks look equally attractive. One trades 34 lakh shares a day, the other 2 lakh. Only one of them can be exited quickly at a fair price.",
    interaction: "screener",
    flow: "cause",
    question: "Why is liquidity the first thing to check rather than the last?",
    choices: ["Liquid stocks rise more", "If you cannot exit, none of the stock's other qualities can help you", "It is the easiest number to find", "Regulators require it"],
    correct: 1,
    correctFeedback: "Correct. Everything else is a reason to be in. Liquidity is what lets you leave.",
    incorrectFeedback: "Liquidity does not predict returns. It determines whether you can act on anything you conclude.",
    takeaway: "Check liquidity first. A stock you cannot exit is not a candidate, whatever else is true about it.",
  },
  "FND-PICK-003": {
    plain: "Filtering means writing down conditions and keeping only the shares that meet all of them.",
    detail: "You are not looking for the best stock. You are cutting an unreadable list down to a readable one, so that the slow work — actually looking at charts — is spent on twenty names instead of two thousand.",
    example: "Start with 18 candidates. Require a price above ₹100 and more than 5 lakh shares of average volume, and 13 remain. Nothing has been decided; the list is just readable now.",
    interaction: "screener",
    flow: "build",
    question: "What has a filter accomplished when it cuts a list from 2,000 names to 20?",
    choices: ["It has found the 20 best stocks", "It has made the list small enough to examine properly", "It has removed all the risk", "It has produced 20 trades"],
    correct: 1,
    correctFeedback: "Correct. Filters buy you attention, not answers.",
    incorrectFeedback: "A filter does not rank or decide. It reduces a list to a size a human can actually read.",
    takeaway: "Filtering makes a list readable. It does not make it a list of good trades.",
  },
  "FND-PICK-004": {
    plain: "The two most useful starting filters are a minimum price and a minimum average volume.",
    detail: "A price floor removes shares where one tick is a large percentage move and where costs eat the trade. A volume floor removes shares you cannot exit. Together they usually cut a raw list by more than half, and they do it without any opinion about direction.",
    example: "Price above ₹100 removes two names from an 18-stock list. Average volume above 5 lakh shares removes three more. Thirteen remain.",
    interaction: "screener",
    flow: "build",
    question: "What do price and volume filters have in common?",
    choices: ["Both predict direction", "Both remove stocks you cannot trade properly, without any directional opinion", "Both are fundamental measures", "Both require a chart"],
    correct: 1,
    correctFeedback: "Correct. They are tradeability filters. Direction comes later, from the chart.",
    incorrectFeedback: "Neither says anything about direction. They remove names where execution itself would be the problem.",
    takeaway: "Price and volume filters test tradeability, not opportunity. Apply them first, and apply them bluntly.",
  },
  "FND-PICK-005": {
    plain: "Passing your filters makes a stock a candidate, not a trade.",
    detail: "This is the single most expensive misunderstanding in this part of trading. A filter list has no idea where price is on the chart, whether the move already happened, where you would be wrong, or how many shares you could hold. All of that is work you still have to do.",
    example: "Six stocks pass every filter. Two are extended after a large move, two have no clear level to place a stop against, and one has results next week. One is worth a chart.",
    interaction: "screener",
    flow: "cause",
    question: "Six names pass every filter you set. How many trades do you have?",
    choices: ["Six", "Zero — you have six charts to look at", "One, the highest-ranked", "It depends on your capital"],
    correct: 1,
    correctFeedback: "Correct. Screening produces candidates. Analysis, setup, risk and sizing come afterwards, and most candidates die there.",
    incorrectFeedback: "Passing a filter is not a setup. Every one of the six still needs a chart, a level and a size before it is a trade.",
    takeaway: "Screener → candidates → analysis → setup → risk → trade. Never screener → buy.",
  },
  "FND-PICK-006": {
    plain: "A stock rarely moves alone — it moves with its market and its sector.",
    detail: "Most of a single share's movement comes from the market as a whole and from its industry group. Buying a strong-looking stock in a weak market and a weak sector means fighting two currents to win one race.",
    example: "A pharma stock looks strong on its own chart. The broad market is falling and every other pharma name is falling with it — the setup is real and the current is against it.",
    interaction: "ranking",
    flow: "cause",
    question: "Why check the market and the sector before the individual stock?",
    choices: ["Because sectors are more predictable", "Because most of a stock's movement comes from them, so they set the odds for the trade", "Because it is faster", "Because stocks always follow their sector exactly"],
    correct: 1,
    correctFeedback: "Correct. The stock's own chart is the last of three currents, not the only one.",
    incorrectFeedback: "Individual stocks do not move independently. Market and sector conditions set the background odds.",
    takeaway: "Read the market, then the sector, then the stock. The stock is the smallest of the three currents.",
  },
  "FND-PICK-007": {
    plain: "Comparing two candidates means putting the same facts side by side, not choosing the one you like.",
    detail: "Line up the same measures for both — trend, liquidity, how far the move has already run, where a stop would go, what could derail it. Very often the comparison is decided by the practical items, not by which company sounds more exciting.",
    example: "Both are in uptrends. One trades 34 lakh shares a day and travels 2% daily; the other trades 7 lakh and travels 3.1%. The second needs a much smaller position for the same risk.",
    interaction: "ranking",
    flow: "compare",
    sides: {
      left: "Deccan Motors (synthetic)",
      right: "Vindhya Autoparts (synthetic)",
      rows: [
        ["34 lakh shares a day", "7 lakh shares a day"],
        ["Travels about 2.0% a day", "Travels about 3.1% a day"],
        ["Large company, ₹92,000 cr", "Small company, ₹4,200 cr"],
      ],
    },
    question: "Both are in uptrends. What does the comparison actually decide?",
    choices: ["Which company is better", "How large a position each can carry, and how easily you could exit", "Which will rise more", "Which is cheaper"],
    correct: 1,
    correctFeedback: "Correct. The comparison settles practical questions. It does not settle which one goes up.",
    incorrectFeedback: "A side-by-side comparison of liquidity and daily travel answers sizing and exit questions, not future returns.",
    takeaway: "Compare candidates on the same facts. Usually it decides size and exit, not direction.",
  },
  "FND-PICK-008": {
    plain: "Most candidates get rejected, and that is the screening process working correctly.",
    detail: "A shortlist of twenty might produce one or two trades. Rejecting eighteen is not a failure to find anything — it is what protects you from taking a position in a name that had no level to place a stop against. The list exists to be cut.",
    example: "Thirteen pass the filters. Ten are removed on the chart, two on event risk. One is traded. That is a normal week, not a bad one.",
    interaction: "ranking",
    flow: "cause",
    question: "You screen, review thirteen charts and take no trade. What happened?",
    choices: ["The screen failed", "The process worked — nothing met the standard, which is a normal outcome", "The filters were too loose", "You should widen the search until something qualifies"],
    correct: 1,
    correctFeedback: "Correct. Lowering the standard until something passes is how a good process turns into a bad one.",
    incorrectFeedback: "Finding nothing is a legitimate result. The alternative — trading something because you looked — is the actual failure.",
    takeaway: "Most candidates should be rejected. A screen that always yields a trade is a screen you are overriding.",
  },
};
