import type { Authored } from "../curriculum.ts";

/** Intraday trading. The module leans on the replay interaction, because the only honest way
 *  to teach session reading is to hide the next candle. Nothing here is presented as a signal
 *  that pays; each technique is paired with the conditions in which it stops working. */
export const intradayContent: Record<string, Authored> = {
  "APP-DAY-001": {
    plain: "Intraday trading means opening and closing every position inside the same session.",
    detail: "Nothing is carried overnight, so no gap can reach you. In exchange every trade has a deadline, and the deadline does not care whether your idea has had time to work — at the close, the position ends either way.",
    example: "Buy Deccan Motors at 10:20 at ₹649, sell at 13:15 at ₹662. By 15:30 the position must be flat, profit or loss.",
    interaction: "replay",
    flow: "define",
    question: "What is the defining constraint of an intraday trade?",
    choices: ["Higher leverage", "A hard deadline: the position closes today regardless of the idea", "Tighter spreads", "Lower brokerage"],
    correct: 1,
    correctFeedback: "Correct. The deadline is what makes intraday a distinct discipline rather than a faster version of swing trading.",
    incorrectFeedback: "Leverage and costs are consequences. The defining feature is that the session ends and so does the trade.",
    takeaway: "Intraday removes overnight risk and imposes a deadline. Every other difference follows from that.",
  },
  "APP-DAY-002": {
    plain: "An intraday trade lives for hours; a swing trade lives for weeks.",
    detail: "The consequences run through everything: a 5-minute chart instead of a daily one, stops measured in rupees rather than tens of rupees, larger positions for the same rupee risk, far more trades, and far more total cost. The same idea expressed on the two horizons is two different trades.",
    example: "Same view on Deccan Motors. Intraday: entry 649, stop 644, ₹5 risk, 1,000 shares. Swing: entry 640, stop 612, ₹28 risk, 178 shares.",
    interaction: "horizon",
    flow: "compare",
    sides: {
      left: "Intraday",
      right: "Swing",
      rows: [
        ["Stop measured in rupees", "Stop measured in tens of rupees"],
        ["Large position, same rupee risk", "Small position, same rupee risk"],
        ["Costs paid many times a week", "Costs paid a few times a month"],
      ],
    },
    question: "Why does an intraday trader hold a much larger position for the same rupee risk?",
    choices: ["Higher risk tolerance", "The stop is much closer, so the same budget buys more shares", "Leverage is mandatory", "Intraday stocks are cheaper"],
    correct: 1,
    correctFeedback: "Correct — and that larger position is why intraday slippage and costs matter so much more.",
    incorrectFeedback: "Same budget divided by a smaller risk per share gives a larger position. Nothing about risk appetite changed.",
    takeaway: "A tighter stop buys a larger position. That is why intraday execution quality matters more.",
  },
  "APP-DAY-003": {
    plain: "The first thirty minutes of a session are the most volatile and the least informative.",
    detail: "Orders accumulated overnight execute at the open, so volume and range are at their largest while the day's direction is genuinely undecided. Many intraday methods simply refuse to trade before 9:45 — not because the open is unprofitable, but because it is the hardest part of the day to read.",
    example: "Deccan Motors gaps to ₹646 from ₹640 and covers a ₹6 range in the first six candles, resolving nothing.",
    interaction: "replay",
    flow: "cause",
    question: "Why is the open both the most active and the least informative part of the session?",
    choices: ["Data feeds lag at the open", "Overnight orders execute at once, producing large movement before direction is settled", "Spreads are widest then", "Institutions do not trade at the open"],
    correct: 1,
    correctFeedback: "Correct. Accumulated orders create range without creating information about the rest of the day.",
    incorrectFeedback: "The activity is real order flow clearing at once. It produces movement, not a resolved direction.",
    takeaway: "The open is loud and undecided. Many methods wait for it to finish before doing anything.",
  },
  "APP-DAY-004": {
    plain: "The opening range is the high and low made during the first part of the session, usually 15 to 30 minutes.",
    detail: "It gives the day two reference levels that everyone can see. Its value is as a framework — above the range the day is behaving one way, below it another — and not as a signal. Ranges break in both directions, often more than once.",
    example: "By 09:45 Deccan Motors has traded between ₹644 and ₹650. Those two numbers become the levels the rest of the session is measured against.",
    interaction: "replay",
    flow: "build",
    question: "What has an opening range given you by 09:45?",
    choices: ["The direction of the day", "Two reference levels the session can be read against", "An entry signal", "The day's high and low"],
    correct: 1,
    correctFeedback: "Correct. A framework, not a forecast — and one that gets broken in both directions on many days.",
    incorrectFeedback: "The range is a pair of levels. Which way it resolves, and whether that holds, is a separate question.",
    takeaway: "The opening range provides reference levels. It does not provide direction.",
  },
  "APP-DAY-005": {
    plain: "A trend day is a session that moves in one direction and closes near its extreme.",
    detail: "Pullbacks are shallow and get bought quickly, which makes fading them expensive. Trend days are a minority of sessions but produce most of the profit available to trend-following intraday methods — and they are only clearly identifiable some way into the day.",
    example: "Price leaves the opening range by 10:30 and never returns to it, closing within ₹2 of the day's high.",
    interaction: "replay",
    flow: "classify",
    question: "Price left the opening range two hours ago and has not returned. What does that suggest about tactics?",
    choices: ["Fade the next push", "Pullbacks are more likely to be bought than to reverse the day", "Close all positions", "The range will reassert itself"],
    correct: 1,
    correctFeedback: "Correct. On a trend day, joining shallow pullbacks works and fading strength does not.",
    incorrectFeedback: "Sustained distance from the opening range is the signature of a trend day, where fading is the losing tactic.",
    takeaway: "Trend days punish fading. Identify the day type before choosing tactics.",
  },
  "APP-DAY-006": {
    plain: "A range day is a session that oscillates between two levels without going anywhere.",
    detail: "Most sessions look more like this than like a trend day. Breakout tactics bleed here — each push beyond the edge fails and reverses — while fading the edges works until the day that finally resolves. Naming the day type is what decides which mistake you make.",
    example: "Six attempts to clear ₹652 and five to break ₹645, all failing, for four hours.",
    interaction: "replay",
    flow: "classify",
    question: "Why do breakout tactics bleed on a range day?",
    choices: ["Volume is too low", "Every push past the edge fails, and each failure is a small loss", "Spreads widen", "Brokerage rises"],
    correct: 1,
    correctFeedback: "Correct. The range manufactures the exact signal a breakout trader acts on, then invalidates it.",
    incorrectFeedback: "The mechanism is repeated failed pushes, each one a small loss for a method built to follow them.",
    takeaway: "Range days are the common case and they punish breakout tactics. Classify the day before you act.",
  },
  "APP-DAY-007": {
    plain: "An intraday breakout is price clearing a level that has been holding it during the session.",
    detail: "The levels that matter are the ones everybody can see: the opening range, the previous day's high and low, the day's own extremes. It tries to capture the move once those orders clear, and it fails constantly, because the same visibility that makes a level tradeable makes it a target.",
    example: "Price clears the opening range high at ₹650, runs to ₹653, then falls back to ₹646 within twenty minutes.",
    interaction: "replay",
    flow: "cause",
    question: "Why do intraday breakouts fail so often at obvious levels?",
    choices: ["The levels are wrong", "Visible levels concentrate orders, and a push through one can be what consumes them", "Volume is unreliable intraday", "Exchanges intervene"],
    correct: 1,
    correctFeedback: "Correct. Concentrated orders are liquidity, and a move to that liquidity is not the same as a move beyond it.",
    incorrectFeedback: "The levels are correct — that is the problem. Everyone sees them, orders cluster, and a push consumes rather than continues.",
    takeaway: "Intraday breakouts target visible levels, which is exactly why they are frequently consumed rather than followed.",
  },
  "APP-DAY-008": {
    plain: "An intraday pullback buys a temporary dip within a session that is already trending.",
    detail: "It gives a defined failure point — the low of the pullback — and a better price than chasing. It works while the day is trending and loses steadily on range days, where every pullback continues into the other side of the range.",
    example: "Price rises from ₹646 to ₹662, eases to ₹657, then resumes. Entry on the first 5-minute close back above the previous candle's high, stop below ₹657.",
    interaction: "replay",
    flow: "build",
    question: "What does an intraday pullback entry give you that chasing does not?",
    choices: ["A higher win rate", "A nearby failure point, and therefore a tighter stop and a larger position", "Lower slippage", "Confirmation the trend continues"],
    correct: 1,
    correctFeedback: "Correct. The pullback low is the invalidation, and its closeness is what makes the trade sizeable.",
    incorrectFeedback: "It confirms nothing. What it provides is a nearby level where the idea is wrong.",
    takeaway: "Pullbacks supply a nearby invalidation. That is the whole advantage over chasing.",
  },
  "APP-DAY-009": {
    plain: "VWAP is the average price of the session weighted by how much traded at each price.",
    detail: "It approximates the average price participants actually paid today, which is why large orders are often measured against it. Traders use it as a reference for whether buyers or sellers have the better position so far — and like every average, it is computed from the past and lags what is happening now.",
    example: "Price at ₹662 with VWAP at ₹653 means the average participant today paid ₹653; anyone who bought at the average is ahead.",
    interaction: "replay",
    flow: "define",
    question: "What does VWAP actually measure?",
    choices: ["Where price should be", "The volume-weighted average price paid so far today", "Institutional buying interest", "The day's midpoint"],
    correct: 1,
    correctFeedback: "Correct. It is a descriptive average of what has already traded, not a fair-value estimate.",
    incorrectFeedback: "VWAP is an average of executed trades weighted by size. It carries no view about where price belongs.",
    takeaway: "VWAP is the session's volume-weighted average price. Descriptive, backward-looking, widely watched.",
  },
  "APP-DAY-010": {
    plain: "Intraday moving averages smooth the last few candles so the session's direction is easier to see.",
    detail: "A 20-period average on a 5-minute chart summarises roughly the last hour and a half. It helps when the session is trending and produces constant crossovers when it is not — which describes most sessions, and is why crossovers are a poor intraday trigger on their own.",
    example: "On a trending morning the 20-period average slopes cleanly upward. Through a midday range it crosses price eleven times in two hours.",
    interaction: "replay",
    flow: "cause",
    question: "Why are moving-average crossovers unreliable as intraday triggers?",
    choices: ["They lag by a fixed amount", "Range conditions produce constant crossovers, and ranges are the common case", "They need too much data", "They only work on daily charts"],
    correct: 1,
    correctFeedback: "Correct. A crossover method generates its most signals in exactly the conditions where they are worthless.",
    incorrectFeedback: "Lag is real but manageable. The bigger problem is that ranging sessions manufacture crossovers continuously.",
    takeaway: "Intraday averages help in trends and mislead in ranges. Ranges are the majority.",
  },
  "APP-DAY-011": {
    plain: "Intraday momentum is how fast and how far price has moved in the last few candles.",
    detail: "It is what makes a move worth joining rather than fading, and it fades quickly — a burst that looks powerful at 10:15 can be entirely spent by 10:35. Momentum entries therefore need an invalidation close by, because their whole premise expires within minutes.",
    example: "Four consecutive 5-minute candles closing near their highs, covering ₹7. The fifth candle closes near its low and the burst is over.",
    interaction: "replay",
    flow: "classify",
    question: "What is the practical consequence of intraday momentum expiring quickly?",
    choices: ["Momentum trades should be held longer", "The invalidation must be close and acted on quickly", "Momentum should be ignored", "Stops should be wide"],
    correct: 1,
    correctFeedback: "Correct. A premise that expires in minutes needs a failure point that is minutes away.",
    incorrectFeedback: "A short-lived premise demands a nearby, quickly enforced invalidation — not patience.",
    takeaway: "Intraday momentum expires fast. The invalidation has to be close and enforced.",
  },
  "APP-DAY-012": {
    plain: "Intraday volume tells you how many participants were involved in a given move.",
    detail: "It follows a reliable shape: heavy at the open, thin through the middle of the day, heavy again into the close. Judging a move's volume means comparing it with the same time on previous days, not with the session's own average — otherwise every midday move looks weak and every opening move looks strong.",
    example: "A push at 12:30 on 40,000 shares looks feeble against the session average, and is heavy for 12:30.",
    interaction: "replay",
    flow: "cause",
    question: "Why compare intraday volume with the same time of day rather than the session average?",
    choices: ["Data is more accurate that way", "Volume follows a daily shape, so the session average makes every midday move look weak", "It reduces noise", "The exchange publishes it that way"],
    correct: 1,
    correctFeedback: "Correct. Without a time-of-day adjustment, volume comparisons mostly rediscover the shape of the session.",
    incorrectFeedback: "The intraday volume curve is highly predictable. Comparing against the flat average measures the clock, not participation.",
    takeaway: "Compare intraday volume against the same clock time. The session average measures the time of day.",
  },
  "APP-DAY-013": {
    plain: "Intraday volatility is how much price typically travels within the session.",
    detail: "It also follows the clock: wide at the open, narrow at midday, widening again into the close. A stop that is sensibly outside the noise at 12:30 sits well inside it at 09:20, which is why a single fixed stop distance behaves like two different rules across one session.",
    example: "Deccan Motors averages ₹1.60 of range per 5-minute candle at the open and ₹0.55 at 12:40. A fixed ₹2 stop is loose at midday and tight at the open.",
    interaction: "replay",
    flow: "calculate",
    question: "You use a fixed ₹2 stop all session. What happens?",
    choices: ["It works consistently", "It is tight at the open and loose at midday — two different rules in one", "It gets safer through the day", "It only works on trend days"],
    correct: 1,
    correctFeedback: "Correct. A constant stop against a varying noise level is not a constant rule.",
    incorrectFeedback: "Intraday volatility varies by the clock, so a fixed distance means something different at each hour.",
    takeaway: "Intraday volatility follows the clock. A fixed stop distance is not a fixed rule.",
  },
  "APP-DAY-014": {
    plain: "Intraday support and resistance are levels where price has turned earlier in the same session.",
    detail: "They are made of orders placed today, so they are far more perishable than daily levels — a level that held three times in the morning can mean nothing after lunch. They are useful for placing stops and targets, and weak as reasons to enter.",
    example: "₹652 rejects price three times before 11:00 and is cut through without pausing at 13:20.",
    interaction: "replay",
    flow: "define",
    question: "Why are intraday levels more perishable than daily levels?",
    choices: ["They are less accurate", "They are made of orders placed today, and those get used up or withdrawn", "Fewer traders watch them", "They are computed differently"],
    correct: 1,
    correctFeedback: "Correct. Same mechanism as any level — resting orders — but with a much shorter shelf life.",
    incorrectFeedback: "Intraday levels are real. They simply consist of orders from a single session, which are consumed or cancelled quickly.",
    takeaway: "Intraday levels are today's orders. Good for stops and targets, weak as entry reasons.",
  },
  "APP-DAY-015": {
    plain: "The previous day's high and low are the most watched levels of the new session.",
    detail: "They carry over from yesterday, so unlike intraday levels they are visible before the session starts and are watched by everyone. Price reaching them tends to produce a reaction — and that reaction is as often a rejection as a continuation.",
    example: "Yesterday's high was ₹651. Today price stalls at ₹650.80 twice before 11:00, then clears it on the third attempt.",
    interaction: "replay",
    flow: "classify",
    question: "Price approaches yesterday's high. What can you reasonably expect?",
    choices: ["A breakout", "A reaction of some kind — rejection or continuation, not specified", "A reversal", "Nothing"],
    correct: 1,
    correctFeedback: "Correct. Widely watched levels produce reactions. Which direction the reaction goes is a separate question.",
    incorrectFeedback: "Attention at a level means a reaction is likely. The level says nothing about which way it resolves.",
    takeaway: "Yesterday's high and low reliably produce reactions and never specify the direction.",
  },
  "APP-DAY-016": {
    plain: "A gap is when today's open is far from yesterday's close, and it changes how the session behaves.",
    detail: "Everyone holding overnight is immediately in profit or in trouble, which produces order flow that has nothing to do with today's news. Gaps sometimes fill back to the previous close and sometimes run away from it; treating either as the rule is how gap trading loses money.",
    example: "Deccan Motors closes at ₹640 and opens at ₹646. Everyone short overnight is under pressure from the first tick.",
    interaction: "replay",
    flow: "cause",
    question: "What does a gap reliably create?",
    choices: ["A move back to the previous close", "Order flow from positions that are immediately in profit or trouble", "A trend day", "Higher volume all session"],
    correct: 1,
    correctFeedback: "Correct. The pressure on overnight positions is the reliable part. Whether the gap fills is not.",
    incorrectFeedback: "Gap fills happen and so do gap runs. What is reliable is the pressure the gap puts on existing positions.",
    takeaway: "Gaps reliably create pressure on overnight positions. They do not reliably fill.",
  },
  "APP-DAY-017": {
    plain: "Intraday multi-timeframe means using a slower chart for context and a faster one for entry.",
    detail: "A 15-minute chart shows the session's structure without the noise; a 5-minute or 1-minute chart times the entry inside it. The same rule as swing trading applies: the slower chart never times anything, and the faster chart never decides direction.",
    example: "The 15-minute chart shows a clear trend; the 5-minute shows the pullback within it. Direction from the first, timing from the second.",
    interaction: "replay",
    flow: "sequence",
    steps: [
      "15-minute chart: is the session trending or ranging, and where are the session's levels?",
      "5-minute chart: is there a defined setup inside that structure?",
      "5-minute chart: where does the setup fail, and how many rupees away is that?",
      "Size from that distance, then stop consulting the faster chart for direction.",
    ],
    question: "Which chart decides whether the session is trending?",
    choices: ["The 1-minute", "The slower chart — the 15-minute", "Whichever agrees with the position", "Both equally"],
    correct: 1,
    correctFeedback: "Correct. Context above, timing below, and never the reverse.",
    incorrectFeedback: "The slower chart establishes structure. The faster chart only times entries inside it.",
    takeaway: "Slower chart for structure, faster chart for timing. The roles do not swap.",
  },
  "APP-DAY-018": {
    plain: "Intraday trading needs liquid stocks, because you trade large size against small moves.",
    detail: "An intraday position is often several times larger than a swing position, and it is entered and exited on the same day. In a thin stock the spread and the impact of your own order can exceed the entire move you were trying to capture.",
    example: "A ₹4 intraday target on a stock with a ₹0.40 spread and ₹0.30 of slippage each way gives up 25% of the move to execution.",
    interaction: "order_book",
    flow: "calculate",
    question: "A ₹4 intraday target, ₹0.40 spread, ₹0.30 slippage each way. How much of the move survives?",
    choices: ["All of it", "About ₹3 — a quarter is consumed by execution", "About ₹2", "It cannot be calculated"],
    correct: 1,
    correctFeedback: "Correct. Roughly ₹1 of a ₹4 move goes to spread and slippage before any brokerage.",
    incorrectFeedback: "Add the spread and both slippage legs: about ₹1 of the ₹4 target disappears into execution.",
    takeaway: "Intraday moves are small, so execution costs are a large share of them. Liquidity is not optional.",
  },
  "APP-DAY-019": {
    plain: "Index instruments are traded intraday because they are deeply liquid and move on broad news rather than single-company events.",
    detail: "A NIFTY position cannot be blindsided by one company's announcement, and the depth means large size fills without moving the price. The trade-off is that index moves are smaller in percentage terms and driven by macro flow that gives very little advance warning.",
    example: "A single company's disappointing results can move that stock 8% and the index 0.2%. The index removes company-specific risk and dilutes company-specific opportunity.",
    interaction: "replay",
    flow: "compare",
    sides: {
      left: "Trading a stock intraday",
      right: "Trading the index intraday",
      rows: [
        ["One company's news can dominate", "Diluted across many companies"],
        ["Larger percentage moves", "Smaller percentage moves"],
        ["Liquidity varies by name", "Consistently deep"],
      ],
    },
    question: "What does trading the index intraday remove, and what does it cost?",
    choices: ["All risk, at the cost of returns", "Single-company surprise, at the cost of smaller percentage moves", "Slippage, at the cost of liquidity", "Nothing"],
    correct: 1,
    correctFeedback: "Correct. Diversification within the instrument cuts both the specific risk and the specific opportunity.",
    incorrectFeedback: "The index dilutes company-specific events in both directions — smaller shocks and smaller moves.",
    takeaway: "The index removes single-company surprise and dilutes single-company opportunity equally.",
  },
  "APP-DAY-020": {
    plain: "Entry timing intraday means waiting for the specific candle that confirms the setup, not the general idea.",
    detail: "The difference between entering on a 5-minute close above a level and entering as price touches it is often a rupee or two — which on a ₹5 stop is a large share of the risk. A written trigger removes the temptation to act on the idea before the evidence.",
    example: "Trigger: a 5-minute close above ₹650 with the candle closing in its upper third. Touching ₹650 intrabar is not the trigger.",
    interaction: "replay",
    flow: "define",
    question: "Why write the trigger as a specific candle condition?",
    choices: ["To reduce brokerage", "Because a rupee or two of timing is a large share of a ₹5 intraday stop", "To satisfy the broker", "Because touches are not recorded"],
    correct: 1,
    correctFeedback: "Correct. When the stop is small, entry precision is a large proportion of the trade's risk.",
    incorrectFeedback: "With a tight stop, small timing differences consume a large share of the risk budget.",
    takeaway: "Write the trigger as a specific candle event. On a small stop, timing is a large part of the risk.",
  },
  "APP-DAY-021": {
    plain: "An intraday stop goes just beyond the level that would prove the setup wrong, usually a few rupees away.",
    detail: "Because the distance is small, the stop must clear the current noise level for that time of day, and it must be honoured immediately — an intraday stop that is 'given room' becomes a swing position you never planned, at a size chosen for a ₹5 risk.",
    example: "Pullback low ₹657, stop ₹656.20, entry ₹659. Risk ₹2.80 per share. Widening it to ₹8 because price 'nearly held' triples the loss.",
    interaction: "replay",
    flow: "judge",
    question: "Price breaks your intraday stop by 20 paise and you decide to hold. What have you created?",
    choices: ["A better entry", "An unplanned position sized for a much smaller risk", "A swing trade", "Nothing significant"],
    correct: 1,
    correctFeedback: "Correct. The size was calculated for the original stop, so every rupee beyond it is unbudgeted loss.",
    incorrectFeedback: "The size was computed from the original distance. Extending the stop multiplies the loss the position was built for.",
    takeaway: "Honour intraday stops immediately. The size was chosen for that exact distance.",
  },
  "APP-DAY-022": {
    plain: "Intraday targets are set at the next visible level, because that is where the move is likely to meet supply.",
    detail: "The candidates are the opening-range extremes, yesterday's high and low, VWAP, and the session's own extremes. Setting a target as a fixed rupee amount ignores where the orders actually are, and often places it just beyond a level the move was never going to clear.",
    example: "Entry ₹659 with yesterday's high at ₹665.40. A target at ₹665 fills ahead of the level; a target at ₹667 requires the move to clear it first.",
    interaction: "replay",
    flow: "judge",
    question: "Why set the target just below the next level rather than beyond it?",
    choices: ["It looks better on paper", "Supply sits at the level, so filling before it is more likely", "It reduces slippage", "Targets must be round numbers"],
    correct: 1,
    correctFeedback: "Correct. Queue ahead of the crowd rather than behind it.",
    incorrectFeedback: "The level is where resting orders sit. A target just short of it fills more reliably than one beyond it.",
    takeaway: "Place intraday targets at visible levels, slightly ahead of the supply rather than past it.",
  },
  "APP-DAY-023": {
    plain: "An intraday trailing stop follows the move up, usually below each new higher low.",
    detail: "It tries to keep you in a trend day while ensuring a winner does not turn into a loser. Intraday it is harder than on a daily chart, because the noise level changes through the session — a trail that is sensible at 10:00 is far too tight by 12:30.",
    example: "Trail below each new 5-minute swing low. During the midday range those lows sit close together and the trail exits on ordinary noise.",
    interaction: "replay",
    flow: "judge",
    question: "Why is a fixed intraday trail harder to run than a daily one?",
    choices: ["Data is noisier", "The session's noise level changes by the hour, so one trail distance means different things", "Brokerage is higher", "Trailing is not possible intraday"],
    correct: 1,
    correctFeedback: "Correct. The same distance is loose at the open and tight at midday.",
    incorrectFeedback: "The problem is the intraday volatility curve. One distance behaves differently at each part of the session.",
    takeaway: "Intraday trails must account for the time of day. Noise is not constant across a session.",
  },
  "APP-DAY-024": {
    plain: "Intraday position sizing uses the same formula as any other trade, with a much smaller stop.",
    detail: "Risk budget divided by risk per share. Because the stop is small, the resulting position is large — often several times a swing position — and that is exactly why an ignored stop is so dangerous. The formula assumes the stop is honoured.",
    example: "₹5,00,000 capital, 0.5% risk is ₹2,500. Stop ₹2.80 away gives 892 shares — about ₹5.9 lakh of exposure from a ₹2,500 risk budget.",
    interaction: "risk",
    flow: "calculate",
    question: "₹2,500 of risk with a ₹2.80 stop. What is the position, and what is the exposure at ₹659?",
    choices: ["892 shares, about ₹5.9 lakh", "892 shares, about ₹2,500", "250 shares, about ₹1.6 lakh", "2,500 shares, about ₹16 lakh"],
    correct: 0,
    correctFeedback: "Correct. A small stop produces a large position — which is safe only while the stop is honoured.",
    incorrectFeedback: "₹2,500 ÷ ₹2.80 ≈ 892 shares, and 892 × ₹659 ≈ ₹5.9 lakh of exposure.",
    takeaway: "Small stops create large positions. The arithmetic is only safe if the stop is enforced.",
  },
  "APP-DAY-025": {
    plain: "Slippage matters more intraday because the moves are small and the positions are large.",
    detail: "Losing ₹0.30 on entry and exit is 2% of a ₹15 swing move and 12% of a ₹5 intraday move. Multiply that by a position several times larger and by many trades a week, and execution quality becomes a bigger factor than setup selection.",
    example: "Six trades a day at ₹0.60 of round-trip slippage on 892 shares is about ₹3,200 a day before brokerage.",
    interaction: "order_book",
    flow: "calculate",
    question: "892 shares, ₹0.60 round-trip slippage, six trades a day. What is the daily cost?",
    choices: ["₹535", "₹3,200", "₹5,350", "₹536"],
    correct: 1,
    correctFeedback: "Correct: 892 × ₹0.60 × 6 ≈ ₹3,200 a day, before brokerage and taxes.",
    incorrectFeedback: "Multiply shares by slippage by trades: 892 × 0.60 × 6.",
    takeaway: "Intraday slippage scales with size and frequency. It can exceed the edge from setup selection.",
  },
  "APP-DAY-026": {
    plain: "Overtrading is taking more trades than your method actually produces.",
    detail: "It usually comes from being present all session with nothing qualifying, and it shows up as trades you cannot justify afterwards. Each one carries full costs and full slippage, so the arithmetic degrades quickly even when the individual decisions look harmless.",
    example: "A method producing two setups a day becomes nine trades. Seven were not the method, and they cost ₹5,600 in execution alone.",
    interaction: "expectancy",
    flow: "cause",
    question: "What is the clearest sign of overtrading?",
    choices: ["Losing money", "Trades you cannot map back to a rule afterwards", "Trading before 10:00", "Holding positions too long"],
    correct: 1,
    correctFeedback: "Correct. The test is attribution, not outcome — an unattributable winner is the same problem as a loser.",
    incorrectFeedback: "Losses happen inside a good process too. The diagnostic is whether each trade maps to a rule.",
    takeaway: "Count trades against what your method should produce. Unattributable trades are the symptom.",
  },
  "APP-DAY-027": {
    plain: "The revenge-trading spiral is a loss, an urge to recover it immediately, a larger position, and a worse loss.",
    detail: "Intraday it runs faster than anywhere else, because the next opportunity is five minutes away rather than next week. The defences are structural, not motivational: a hard loss limit, a mandatory pause after a losing trade, and a size that cannot be changed mid-session.",
    example: "Down ₹4,000 at 10:40, doubles size at 10:45, down ₹15,000 by 11:20 — twenty minutes of decisions the plan never contained.",
    interaction: "risk",
    flow: "sequence",
    steps: [
      "A loss lands, and it feels larger than the number.",
      "The next setup arrives within minutes, before the feeling passes.",
      "Size increases so one trade can undo the loss.",
      "The stop gets ignored, because at that size it now hurts too much to take.",
    ],
    question: "Why is the spiral faster intraday than on other horizons?",
    choices: ["Losses are bigger", "The next opportunity arrives within minutes, before the emotion has passed", "Stops are wider", "Leverage is higher"],
    correct: 1,
    correctFeedback: "Correct. The gap between the loss and the next decision is too short for the feeling to fade.",
    incorrectFeedback: "The mechanism is timing. A five-minute gap between a loss and the next chance to act is what makes it fast.",
    takeaway: "The spiral is fast intraday. Defend with a hard limit and a mandatory pause, not willpower.",
  },
  "APP-DAY-028": {
    plain: "Different parts of the session behave differently, and the differences are consistent enough to plan around.",
    detail: "The open is volatile and undecided; late morning often produces the day's clearest trend; midday is quiet and range-bound; the last hour brings volume back with position-squaring flows. Most intraday methods work in one or two of those windows and lose money in the others.",
    example: "A breakout method producing good results between 10:00 and 11:30 gives most of it back trading the same signals between 12:00 and 14:00.",
    interaction: "replay",
    flow: "classify",
    question: "Your method works from 10:00 to 11:30 and loses from 12:00 to 14:00. What is the sensible response?",
    choices: ["Adjust the parameters for midday", "Restrict the method to the window where it works", "Increase size in the morning to compensate", "Trade a different stock at midday"],
    correct: 1,
    correctFeedback: "Correct. A time filter is one of the cheapest and most honest filters available.",
    incorrectFeedback: "Re-tuning for conditions the method was not built for is fitting. Not trading those hours is the direct answer.",
    takeaway: "Sessions have consistent phases. Restrict your method to the window it was built for.",
  },
  "APP-DAY-029": {
    plain: "Knowing when to stop trading for the day is a rule you write before the session, not a judgement you make during it.",
    detail: "The triggers worth writing down are a loss limit, a number of consecutive losses, and a state check — if you are trading to recover rather than because a setup appeared, the day is over. All three exist because the moment you should stop is the moment you least want to.",
    example: "Rules: stop at −2% of capital, stop after three consecutive losses, stop if the last trade was not on the list. Any one of them ends the session.",
    interaction: "risk",
    flow: "judge",
    question: "Why must stopping rules be written before the session?",
    choices: ["To satisfy the broker", "Because the moment you should stop is the moment you least want to", "To track performance", "Because rules cannot be changed intraday"],
    correct: 1,
    correctFeedback: "Correct. The rule exists to overrule the version of you that is losing.",
    incorrectFeedback: "The reason is behavioural: a judgement made while down is not the judgement you would make while calm.",
    takeaway: "Write the stopping rules before the session. In-session judgement is exactly what they replace.",
  },
  "APP-DAY-030": {
    plain: "An intraday loss limit caps what a single session can cost you.",
    detail: "It is more urgent intraday than on any other horizon, because the number of decisions available in one day is enormous. A limit of 1–2% of capital, enforced by closing the platform, converts a potentially unbounded day into a known, survivable one.",
    example: "₹5,00,000 capital with a 2% daily limit is ₹10,000. At ₹2,500 of risk per trade, four losses end the session.",
    interaction: "risk",
    flow: "calculate",
    question: "₹5,00,000 capital, 2% daily limit, ₹2,500 risk per trade. How many losses end the day?",
    choices: ["Two", "Four", "Ten", "Twenty"],
    correct: 1,
    correctFeedback: "Correct: ₹10,000 ÷ ₹2,500 = 4. Knowing that number in advance is the point of the limit.",
    incorrectFeedback: "Divide the daily limit by the per-trade risk: ₹10,000 ÷ ₹2,500.",
    takeaway: "A daily limit converts an unbounded session into a known number of permitted losses.",
  },
  "APP-DAY-031": {
    plain: "Intraday leverage is dangerous because it multiplies a position that is already large by design.",
    detail: "The intraday position is big because the stop is small — that is the arithmetic working correctly. Adding leverage on top multiplies an already-large exposure, so the account survives only while every stop is honoured perfectly. One ignored stop at that size can end it.",
    example: "₹5.9 lakh of exposure from ₹2,500 of risk is already 118× the risk budget. A leveraged version of the same trade turns one ignored stop into a capital event.",
    interaction: "risk",
    flow: "judge",
    question: "Why is leverage particularly dangerous intraday rather than merely amplifying?",
    choices: ["Intraday markets are less liquid", "The position is already large because the stop is small, so leverage multiplies an amplified exposure", "Leverage costs more intraday", "Stops cannot be used with leverage"],
    correct: 1,
    correctFeedback: "Correct. Leverage compounds an exposure that the tight stop already made large.",
    incorrectFeedback: "The tight stop has already produced a large position. Leverage multiplies that, not a small base.",
    takeaway: "The tight intraday stop already creates a large position. Leverage stacks on top of that.",
  },
  "APP-DAY-032": {
    plain: "Reading a session honestly means deciding without seeing the next candle.",
    detail: "Every chart you review after the close is obvious, because the outcome is printed on it. The only way to test whether you can actually read a session is to step through it one candle at a time and commit to a call before the next one appears — which is what the replay does.",
    example: "At 11:20 the session looks like a trend day and the trade is clear. Two hours later it has been a range for four hours, and the 11:20 decision looks quite different.",
    interaction: "replay",
    flow: "plan",
    question: "Why does reviewing charts after the close overstate your ability?",
    choices: ["The data is different", "The outcome is visible, so the decision that led to it feels obvious", "Closing prices are less accurate", "Volume is revised"],
    correct: 1,
    correctFeedback: "Correct. Hindsight makes every decision look available at the time. Stepping through one candle at a time removes that.",
    incorrectFeedback: "The data is identical. What differs is that you can see the outcome, which makes the decision look easier than it was.",
    takeaway: "Test session reading by hiding the next candle. A reviewed chart always looks obvious.",
  },
};
