import type { Authored } from "../curriculum.ts";

/** Classical chart patterns, placed after Price Action so structure and context come first.
 *  Each named pattern is taught the same way: what the shape is, what it is trying to capture,
 *  why that might work, and what breaks it. None of them is presented as a signal that pays. */
export const patternsContent: Record<string, Authored> = {
  "APP-PAT-001": {
    plain: "A chart pattern is a recognisable shape formed by several weeks of price moving between the same levels.",
    detail: "Unlike a candlestick pattern, which covers a few periods, a chart pattern is built from the swing structure you already know how to read — highs, lows, and the levels where price keeps turning. The name is a shorthand for an arrangement of those swings.",
    example: "Highs stalling near one price while lows keep rising toward it is called an ascending triangle. The name describes a swing arrangement, nothing more.",
    interaction: "chart_pattern",
    flow: "define",
    question: "What is a chart pattern made of?",
    choices: ["Indicator readings", "An arrangement of swing highs and lows relative to levels", "Volume bars", "Candlestick shapes"],
    correct: 1,
    correctFeedback: "Correct. Patterns are structure with a label attached — which means everything you know about structure applies to them.",
    incorrectFeedback: "Chart patterns are built from swings and levels. They are named arrangements of the structure you already read.",
    takeaway: "A chart pattern is a named arrangement of swing structure. Nothing in it is separate from structure.",
  },
  "APP-PAT-002": {
    plain: "Patterns can work because they mark where large numbers of orders are resting.",
    detail: "A level tested four times has stops, entries and resting limit orders piled just beyond it. When price finally goes there, those orders execute in quick succession and the move accelerates. That mechanism is real — and it is a claim about order concentration, not about the shape being magic.",
    example: "A ceiling at 104 that has held three times collects buy stops just above it. Price reaching 104.20 triggers them all within minutes.",
    interaction: "chart_pattern",
    flow: "cause",
    question: "What is the actual mechanism behind a pattern breakout accelerating?",
    choices: ["Traders recognising the pattern and buying", "Orders resting just beyond a tested level all executing at once", "Indicators triggering simultaneously", "Institutional algorithms defending shapes"],
    correct: 1,
    correctFeedback: "Correct. It is an order-flow mechanism. Recognition matters only because it is why the orders are placed there.",
    incorrectFeedback: "The acceleration comes from clustered orders executing together, not from the shape itself.",
    takeaway: "Patterns work through order concentration at tested levels. That is the whole mechanism.",
  },
  "APP-PAT-003": {
    plain: "Continuation patterns pause an existing move; reversal patterns end one.",
    detail: "The division matters because it tells you what has to already be true. A continuation pattern needs a prior trend to continue — without one it is describing noise. A reversal pattern needs an established move to reverse, and the more extended that move, the more there is to unwind.",
    example: "A flag with no prior advance is not a flag, it is a small range. A double top after four sideways months is not topping anything.",
    interaction: "chart_pattern",
    flow: "compare",
    sides: {
      left: "Continuation",
      right: "Reversal",
      rows: [
        ["Rectangle, triangles, flag, pennant, cup", "Head and shoulders, double top/bottom, wedges"],
        ["Needs a prior trend to resume", "Needs an established move to end"],
        ["Fails when the trend was already over", "Fails when the move simply pauses and resumes"],
      ],
    },
    question: "A textbook flag forms with no prior advance. What do you have?",
    choices: ["A valid flag", "A small range — the pattern needs a move to continue", "A reversal pattern", "A pennant"],
    correct: 1,
    correctFeedback: "Correct. A continuation pattern with nothing to continue is a shape describing noise.",
    incorrectFeedback: "Flags pause advances. Without the advance, the shape has no move to resume.",
    takeaway: "Continuation needs a trend to resume; reversal needs a move to end. Check that first, always.",
  },
  "APP-PAT-004": {
    plain: "A rectangle is price bouncing between roughly the same high and the same low, several times each.",
    detail: "It tries to capture the resolution of a stalemate: once one boundary gives way, the orders resting there are gone and price can travel. Its weakness is that boundaries are spent by being tested — a rectangle that has held four times has less resting interest left than one that has held twice.",
    example: "Highs at 104, 104.30 and 103.80; lows at 97.60, 97.20 and 97.90. Two levels, three touches each, six weeks.",
    interaction: "chart_pattern",
    flow: "build",
    question: "Which rectangle boundary is more likely to give way: one tested twice or one tested five times?",
    choices: ["The one tested twice — it is less established", "The one tested five times — each test consumes the orders holding it", "They are equally likely", "Neither, once a level is established"],
    correct: 1,
    correctFeedback: "Correct. Levels are made of orders, and testing spends them. Repeated tests weaken rather than confirm.",
    incorrectFeedback: "Each test uses up some of the resting interest that makes the level hold. Five tests leaves less than two.",
    takeaway: "Rectangles capture a stalemate resolving. Repeated tests weaken a boundary rather than confirming it.",
  },
  "APP-PAT-005": {
    plain: "A symmetrical triangle is lower highs and higher lows converging, so the range narrows bar by bar.",
    detail: "It captures compression resolving into expansion, which is a genuine and well-supported observation — narrowing ranges do tend to be followed by wider ones. What it does not do is say which way, and the popular idea that it must resolve before some apex is not something the shape supports.",
    example: "Highs at 106, 104.20, 102.80; lows at 94, 96.40, 98.10. The two sequences converge over five weeks.",
    interaction: "chart_pattern",
    flow: "build",
    question: "What does a symmetrical triangle predict?",
    choices: ["An upward breakout", "A larger range soon — with no direction implied", "A downward breakout", "A reversal of the prior trend"],
    correct: 1,
    correctFeedback: "Correct. Compression forecasts expansion, and nothing about direction. Trading it means preparing for both.",
    incorrectFeedback: "The shape says the range is narrowing. Which side it resolves is not contained in it.",
    takeaway: "Symmetrical triangles forecast expansion, not direction. Prepare for movement, not for a side.",
  },
  "APP-PAT-006": {
    plain: "An ascending triangle is a flat ceiling tested repeatedly with each pullback stopping higher than the last.",
    detail: "It tries to capture buyers willing to pay up sooner each time meeting a fixed block of supply at one price. The rising lows are the informative half. It fails when the rising lows simply run out — and the flat ceiling is where every stop sits, which is what makes it worth probing.",
    example: "Ceiling at 104 touched three times; lows at 96.20, 98.40 and 100.10 between the touches.",
    interaction: "chart_pattern",
    flow: "classify",
    question: "Which half of an ascending triangle carries the information?",
    choices: ["The flat ceiling — supply at one price", "The rising lows — buyers paying up sooner each time", "Both equally", "Neither; the shape is the signal"],
    correct: 1,
    correctFeedback: "Correct. A flat level is common. Demand arriving progressively earlier is the observation worth having.",
    incorrectFeedback: "Flat ceilings are everywhere. The rising lows are what say something is changing beneath the level.",
    takeaway: "The rising lows are the signal in an ascending triangle. The ceiling is just where the stops are.",
  },
  "APP-PAT-007": {
    plain: "A descending triangle is a flat floor tested repeatedly with each rally failing lower than the last.",
    detail: "The mirror of its ascending twin: sellers accepting less each time against a fixed block of demand at one price. The important qualification is the broader trend — in a strong market the flat floor frequently holds and the shape dissolves without resolving.",
    example: "Floor at 97 touched three times; highs at 106, 103.60 and 100.80 between the touches.",
    interaction: "chart_pattern",
    flow: "classify",
    question: "A descending triangle forms in a strongly rising broader market. What is the honest reading?",
    choices: ["A reliable short setup", "A shape whose usual resolution is fighting the broader trend", "Proof the market is topping", "The same as in any other market"],
    correct: 1,
    correctFeedback: "Correct. Patterns are read inside their context, and the broader trend is the largest part of that context.",
    incorrectFeedback: "The shape is the same; the environment is not. A downward resolution here fights the broader current.",
    takeaway: "Descending triangles in rising markets often dissolve. Context outranks the shape.",
  },
  "APP-PAT-008": {
    plain: "A bull flag is a steep advance followed by a shallow drift lower on lighter volume.",
    detail: "It captures a pause in a strong move — profit-taking that never attracts enough selling to reverse anything. The lighter volume during the drift is the part worth checking. If the drift deepens past roughly half the advance, it has stopped being a pause and become something else.",
    example: "A rise from 86 to 109 over nine sessions, then eight sessions drifting to 104 on about a third of the volume.",
    interaction: "chart_pattern",
    flow: "build",
    question: "What turns a flag into something that is no longer a flag?",
    choices: ["The drift lasting more than a week", "The drift retracing much more than about half the advance", "Volume rising during the drift", "The advance being too steep"],
    correct: 1,
    correctFeedback: "Correct. A pause gives back part of the move. Giving back most of it is a different event with a different name.",
    incorrectFeedback: "Depth is the test. A shallow give-back is a pause; a deep one has undone the move it was meant to pause.",
    takeaway: "A flag is a shallow pause on lighter volume. Depth is what disqualifies it.",
  },
  "APP-PAT-009": {
    plain: "A pennant is a steep advance followed by a small converging coil rather than a straight drift.",
    detail: "It captures the same pause a flag does, with the range contracting instead of sloping. Its practical drawback follows from its size: a pennant is small by definition, so the stop sits close to the entry and ordinary noise reaches it easily.",
    example: "A rise from 87 to 110, then twelve sessions coiling between 108.40 and 105.60 on falling volume.",
    interaction: "chart_pattern",
    flow: "compare",
    sides: {
      left: "Flag",
      right: "Pennant",
      rows: [
        ["Drifts against the move on a slope", "Coils, with the range contracting"],
        ["A little more room for the stop", "Small by definition, so the stop is tight"],
        ["Same idea: a pause in a strong move", "Same idea: a pause in a strong move"],
      ],
    },
    question: "What is the practical consequence of a pennant being small?",
    choices: ["It is more reliable", "The stop sits close, so ordinary noise reaches it easily", "It resolves faster", "It needs less volume"],
    correct: 1,
    correctFeedback: "Correct. A tight pattern gives a tight stop, and a tight stop is hit by movement that means nothing.",
    incorrectFeedback: "Size sets the stop distance. A small pattern gives you a stop inside the market's ordinary noise.",
    takeaway: "Flags and pennants capture the same pause. The pennant's small size makes its stop fragile.",
  },
  "APP-PAT-010": {
    plain: "A rising wedge is price still rising, but with each push smaller than the last and the range narrowing.",
    detail: "It captures an advance running out of energy: progress continuing while the effort behind it shrinks. That makes it a reversal pattern that forms while price is still going up, which is why it is so often called early. Slowing is not stopping, and wedges persist far longer than they look able to.",
    example: "Pushes of 13, then 8.5, then 5 points, with pullbacks shrinking too — price higher each time, moving less each time.",
    interaction: "chart_pattern",
    flow: "judge",
    question: "You identify a rising wedge while price is still making new highs. What does the shape justify?",
    choices: ["Shorting immediately — the reversal is forming", "Tightening risk on longs, while accepting the wedge can extend for weeks", "Ignoring it until price breaks down", "Doubling the long position"],
    correct: 1,
    correctFeedback: "Correct. Fading momentum is a risk-management input. Acting on it as a reversal signal is what makes wedges expensive.",
    incorrectFeedback: "A wedge describes deceleration, and decelerating advances can continue for a long time. It manages risk; it does not time a short.",
    takeaway: "Rising wedges show an advance losing energy. Use it to manage risk, not to time a reversal.",
  },
  "APP-PAT-011": {
    plain: "A falling wedge is price still falling, but with each leg down shorter than the last and the range tightening.",
    detail: "The mirror: a decline losing force, with sellers still in control but achieving less each attempt. Same caution applies in reverse — a decline that decelerates can resume, and nothing about the narrowing puts a floor under it.",
    example: "Legs down of 13, then 8.5, then 5 points, with each bounce also shrinking — lower each time, less each time.",
    interaction: "chart_pattern",
    flow: "classify",
    question: "What do rising and falling wedges have in common?",
    choices: ["Both are continuation patterns", "Both describe a move decelerating while still going the same way", "Both require high volume", "Both resolve at the apex"],
    correct: 1,
    correctFeedback: "Correct. Deceleration inside a continuing move — which is why both are so easy to act on too early.",
    incorrectFeedback: "Both are reversal patterns that form while the move is still going. Deceleration is the shared observation.",
    takeaway: "Both wedges describe deceleration inside a continuing move. Both are habitually called early.",
  },
  "APP-PAT-012": {
    plain: "A head and shoulders is three peaks with the middle one highest, and the two troughs between them at roughly one level.",
    detail: "It captures a trend failing in stages: the third rally cannot reach the second, which is a change from what the trend had been doing. The line joining the troughs is called the neckline, and it is the most watched line in charting — which is precisely why price trades through it and comes straight back so often.",
    example: "Peaks at 99, 106 and 101; troughs at 94.20 and 93.80. The neckline sits around 94.",
    interaction: "chart_pattern",
    flow: "build",
    question: "Why does price so often break a neckline and immediately recover?",
    choices: ["The pattern was drawn wrongly", "It is the most watched line in charting, so orders cluster there and get consumed", "Necklines are unreliable by nature", "Volume is always low at necklines"],
    correct: 1,
    correctFeedback: "Correct. Visibility concentrates orders, and concentrated orders attract the move that consumes them.",
    incorrectFeedback: "The clustering is the cause. A widely watched level is a target, and reaching it is not the same as passing it.",
    takeaway: "Head and shoulders shows a trend failing in stages. The neckline is watched by everyone, so probes are routine.",
  },
  "APP-PAT-013": {
    plain: "An inverse head and shoulders is the same shape upside down: three troughs with the middle one deepest.",
    detail: "It captures a decline failing in stages — the third low is not matched, so supply is being absorbed earlier each time. Everything about its mirror applies, including that the neckline is obvious to everyone looking at the chart.",
    example: "Troughs at 101, 94 and 99; peaks at 105.80 and 106.20 between them, putting the neckline near 106.",
    interaction: "chart_pattern",
    flow: "classify",
    question: "What is the informative part of an inverse head and shoulders?",
    choices: ["The depth of the head", "That the third low is higher than the second — supply absorbed earlier", "The symmetry of the shoulders", "The neckline being flat"],
    correct: 1,
    correctFeedback: "Correct. The failure to match the previous low is the change; symmetry and neat necklines are cosmetic.",
    incorrectFeedback: "The substance is the third low not reaching the second. Symmetry is what makes it look tidy, not what makes it mean anything.",
    takeaway: "The unmatched third low is the substance. Symmetry is cosmetic.",
  },
  "APP-PAT-014": {
    plain: "A double top is two peaks at roughly the same level with a clear trough between them.",
    detail: "It captures a level that stopped price once stopping it again — the second failure suggests the supply there was not a one-off. The obvious limitation is sample size: two touches is very little evidence, and plenty of levels are cleared on the third attempt.",
    example: "Peaks at 106.40 and 105.90 separated by six weeks, with a trough at 95.20 between them.",
    interaction: "chart_pattern",
    flow: "judge",
    question: "What is the strongest objection to trading a double top?",
    choices: ["The peaks are never exactly equal", "Two touches is a very small sample of evidence about that level", "Volume is unreliable at tops", "It takes too long to form"],
    correct: 1,
    correctFeedback: "Correct. Two observations is thin evidence, and the pattern's whole claim rests on them.",
    incorrectFeedback: "The peaks need not be exact. The real weakness is that the claim rests on two data points.",
    takeaway: "A double top rests on two observations of one level. Size the trade for how thin that is.",
  },
  "APP-PAT-015": {
    plain: "A double bottom is two troughs at roughly the same level with a clear peak between them.",
    detail: "Buyers appearing at the same price twice — held once by accident and once, apparently, on purpose. The same thin-evidence caution applies, plus the reminder that support is spent by being used: a level that has held twice has less resting demand than before it was tested at all.",
    example: "Troughs at 93.60 and 94.10 separated by five weeks, with a peak at 104.80 between them.",
    interaction: "chart_pattern",
    flow: "build",
    question: "A double bottom holds twice. What does that say about the third test?",
    choices: ["It will hold too — the level is proven", "Less than it seems: each test consumes some of the demand holding the level", "The level is now resistance", "Nothing at all"],
    correct: 1,
    correctFeedback: "Correct. Holding twice is evidence the level exists, and evidence that some of it has been used.",
    incorrectFeedback: "Levels are resting orders. Two successful tests confirm the level and deplete it at the same time.",
    takeaway: "A double bottom confirms a level exists and shows some of it has already been spent.",
  },
  "APP-PAT-016": {
    plain: "A cup and handle is a rounded decline and recovery back toward an old high, then a small drift lower before the retest.",
    detail: "It captures supply from the old high being worked through gradually, with the handle showing how much of it is left. The handle is the fragile part: a deep one means the supply was never absorbed, and the cup means nothing without it.",
    example: "A high near 104, a rounded decline to 92 and recovery over four months back to 103, then a two-week drift to 100.",
    interaction: "chart_pattern",
    flow: "build",
    question: "Which part of a cup and handle carries the most information?",
    choices: ["The depth of the cup", "The handle — a shallow one suggests the old supply has been absorbed", "How long the cup took", "The roundness of the cup"],
    correct: 1,
    correctFeedback: "Correct. The handle is the test of whether anything is left at the old high. The cup is the setup for that test.",
    incorrectFeedback: "The cup describes the journey back. The handle is where you find out whether sellers are still waiting.",
    takeaway: "The handle is the informative part. A deep handle means the old supply is still there.",
  },
  "APP-PAT-017": {
    plain: "The measured move is a target taken by adding the pattern's own height to the point where it completes.",
    detail: "A rectangle seven points tall breaking upward at 104 gives a measured target of 111. It is a convention rather than a law — its only real justification is that a pattern's height reflects how much the instrument was moving, so it scales the target to the stock instead of guessing. Treat it as a first estimate to sanity-check against actual levels.",
    example: "Rectangle between 97 and 104. Height 7. Breaking at 104 gives a measured objective of 111 — which sits just past a prior high at 110.40.",
    interaction: "chart_pattern",
    flow: "calculate",
    question: "A rectangle spans 97 to 104 and breaks upward. What is the measured objective?",
    choices: ["104", "107", "111", "118"],
    correct: 2,
    correctFeedback: "Correct: height 7 added to the 104 breakout gives 111 — an estimate to check against real levels, not a promise.",
    incorrectFeedback: "Add the pattern's height to the breakout point: (104 − 97) + 104 = 111.",
    takeaway: "Measured move = pattern height added at the breakout. A convention that scales to the stock, not a law.",
  },
  "APP-PAT-018": {
    plain: "Volume usually contracts while a pattern forms and expands when it resolves.",
    detail: "The contraction says participation is draining out as the stalemate persists; the expansion says the resolution drew people back in. It is genuinely useful context and it is not confirmation — the heaviest breakout volume you will ever see also appears on breakouts that fail within days.",
    example: "Six weeks of volume falling from 46 to 17 lakh shares inside a flag, then 52 lakh on the session that resolves it.",
    interaction: "chart_pattern",
    flow: "cause",
    question: "A pattern resolves on three times normal volume and fails within a week. What does that show?",
    choices: ["The volume reading was wrong", "Heavy volume shows participation, not outcome", "It was not a real pattern", "Volume should be ignored"],
    correct: 1,
    correctFeedback: "Correct. Many people acting is not the same as many people being right.",
    incorrectFeedback: "Both the pattern and the volume were real. Participation and outcome are different things.",
    takeaway: "Volume contracts into a pattern and expands out of it. That is context, never confirmation.",
  },
  "APP-PAT-019": {
    plain: "The trigger is the price at which the pattern is considered complete — usually a close beyond its boundary.",
    detail: "Writing the trigger as a close rather than a touch matters, because touching a boundary intrabar happens constantly and closing beyond it does not. The trigger is also what makes the pattern testable: without one, you can always claim afterwards that it did or did not complete.",
    example: "Rectangle ceiling at 104. Trigger: a daily close above 104. Price touching 104.30 during the session and closing at 103.20 is not a completion.",
    interaction: "chart_pattern",
    flow: "define",
    question: "Why define the trigger as a close beyond the boundary rather than a touch?",
    choices: ["Closes are more accurate", "Touches happen constantly and closes beyond do not, so the close is the real evidence", "Brokers require it", "It gives a better entry price"],
    correct: 1,
    correctFeedback: "Correct — and it costs you a worse entry, which is the honest price of the extra evidence.",
    incorrectFeedback: "Intrabar touches are frequent and mean little. A close beyond the level is the observation worth acting on.",
    takeaway: "Define the trigger as a close beyond the boundary. It costs entry price and buys real evidence.",
  },
  "APP-PAT-020": {
    plain: "The stop belongs back inside the pattern, at the point where completion has clearly failed.",
    detail: "For a rectangle that is back below the ceiling it just cleared; for a head and shoulders, back above the right shoulder. Placing it there means the stop answers 'did the pattern fail' rather than 'is the trade uncomfortable'. Once that distance is known, the position size follows from it.",
    example: "Trigger at 104.20 with the rectangle ceiling at 104 and the last swing low at 100.40. A stop at 100.10 means ₹4.10 of risk per share.",
    interaction: "risk",
    flow: "calculate",
    question: "Trigger 104.20, stop 100.10, risk budget ₹5,000. What is the position?",
    choices: ["48 shares", "1,219 shares", "121 shares", "500 shares"],
    correct: 1,
    correctFeedback: "Correct: risk per share is ₹4.10, so ₹5,000 ÷ ₹4.10 ≈ 1,219 shares.",
    incorrectFeedback: "Risk per share is 104.20 − 100.10 = ₹4.10. Then ₹5,000 ÷ ₹4.10 ≈ 1,219.",
    takeaway: "Stop inside the pattern at the point of clear failure, then size from that distance.",
  },
  "APP-PAT-021": {
    plain: "Most patterns fail, and a failure is not evidence that you read the chart wrongly.",
    detail: "The same shape with the same volume produces continuation in one instrument and reversal in another. Because that is true, the parts of a pattern trade that you actually control are the trigger, the stop and the size — and a run of pattern failures is an expected outcome rather than a diagnosis.",
    example: "Two textbook breakouts on comparable volume. One extends for three weeks; the other reverses through the base within four sessions.",
    interaction: "chart_pattern",
    flow: "judge",
    question: "Four of your last six pattern trades failed. What is the reasonable conclusion?",
    choices: ["You are reading patterns wrongly", "Six trades is far too small a sample to conclude anything", "Patterns do not work", "You should switch to indicators"],
    correct: 1,
    correctFeedback: "Correct. At any plausible win rate, four failures in six is unremarkable. The sample is the problem, not the reading.",
    incorrectFeedback: "Six trades cannot distinguish a bad method from an ordinary run. Judge the process over a much larger batch.",
    takeaway: "Pattern failure is normal and frequent. Trigger, stop and size are the parts you control.",
  },
  "APP-PAT-022": {
    plain: "A failed pattern often moves faster in the opposite direction than a successful one moves in its own.",
    detail: "Everyone who entered on the completion is now wrong at once, and their exits push price the way it was already going. That is why the failure is sometimes the better trade — and why it is not a free one: recognising failure requires the same trigger, stop and size discipline as the original.",
    example: "A breakout above 104 runs to 106, reverses through the base and reaches 94 in eight sessions — twice the distance the successful version travelled.",
    interaction: "chart_pattern",
    flow: "judge",
    question: "Why can a failed pattern produce a faster move than a successful one?",
    choices: ["Failures attract more attention", "Everyone who entered on completion must exit, and their exits push price the same way", "Volume is higher on failures", "Stops are wider on failures"],
    correct: 1,
    correctFeedback: "Correct. Forced exits are urgent trades in the direction of the failure — the same mechanism as any trap.",
    incorrectFeedback: "The fuel is trapped positions exiting. Their exits are trades pushing the same way the failure went.",
    takeaway: "Failed patterns trap positions, and forced exits accelerate the move against them.",
  },
  "APP-PAT-023": {
    plain: "Patterns are drawn by the person looking at the chart, which means two traders can see different ones.",
    detail: "Where the neckline goes, whether that peak counts as a shoulder, whether the handle is too deep — these are judgements, not measurements. The honest response is to write the trigger and invalidation as prices before deciding what the shape is called, so the trade does not move when the label does.",
    example: "One trader draws a head and shoulders with the neckline at 94; another sees a rectangle with a floor at 93.60. Same chart, two names, nearly the same level.",
    interaction: "chart_pattern",
    flow: "judge",
    question: "Two traders name the same chart differently. What is the practical defence?",
    choices: ["Use an indicator to settle it", "Commit to the trigger and invalidation prices before naming the shape", "Take the more common pattern", "Avoid patterns entirely"],
    correct: 1,
    correctFeedback: "Correct. If the levels are fixed first, the label becomes a description rather than a decision.",
    incorrectFeedback: "The disagreement is about labels. Fixing the prices first makes the label stop mattering.",
    takeaway: "Fix the trigger and invalidation prices before naming the pattern. Then the name cannot move the trade.",
  },
  "APP-PAT-024": {
    plain: "Trading a pattern properly means the same chain as any other setup, with the shape doing only one job.",
    detail: "The shape supplies a trigger and an invalidation level, and that is its entire contribution. Trend, sector, liquidity, event risk, position size and the exit plan all still have to be answered separately — and most named patterns you find will be rejected on one of those rather than on the shape.",
    example: "A clean ascending triangle in a stock with results in six days. The shape is fine; the trade is not, and the reason has nothing to do with the pattern.",
    interaction: "chart_pattern",
    flow: "plan",
    question: "You find a textbook pattern in a stock reporting results in six days. What decides it?",
    choices: ["The quality of the pattern", "The event — a shape cannot outrank a scheduled gap inside your holding period", "The measured move target", "The volume on the breakout"],
    correct: 1,
    correctFeedback: "Correct. The pattern contributes a trigger and a level. It has no say over event risk.",
    incorrectFeedback: "The shape supplies levels only. A scheduled gap inside the holding period is decided outside the pattern entirely.",
    takeaway: "A pattern supplies a trigger and an invalidation. Everything else in the trade is decided elsewhere.",
  },
};
