import type { Authored } from "../curriculum.ts";

/** Positional stock selection (Applied) and portfolio construction (Professional).
 *  Fundamental measures appear here as evidence to be weighed, never as thresholds that
 *  produce buy decisions. Every metric lesson names what the number cannot tell you. */
export const positionalContent: Record<string, Authored> = {
  // ── Positional Trading (Applied) ────────────────────────────────────────────
  "APP-PSN-001": {
    plain: "Positional trading means holding a stock for several weeks to several months to capture a larger move.",
    detail: "It sits between swing trading and investing. You still exit on a price level rather than on a change in the business, but the level is far away, the position is small, and the thesis has to survive quarterly results rather than avoid them.",
    example: "Buy Deccan Motors at ₹640 with a stop at ₹566 — a ₹74 risk — intending to hold three to five months through two sets of results.",
    interaction: "ranking",
    flow: "define",
    question: "What does a positional trade share with a swing trade, and what does it share with investing?",
    choices: ["Nothing with either", "It exits on a price level like a swing trade, and survives results like an investment", "It exits on business news like an investment", "It uses intraday charts"],
    correct: 1,
    correctFeedback: "Correct. A price-based exit at an investment-length horizon is exactly the combination.",
    incorrectFeedback: "Positional keeps the price-based exit of a trade while accepting the event exposure of a long hold.",
    takeaway: "Positional trading exits on price like a trade, over a horizon that must survive results like an investment.",
  },
  "APP-PSN-002": {
    plain: "A positional trader will exit a good company on a price level; an investor will not.",
    detail: "That single difference changes everything about how the position is managed. The positional trader has a defined worst case and a defined size; the investor accepts drawdowns that would end a trade. Neither is wrong — mixing them mid-position is.",
    example: "Same stock, same entry. The positional trader is out at ₹566. The investor is still holding at ₹480, because the business has not changed.",
    interaction: "ranking",
    flow: "compare",
    sides: {
      left: "Positional trade",
      right: "Investment",
      rows: [
        ["Exits on a price level", "Exits on a change in the business"],
        ["Size set by the stop distance", "Size set by portfolio weight"],
        ["Weeks to months", "Months to years"],
      ],
    },
    question: "Your positional stop is hit but the business is unchanged. What is the problem with holding?",
    choices: ["Nothing — the fundamentals justify it", "The position was sized for a stop you have now abandoned", "It will underperform", "Brokerage will increase"],
    correct: 1,
    correctFeedback: "Correct. Converting to an investment mid-trade leaves you holding a position sized for a rule you dropped.",
    incorrectFeedback: "The fundamentals may well justify ownership. The size was calculated from a stop that no longer exists.",
    takeaway: "Decide which one you are running before entering. The conversion always happens at the worst moment.",
  },
  "APP-PSN-003": {
    plain: "Start with the broad market, because most of a stock's move over months comes from it.",
    detail: "In a broadly rising market most reasonable candidates work and mistakes are forgiven; in a falling one, good stocks fall too. This does not tell you what to buy — it tells you how aggressive to be and how many positions to carry.",
    example: "The index above a rising 200-day average argues for a full complement of positions. Below a falling one, the same setups deserve half the size and half the count.",
    interaction: "classification",
    flow: "cause",
    question: "What does reading the broad market decide?",
    choices: ["Which stock to buy", "How aggressive to be — position size and how many positions to carry", "The stop distance", "The sector"],
    correct: 1,
    correctFeedback: "Correct. Market context sets exposure. Stock selection is a separate question.",
    incorrectFeedback: "The market read does not select stocks. It calibrates how much total exposure the conditions justify.",
    takeaway: "The market read sets your total exposure, not your stock choice.",
  },
  "APP-PSN-004": {
    plain: "Sector strength asks whether the group a stock belongs to is being bought.",
    detail: "Stocks in the same sector move together far more than they move independently, so a strong stock in a weak sector is fighting its own group. Checking sector strength before the individual chart removes a large share of candidates quickly and for a good reason.",
    example: "Two pharma names look identical on their charts. The whole pharma group is up 14% over three months while metals are down 6% — the group is doing much of the work.",
    interaction: "ranking",
    flow: "classify",
    question: "A stock looks strong but its sector is the weakest in the market. What does that mean?",
    choices: ["It is the best stock in the sector, so buy it", "It is fighting its group, which supplies most of its movement", "Sector strength is irrelevant to individual stocks", "It will outperform when the sector recovers"],
    correct: 1,
    correctFeedback: "Correct. Being the strongest name in a weak group is a real observation and a poor tailwind.",
    incorrectFeedback: "Sector movement drives a large share of any stock's return. Strength against a weak group is swimming upstream.",
    takeaway: "Sector supplies much of a stock's movement. Strength within a weak group is a weak tailwind.",
  },
  "APP-PSN-005": {
    plain: "Over months, relative strength means the stock has outperformed the index for long enough that it is unlikely to be noise.",
    detail: "Three to six months of outperformance is the usual window. It is one of the more durable observations in markets, and it is still backward-looking: you are selecting a stock precisely because the move has already happened, and betting it continues.",
    example: "Zanskar Metals is up 28 points against the index over three months; Nilgiri Software is down 8. One has been in demand for a quarter; the other has not.",
    interaction: "ranking",
    flow: "build",
    question: "What are you betting on when you select for six-month relative strength?",
    choices: ["That the stock is undervalued", "That demand which has persisted for six months persists a while longer", "That the stock will revert to the index", "That the sector will rotate"],
    correct: 1,
    correctFeedback: "Correct. The bet is persistence, and it fails when leadership rotates.",
    incorrectFeedback: "Relative strength is a persistence bet, not a value one. It ends when leadership changes hands.",
    takeaway: "Relative strength bets that persistent demand persists. It ends when leadership rotates.",
  },
  "APP-PSN-006": {
    plain: "For a position held over months, liquidity has to be checked against your full size, not against a normal trade.",
    detail: "Positional positions are larger in rupees and held through conditions in which liquidity can disappear. A stock that trades comfortably on an ordinary day may not absorb your exit during the week you actually want to leave.",
    example: "A ₹8,00,000 position in Ganga Lifesciences at ₹286 is about 2,800 shares against 3 lakh a day — fine normally, and a real problem on a day the sector is being sold.",
    interaction: "ranking",
    flow: "judge",
    question: "Why check liquidity against stressed conditions rather than ordinary ones?",
    choices: ["Ordinary volume is unreliable", "You will want to exit precisely when everyone else does, and that is when volume concentrates on one side", "Regulators require it", "Liquidity is constant"],
    correct: 1,
    correctFeedback: "Correct. The exit you care about happens on the day liquidity is worst.",
    incorrectFeedback: "Normal-day liquidity is the wrong benchmark, because the exit that matters happens on an abnormal day.",
    takeaway: "Size against stressed liquidity. The exit that matters happens when everyone wants the same one.",
  },
  "APP-PSN-007": {
    plain: "Market capitalisation is the company's size, and it mostly tells you how much the stock moves.",
    detail: "Large caps move less, absorb size and are more heavily researched. Small caps move more and can be exceptional or ruinous. For a positional trade, size determines stop distance and therefore how much capital the position can carry — it is not a quality measure.",
    example: "Sarva Bank at ₹2,85,000 crore travels 1.6% a day. Vindhya Autoparts at ₹4,200 crore travels 3.1%. The stop on the second must be roughly twice as wide.",
    interaction: "ranking",
    flow: "classify",
    question: "What does market cap most directly affect in a positional trade?",
    choices: ["The company's quality", "The stop distance, and therefore how much capital the position can carry", "The valuation", "The sector"],
    correct: 1,
    correctFeedback: "Correct. Smaller companies travel further daily, which forces wider stops and smaller positions.",
    incorrectFeedback: "Size maps to volatility, which maps to stop distance and position size. It says nothing about quality.",
    takeaway: "Market cap is a volatility and capacity measure. It sets your stop distance, not your opinion.",
  },
  "APP-PSN-008": {
    plain: "Revenue growth tells you whether the company is selling more than it used to.",
    detail: "It is the cleanest of the growth measures because it is hardest to flatter with accounting choices. On its own it says nothing about whether the growth is profitable, or whether the price already assumes far more of it than the company is delivering.",
    example: "Satpura Infra grows revenue at 27% and carries debt-to-equity of 1.6. The growth is real; so is the borrowing that funded it.",
    interaction: "ranking",
    flow: "define",
    question: "What does strong revenue growth on its own fail to tell you?",
    choices: ["Whether sales are rising", "Whether the growth is profitable, and whether the price already assumes it", "The company's sector", "The company's size"],
    correct: 1,
    correctFeedback: "Correct. Revenue growth is necessary evidence and nowhere near sufficient on its own.",
    incorrectFeedback: "Revenue growth answers one question only. Profitability and the price paid for that growth are separate.",
    takeaway: "Revenue growth shows sales rising. It is silent about profitability and about the price already paid for it.",
  },
  "APP-PSN-009": {
    plain: "Earnings growth tells you whether profit is rising, and how it compares with revenue growth.",
    detail: "Profit growing faster than revenue means margins are improving; slower means they are compressing. Earnings are also more easily influenced by accounting choices and one-off items than revenue, so a single quarter's jump deserves less weight than a multi-year pattern.",
    example: "Sarva Bank: revenue +14%, profit +18% — margins improving. Chola Consumer: revenue +3%, profit +1% — a business that has stopped growing.",
    interaction: "ranking",
    flow: "calculate",
    question: "Revenue grows 14% and profit grows 18%. What does the comparison show?",
    choices: ["Accounting irregularity", "Margins are improving — profit is growing faster than sales", "Revenue is understated", "Nothing useful"],
    correct: 1,
    correctFeedback: "Correct. The relationship between the two growth rates is more informative than either alone.",
    incorrectFeedback: "Profit outpacing revenue means each rupee of sales is producing more profit — margin expansion.",
    takeaway: "Compare profit growth with revenue growth. The gap between them is the margin story.",
  },
  "APP-PSN-010": {
    plain: "Profitability is how much of each rupee of sales the company keeps.",
    detail: "A highly profitable business has room to absorb a bad year; a thin-margin one does not. For a positional trade this matters mainly as resilience — it changes how likely the thesis is to survive a disappointing quarter, not whether the stock goes up next month.",
    example: "Malwa Foods keeps a large share of every rupee of sales and has survived several weak quarters without the price structure breaking. Tapti Steel does not, and has not.",
    interaction: "ranking",
    flow: "cause",
    question: "How does profitability affect a positional trade?",
    choices: ["It predicts the next quarter's return", "It changes how likely the thesis is to survive a disappointing quarter", "It sets the stop distance", "It determines the sector"],
    correct: 1,
    correctFeedback: "Correct. Profitability buys resilience, which matters over a horizon that includes results announcements.",
    incorrectFeedback: "Profitability does not forecast returns. It affects how much bad news the business can absorb.",
    takeaway: "Profitability is resilience. Over a months-long hold, resilience is what survives a bad quarter.",
  },
  "APP-PSN-011": {
    plain: "Debt is what the company owes, and it decides how much bad news the business can survive.",
    detail: "Debt is not automatically bad — capital-heavy industries need it. What matters is whether the business can service it if conditions worsen. High debt turns an ordinary downturn into a solvency question, which is why heavily indebted stocks fall harder when sentiment turns.",
    example: "Indus Finserv carries debt-to-equity of 3.2 with profits falling 4%. Tapti Steel carries 1.9 with profits down 22%. Both fall harder than the market on bad news.",
    interaction: "ranking",
    flow: "cause",
    question: "Why do heavily indebted companies fall harder in a downturn?",
    choices: ["They are more widely held", "Debt turns an earnings problem into a solvency question", "They are less liquid", "Their sectors are more cyclical"],
    correct: 1,
    correctFeedback: "Correct. Leverage converts a bad year into an existential one, and prices reflect that shift.",
    incorrectFeedback: "The mechanism is the obligation. Debt must be serviced whatever earnings do, which raises the stakes of a downturn.",
    takeaway: "Debt is a resilience question, not a quality verdict. It decides what a bad year turns into.",
  },
  "APP-PSN-012": {
    plain: "Return ratios measure how much profit the company produces from the money invested in it.",
    detail: "A business earning 27% on its capital is doing something a business earning 8% is not. The measure is comparative — it means little across industries with different capital needs — and a high figure can also come from heavy borrowing rather than from a better business.",
    example: "Kaveri Tech earns 27% with almost no debt. Satpura Infra earns 12% with debt-to-equity of 1.6. The first figure is telling you more.",
    interaction: "ranking",
    flow: "judge",
    question: "Two companies report the same return on equity, one with no debt and one heavily borrowed. What differs?",
    choices: ["Nothing", "The debt-free business is producing the return from the business itself, not from leverage", "The leveraged one is better managed", "The measure is invalid for both"],
    correct: 1,
    correctFeedback: "Correct. Leverage flatters return on equity, so the ratio must be read next to the balance sheet.",
    incorrectFeedback: "Borrowing raises return on equity mechanically. The same number means different things at different debt levels.",
    takeaway: "Return ratios must be read alongside debt. Leverage inflates them without improving the business.",
  },
  "APP-PSN-013": {
    plain: "Valuation tells you how much you are paying relative to what the company earns.",
    detail: "It is context, not a rule. 'Cheap' often means the market expects deterioration, and 'rich' often means it expects growth — both can be correct. For a positional trade valuation mostly answers how much disappointment is already priced in, which affects the downside if results miss.",
    example: "Zanskar Metals looks cheap at a cyclical peak in metal prices. Kaveri Tech looks rich while compounding at 15%. Neither label is a decision.",
    interaction: "ranking",
    flow: "judge",
    question: "A stock screens as cheap. What is the most useful interpretation?",
    choices: ["It is undervalued and should be bought", "The market expects something to deteriorate — the question is whether it is right", "Valuation is meaningless", "It will revert to the sector average"],
    correct: 1,
    correctFeedback: "Correct. A low valuation is the market's opinion, and your job is to work out whether that opinion is wrong.",
    incorrectFeedback: "Cheapness is not a discount waiting to be claimed. It reflects expectations that may well be justified.",
    takeaway: "Valuation shows what is already expected. Cheap usually means expected deterioration, not free money.",
  },
  "APP-PSN-014": {
    plain: "Corporate events — results, dividends, splits, mergers, regulatory decisions — can move a stock more than months of trend.",
    detail: "Over a positional horizon you cannot avoid them, so they must be planned for. That means knowing the dates, sizing so a gap is survivable, and deciding in advance whether you reduce into a major announcement or hold through it.",
    example: "A four-month positional hold sits through two results announcements and one policy decision. All three dates were published before the position was opened.",
    interaction: "ranking",
    flow: "sequence",
    steps: [
      "List the scheduled events falling inside the intended holding period.",
      "Decide now whether you reduce into each one or hold through it.",
      "Size so that a gap several times the stop is survivable at the portfolio level.",
      "Write the decision down, so the outcome can be judged against the plan.",
    ],
    question: "How should scheduled events be handled over a positional horizon?",
    choices: ["Avoid them by closing before each one", "Plan for them in advance, since a months-long hold cannot avoid them", "Ignore them — the trend matters more", "Widen the stop before each one"],
    correct: 1,
    correctFeedback: "Correct. Avoidance is not available at this horizon, so the decision has to be made deliberately and early.",
    incorrectFeedback: "A months-long hold will sit through events. The only question is whether you decided in advance how.",
    takeaway: "Events cannot be avoided over months. Decide the response before opening the position.",
  },
  "APP-PSN-015": {
    plain: "Institutional activity is large investors building or reducing positions, and it plays out over months.",
    detail: "Large holders cannot enter or exit quickly, so their activity shows up as sustained volume and persistent relative strength rather than as a single day's spike. Reading it is inference: you observe the footprint, never the intention, and the same footprint has several explanations.",
    example: "Steadily elevated volume with the price grinding higher for weeks is consistent with accumulation — and equally consistent with index inclusion or a large seller being absorbed.",
    interaction: "ranking",
    flow: "judge",
    question: "Sustained elevated volume with a grinding uptrend. What can you conclude?",
    choices: ["Institutions are accumulating", "Something is being absorbed over time — the cause is inference, not observation", "Retail buying is driving it", "An announcement is imminent"],
    correct: 1,
    correctFeedback: "Correct. The footprint is observable; who made it and why is not.",
    incorrectFeedback: "The pattern is real and its cause is not visible. Accumulation is one explanation among several.",
    takeaway: "Institutional footprints are observable; intentions are not. Hold the inference loosely.",
  },
  "APP-PSN-016": {
    plain: "A stock near its 52-week high has almost nobody holding it at a loss.",
    detail: "That is the structural argument: there is no supply overhead from buyers waiting to escape at break-even. It is genuinely useful and it is not a reason on its own — stocks at highs also fall, and buying at a high means your stop is further from the recent lows.",
    example: "Aravali Pharma sits 0.9% below its 52-week high with nothing but clear space above it — and a nearest structural stop 8% away.",
    interaction: "ranking",
    flow: "cause",
    question: "What is the trade-off in buying near a 52-week high?",
    choices: ["There is none", "No overhead supply, but the nearest structural stop is usually further away", "Lower liquidity", "Higher brokerage"],
    correct: 1,
    correctFeedback: "Correct. Clear space above comes with a longer walk down to the last meaningful level.",
    incorrectFeedback: "The absence of overhead supply is real. So is the wider stop, because the recent structure is now further below.",
    takeaway: "Highs mean no trapped supply above and usually a wider stop below. Both are true.",
  },
  "APP-PSN-017": {
    plain: "Long-term price structure is the sequence of highs and lows on the weekly chart over a year or more.",
    detail: "At a positional horizon this is the primary chart. A stock making higher weekly highs and lows for a year is in a different situation from one that has been range-bound for three, even if both look identical on a daily chart this week.",
    example: "The daily charts of two stocks look the same. On the weekly, one has made higher lows for six quarters and the other has been in the same range since 2023.",
    interaction: "classification",
    flow: "classify",
    question: "Which chart is primary for a four-month hold?",
    choices: ["The 15-minute", "The daily", "The weekly, with the daily used for entry", "Whichever is clearest"],
    correct: 2,
    correctFeedback: "Correct. Weekly structure for the thesis, daily for timing the entry and placing the stop.",
    incorrectFeedback: "Match the chart to the horizon. A months-long hold is a weekly-chart thesis with a daily-chart entry.",
    takeaway: "Weekly structure carries the positional thesis. The daily chart only times the entry.",
  },
  "APP-PSN-018": {
    plain: "The 50-day and 200-day averages summarise the medium-term and long-term direction in two numbers.",
    detail: "Price above both, with the 50 above the 200, is the configuration most positional methods want — not because the lines have power, but because that arrangement only occurs after a sustained advance. It is a summary of structure, and a poor substitute for reading it.",
    example: "Konkan Cement is above both averages and has gone nowhere for four months. The condition is satisfied and there is no trend.",
    interaction: "ranking",
    flow: "cause",
    question: "A stock is above both averages with the 50 above the 200, and has been flat for months. What does that show?",
    choices: ["The averages are wrong", "The arrangement is a summary of past structure, not a description of current trend", "It is a strong uptrend", "The stock will break out"],
    correct: 1,
    correctFeedback: "Correct. The configuration records what happened earlier; the current chart is where you read what is happening now.",
    incorrectFeedback: "The averages are computing correctly. They summarise a past advance, which can persist in the numbers after it has stopped in the price.",
    takeaway: "Average configurations summarise past structure. Read the structure itself before relying on them.",
  },
  "APP-PSN-019": {
    plain: "A base is a long period where a stock trades sideways in a defined range.",
    detail: "It represents a stalemate between buyers and sellers, and the longer it lasts the more meaningful its resolution tends to be — a six-month range breaking is a different event from a six-day one. Bases also resolve downward, which the enthusiasm around them tends to forget.",
    example: "Kaveri Tech spends six weeks between ₹1,500 and ₹1,590. The range's height, ₹90, is what the stop distance has to respect.",
    interaction: "swing",
    flow: "define",
    question: "What does a long base give you that a short one does not?",
    choices: ["A guaranteed upward resolution", "A more meaningful resolution and clearer levels to place a stop against", "Lower volatility forever", "Higher volume"],
    correct: 1,
    correctFeedback: "Correct. Longer stalemates produce clearer levels and more significant resolutions — in either direction.",
    incorrectFeedback: "Bases resolve both ways. What length adds is significance and clarity of the levels, not a direction.",
    takeaway: "Longer bases give clearer levels and more meaningful resolutions. They still resolve both ways.",
  },
  "APP-PSN-020": {
    plain: "A breakout from a long consolidation is price leaving a range it has been stuck in for months.",
    detail: "It tries to capture the move that follows a long stalemate resolving. It makes sense when the range is well defined and the broader market agrees; it fails in the usual way, and at this horizon the failure is expensive because the position was held for weeks before it broke down.",
    example: "A four-month range between ₹296 and ₹322 resolves upward. The stop sits back inside at ₹297 — a ₹25 risk that must be sized for.",
    interaction: "swing",
    flow: "build",
    question: "Why is a failed breakout from a long base more costly at a positional horizon?",
    choices: ["The stop is tighter", "The position is larger in rupees and has usually been held for weeks before it fails", "Volume is lower", "Brokerage is higher"],
    correct: 1,
    correctFeedback: "Correct. Time and size both compound the cost of the same structural failure.",
    incorrectFeedback: "Positional positions are larger in rupees and held longer, so the same failure costs more in both money and opportunity.",
    takeaway: "Long-base breakouts fail like any other. At this horizon the failure costs more time and more money.",
  },
  "APP-PSN-021": {
    plain: "Volume expansion on a breakout means more participants took part in the move out of the range.",
    detail: "After a long quiet base, a resolution on two or three times normal volume shows that the stalemate was broken by real participation rather than drift. It remains context: heavy volume tells you many people acted, not that they were right.",
    example: "Kaveri Tech breaks out on 2.1× average volume after six weeks of declining volume. Marwar Realty breaks out on 3.4× and reverses within four sessions.",
    interaction: "swing",
    flow: "cause",
    question: "What does volume expansion on a breakout establish?",
    choices: ["The breakout will hold", "That many participants acted at those prices — not that they were right", "That institutions are buying", "That the base was valid"],
    correct: 1,
    correctFeedback: "Correct. The heaviest breakout volume in this universe belongs to the breakout that failed.",
    incorrectFeedback: "Participation is not outcome. The failing breakout here had more volume than the one that worked.",
    takeaway: "Volume shows participation in the resolution. It does not show whether the participants were right.",
  },
  "APP-PSN-022": {
    plain: "Trend continuation over months means the stock keeps making higher weekly highs and lows.",
    detail: "At this horizon the individual pullback is not the question — a 12% retracement that would end a swing trade is ordinary here. What matters is whether the weekly sequence is intact, which is why the stop belongs below a weekly swing low rather than a daily one.",
    example: "A stock falls 11% over three weeks and holds above its last weekly swing low. The daily chart looks broken; the weekly sequence is untouched.",
    interaction: "classification",
    flow: "classify",
    question: "An 11% pullback holds above the last weekly swing low. What has changed in a positional thesis?",
    choices: ["The thesis is broken", "Nothing structural — the weekly sequence is intact", "The stop should be tightened", "The position should be doubled"],
    correct: 1,
    correctFeedback: "Correct. At a positional horizon, ordinary pullbacks are supposed to be uncomfortable on the daily chart.",
    incorrectFeedback: "The weekly sequence defines the thesis. A pullback that respects it has not changed anything structural.",
    takeaway: "Judge positional continuation on the weekly sequence. Daily discomfort is expected.",
  },
  "APP-PSN-023": {
    plain: "A structurally weak stock is one where the price structure, the trend and the business are all deteriorating together.",
    detail: "The tell is agreement across independent evidence: below both averages, negative relative strength, falling revenue, falling profit, heavy debt. When every measure agrees, the cheapness is not an opportunity — it is the market pricing what all of those measures are describing.",
    example: "Tapti Steel: below both averages, −19 relative strength, revenue −3%, profit −22%, debt-to-equity 1.9, down 31% from its high. Every measure says the same thing.",
    interaction: "ranking",
    flow: "judge",
    question: "Every measure on a stock is negative and it trades at a large discount. What is the reasonable conclusion?",
    choices: ["It is deeply undervalued", "The discount is the market pricing exactly what those measures describe", "It is a contrarian opportunity", "The data must be wrong"],
    correct: 1,
    correctFeedback: "Correct. A discount with unanimous negative evidence is an explanation, not an opportunity.",
    incorrectFeedback: "When independent measures all agree, the price usually reflects them. Contrarian positions need a reason the market is wrong.",
    takeaway: "Unanimous negative evidence explains the discount. Avoid unless you can say why the market is wrong.",
  },
  "APP-PSN-024": {
    plain: "Positional sizing uses the same formula with a much wider stop, so positions are small.",
    detail: "A stop 12% away on a ₹5,00,000 account risking 1% gives a position of about ₹42,000 — far smaller than the same account's swing position. This surprises people, and it is the arithmetic working exactly as intended: the horizon widened the stop, so the size had to fall.",
    example: "Entry ₹640, stop ₹566, risk per share ₹74. ₹5,000 of risk gives 67 shares — about ₹43,000 of exposure from a ₹5,00,000 account.",
    interaction: "risk",
    flow: "calculate",
    question: "Entry ₹640, stop ₹566, risk budget ₹5,000. What is the position?",
    choices: ["67 shares", "179 shares", "500 shares", "781 shares"],
    correct: 0,
    correctFeedback: "Correct: ₹5,000 ÷ ₹74 ≈ 67 shares. The wide stop is why the position is small.",
    incorrectFeedback: "Risk per share is 640 − 566 = ₹74. Then ₹5,000 ÷ ₹74 ≈ 67 shares.",
    takeaway: "Wide positional stops produce small positions. That is the formula working, not a mistake.",
  },
  "APP-PSN-025": {
    plain: "A positional stop must sit outside months of ordinary movement, which usually means 10% or more.",
    detail: "Ordinary movement over months is much larger than over days, so a stop that would be generous for a swing trade is inside the noise here. The stop belongs at a weekly structural level — below the last significant weekly low — and the position size adapts to whatever distance that turns out to be.",
    example: "A stock with a 2% ATR moves roughly 30% across a quarter of ordinary trading. A 4% stop on a four-month hold measures noise, not error.",
    interaction: "risk",
    flow: "judge",
    question: "Why is a 4% stop unsuitable for a four-month hold?",
    choices: ["It is too wide", "Four months of ordinary movement is far larger than 4%, so the stop measures noise", "Stops must be percentages of capital", "Brokers do not accept it"],
    correct: 1,
    correctFeedback: "Correct. The stop has to clear the noise of the holding period, and months of noise is large.",
    incorrectFeedback: "Over months, ordinary movement is far larger than 4%. A stop that tight is triggered by nothing meaningful.",
    takeaway: "Positional stops clear months of noise — typically 10% or more, anchored to weekly structure.",
  },
  "APP-PSN-026": {
    plain: "Over months you will sit through gaps, and no stop protects you from them.",
    detail: "Results, policy changes and sector news all arrive while the market is closed. The wider positional stop absorbs more of a gap than a swing stop would, but a large gap still exceeds it — which is why positional sizing should assume the loss can exceed the planned risk.",
    example: "A ₹74 stop on a ₹640 stock. A disappointing results morning opens at ₹548 — a ₹92 loss, 24% more than planned.",
    interaction: "risk",
    flow: "calculate",
    question: "Entry ₹640, stop ₹566, gap open at ₹548. What is the loss per share?",
    choices: ["₹74, as planned", "₹92 — the gap opened below the stop", "₹18", "Nothing until you sell"],
    correct: 1,
    correctFeedback: "Correct: 640 − 548 = ₹92, which is 24% more than the planned risk.",
    incorrectFeedback: "The stop fills near the open, not at the stop price: 640 − 548 = ₹92.",
    takeaway: "Assume the positional loss can exceed the planned risk. Size for the gap, not for the stop.",
  },
  "APP-PSN-027": {
    plain: "Concentration is how much of your capital depends on a small number of outcomes.",
    detail: "Six positions each risking 1% look diversified until four of them are in the same sector, at which point one sector event is a 4% loss. The count of positions is not the measure — the count of independent things that would have to go wrong is.",
    example: "Six positions: two banks, two energy names, one metal, one pharma. Two of those pairs move together, so there are closer to four independent bets.",
    interaction: "ranking",
    flow: "judge",
    question: "Six positions, four of them in two sectors. How many independent bets do you have?",
    choices: ["Six", "About four — the pairs move together", "Two", "One"],
    correct: 1,
    correctFeedback: "Correct. Count independent drivers, not positions. The pairs behave as single bets under sector news.",
    incorrectFeedback: "Positions in the same sector move together, so they collapse into fewer independent exposures than the count suggests.",
    takeaway: "Count independent drivers, not positions. Sector pairs are one bet with two tickets.",
  },
  "APP-PSN-028": {
    plain: "Correlation is how much your positions tend to move together.",
    detail: "Over a months-long horizon it is the difference between a portfolio and a single large bet. Correlations also rise in falling markets — the diversification you measured in calm conditions is weakest exactly when you need it, which argues for fewer positions per sector rather than more positions overall.",
    example: "Two energy positions with 0.3 correlation in normal conditions move at 0.85 during a broad market fall. What looked like two bets becomes one.",
    interaction: "risk",
    flow: "cause",
    question: "Why is measured correlation a weak guide to how a portfolio behaves in a fall?",
    choices: ["It is hard to compute", "Correlations rise in falling markets, so diversification weakens when you need it", "It only applies to derivatives", "It changes with position size"],
    correct: 1,
    correctFeedback: "Correct — which is why sector limits are more robust than correlation estimates.",
    incorrectFeedback: "Correlations converge under stress. The number measured in calm conditions overstates the protection available in a fall.",
    takeaway: "Correlations rise when markets fall. Use sector limits rather than trusting calm-market correlations.",
  },
  "APP-PSN-029": {
    plain: "Building a positional shortlist means putting market, sector, structure, fundamentals and risk against each candidate before choosing any of them.",
    detail: "Each candidate should end with a written thesis, an invalidation level, a size and an intended holding period. Most will fail on one of those — usually the invalidation, because a stock without a level to place a stop against cannot be sized, however good it looks.",
    example: "Eighteen names reduce to six on trend and liquidity, then to three once each has to produce a weekly structural stop within an acceptable distance.",
    interaction: "ranking",
    flow: "plan",
    question: "A candidate looks strong on every measure but has no weekly structural level within 20%. What follows?",
    choices: ["Buy it with a 20% stop", "It cannot be sized sensibly, so it is not a positional candidate right now", "Use a 5% stop instead", "Buy it without a stop"],
    correct: 1,
    correctFeedback: "Correct. No usable invalidation means no defensible size — and 'wait for a better level' is a real answer.",
    incorrectFeedback: "Without a structural level the position cannot be sized. Tightening the stop arbitrarily just guarantees it is hit.",
    takeaway: "Every shortlisted candidate needs a thesis, an invalidation, a size and a horizon. Most fail on invalidation.",
  },

  // ── Portfolio Construction (Professional) ───────────────────────────────────
  "PRO-PORT-001": {
    plain: "A portfolio is not a collection of good trades — it is one exposure made of several parts.",
    detail: "Each position was sized correctly on its own, and their interaction was sized by nobody. The portfolio question is different from the trade question: not 'is this a good trade' but 'what does adding this do to what I already hold'.",
    example: "Eight individually well-sized positions, each risking 1%, six of them long the same broad market factor. Correct at the trade level, a 6% single bet at the portfolio level.",
    interaction: "risk",
    flow: "define",
    question: "What question does portfolio construction ask that trade selection does not?",
    choices: ["Is this a good trade?", "What does adding this do to what I already hold?", "What is the stop?", "What is the target?"],
    correct: 1,
    correctFeedback: "Correct. Every position can be individually correct while the combination is a single concentrated bet.",
    incorrectFeedback: "Trade quality is the trade-level question. Portfolio construction asks about the interaction with existing holdings.",
    takeaway: "Portfolio construction asks what a position adds to the book, not whether it is a good trade alone.",
  },
  "PRO-PORT-002": {
    plain: "The number of positions decides how much any single one can matter.",
    detail: "Too few and one outcome dominates the year. Too many and each is too small to move the result while the costs and the monitoring burden scale linearly. Most discretionary books settle between six and fifteen, and the number should be a rule rather than a consequence of how many ideas you happened to like.",
    example: "Twenty-five positions at 0.4% risk each means the best idea contributes as much as the twenty-fifth, and every one still costs a round trip.",
    interaction: "risk",
    flow: "judge",
    question: "What is the cost of running twenty-five positions instead of ten?",
    choices: ["Higher risk", "Each position is too small to matter, while costs and monitoring scale with the count", "Lower returns guaranteed", "Nothing"],
    correct: 1,
    correctFeedback: "Correct. Beyond a point, additional positions dilute the result without diluting the work.",
    incorrectFeedback: "More positions reduce single-name impact and multiply cost and attention. The dilution is the problem, not the risk.",
    takeaway: "Fix the position count as a rule. Too many dilutes results while multiplying cost and attention.",
  },
  "PRO-PORT-003": {
    plain: "Sizing across positions means deciding whether every position risks the same amount or whether conviction changes it.",
    detail: "Equal risk per position is simple, testable and removes a decision you are likely to make badly. Conviction-weighted sizing can be better if conviction actually predicts outcomes — which is a claim that should be measured against your own records before it is trusted.",
    example: "Ten positions at 1% each, or four at 1.5% and six at 0.66%. The second is better only if your high-conviction trades genuinely outperform in your own history.",
    interaction: "risk",
    flow: "judge",
    question: "Before adopting conviction-weighted sizing, what should you check?",
    choices: ["That your platform supports it", "Whether your high-conviction trades have actually outperformed in your own records", "That it improves the backtest", "That other traders use it"],
    correct: 1,
    correctFeedback: "Correct. Conviction weighting is a testable claim about your own judgement, and it is often not supported.",
    incorrectFeedback: "The question is empirical and personal: does your stated conviction predict outcomes in your own trade log?",
    takeaway: "Equal risk is the default. Conviction weighting is a claim about your judgement — test it before trusting it.",
  },
  "PRO-PORT-004": {
    plain: "A sector cap limits how much of the portfolio can sit in one industry.",
    detail: "It is a blunt, robust substitute for correlation estimates: instead of predicting how positions will move together, you simply refuse to hold more than a stated share in any group. Its cost is real — it forces you to reject a good idea because of what you already own.",
    example: "A cap of 25% per sector. With three banking positions at 8% each, the fourth banking idea is rejected regardless of quality.",
    interaction: "risk",
    flow: "judge",
    question: "Your best current idea would breach the sector cap. What does the cap require?",
    choices: ["Making an exception for a strong idea", "Rejecting it, or replacing a weaker position in that sector", "Raising the cap", "Halving all positions"],
    correct: 1,
    correctFeedback: "Correct. A cap that bends for strong ideas is not a cap — and every breached cap is breached for a good reason at the time.",
    incorrectFeedback: "A limit that yields to conviction provides no protection. Reject, or replace a weaker holding in the same sector.",
    takeaway: "Sector caps are blunt and robust. Their value comes entirely from not making exceptions.",
  },
  "PRO-PORT-005": {
    plain: "Correlation-aware selection asks what a candidate adds to the book, not how good it is alone.",
    detail: "A slightly weaker idea uncorrelated with everything you hold can improve the portfolio more than a stronger idea that duplicates existing exposure. This is the point where trade selection and portfolio construction genuinely conflict, and the portfolio should usually win.",
    example: "The strongest candidate is a fourth energy name. The fifth-strongest is in a sector you do not hold. The second improves the book more.",
    interaction: "ranking",
    flow: "judge",
    question: "The strongest candidate duplicates existing exposure. What usually improves the portfolio more?",
    choices: ["Taking the strongest idea regardless", "The weaker idea that adds an exposure you do not already hold", "Taking both at half size", "Neither"],
    correct: 1,
    correctFeedback: "Correct. Marginal contribution to the portfolio is a different question from standalone quality.",
    incorrectFeedback: "A fourth position in the same driver adds concentration rather than diversification, whatever its standalone merit.",
    takeaway: "Judge candidates by what they add to the book. Marginal contribution beats standalone quality.",
  },
  "PRO-PORT-006": {
    plain: "Cash is a position, and holding it is a decision rather than an absence of one.",
    detail: "Full deployment is a choice to have maximum exposure to whatever the market does next. Holding cash costs the return you might have earned and buys the ability to act when conditions improve — which is worth most in exactly the conditions where everything is falling.",
    example: "40% cash during a period of poor conditions gives up part of a recovery and provides capacity to buy when candidates finally qualify.",
    interaction: "risk",
    flow: "cause",
    question: "What does holding cash buy?",
    choices: ["A guaranteed return", "Capacity to act when conditions improve, at the cost of returns while they do not", "Lower correlation", "Reduced brokerage"],
    correct: 1,
    correctFeedback: "Correct. Cash is optionality, and like any option it costs something to hold.",
    incorrectFeedback: "Cash buys the ability to act later. That capacity has a real cost in forgone return.",
    takeaway: "Cash is a position that buys capacity. Full deployment is a decision too.",
  },
  "PRO-PORT-007": {
    plain: "Scaling in means building a position in parts rather than all at once.",
    detail: "It reduces the cost of being early and increases the cost of being right, since the full position only exists after the move has begun. It also multiplies transaction costs and complicates the stop — the average entry moves with each addition, so the invalidation must be recalculated each time.",
    example: "One-third at ₹640, one-third at ₹662 after confirmation, one-third at ₹684. Average entry ₹662, and the original ₹566 stop now represents a different risk per share.",
    interaction: "risk",
    flow: "calculate",
    question: "You scale in three times and the average entry rises. What must be recalculated?",
    choices: ["Nothing", "The risk per share, and therefore whether the total position still fits the risk budget", "The sector cap", "The target only"],
    correct: 1,
    correctFeedback: "Correct. Each addition changes the average entry, which changes the distance to the stop and the total risk.",
    incorrectFeedback: "The stop is unchanged but the average entry is not, so the risk per share and the total risk have both moved.",
    takeaway: "Every addition changes the average entry and the total risk. Recalculate at each step.",
  },
  "PRO-PORT-008": {
    plain: "Scaling out means selling a position in parts as it works.",
    detail: "It guarantees you capture some of a move and guarantees you capture less of a large one. Whether that is a good trade depends entirely on where your profits come from: it suits methods with consistent payoffs and damages methods that depend on rare large winners.",
    example: "Selling a third at 1R, a third at 2R and trailing the rest converts a 6R winner into roughly a 3R one — while making the 1R winners more reliable.",
    interaction: "expectancy",
    flow: "judge",
    question: "Your method's profits come from a few large winners. What does scaling out do?",
    choices: ["Improves consistency at no cost", "Removes much of the tail your profits actually depend on", "Reduces risk with no downside", "Increases the average winner"],
    correct: 1,
    correctFeedback: "Correct. Scaling out systematically trims exactly the outcomes a tail-driven method needs.",
    incorrectFeedback: "Scaling out reduces the size held during the largest part of a move — the part a tail-driven method relies on.",
    takeaway: "Scaling out suits consistent payoffs and damages tail-driven methods. Match it to where your profit lives.",
  },
  "PRO-PORT-009": {
    plain: "Replacing a position means selling something you hold to make room for something better.",
    detail: "It is the honest alternative to breaching a limit, and it forces a comparison most traders avoid: is the new idea better than the weakest thing I already own? Framing it that way also prevents the portfolio from growing every time you find something you like.",
    example: "At the position limit with a new candidate: sell the weakest existing holding or skip the new one. Adding a ninth position is not among the options.",
    interaction: "ranking",
    flow: "judge",
    question: "You are at your position limit and find a strong candidate. What are the honest options?",
    choices: ["Add it and exceed the limit", "Replace the weakest existing position, or skip the new idea", "Halve every position to make room", "Raise the limit"],
    correct: 1,
    correctFeedback: "Correct — and the comparison against your weakest holding is a useful discipline in itself.",
    incorrectFeedback: "Exceeding the limit or resizing everything defeats the purpose. Replacement or rejection are the real choices.",
    takeaway: "At the limit, replace or skip. Comparing against your weakest holding is the discipline.",
  },
  "PRO-PORT-010": {
    plain: "Rebalancing means returning positions to their intended weights on a schedule.",
    detail: "Winners grow into oversized positions and losers shrink into irrelevance, so a book left alone drifts toward concentration in whatever recently worked. Rebalancing corrects that and costs money, which is why the schedule and the tolerance band should both be fixed in advance.",
    example: "A position intended at 8% grows to 19% after a strong run. Rebalancing trims it; not rebalancing means one position now carries a fifth of the portfolio.",
    interaction: "risk",
    flow: "cause",
    question: "What happens to an unrebalanced portfolio over time?",
    choices: ["It stays at target weights", "It drifts toward concentration in whatever has recently worked", "It becomes more diversified", "Nothing measurable"],
    correct: 1,
    correctFeedback: "Correct. Winners grow, losers shrink, and the book quietly becomes a bet on the recent past.",
    incorrectFeedback: "Weights drift with performance. Left alone, the portfolio concentrates into whatever has just done well.",
    takeaway: "Unrebalanced books concentrate into recent winners. Fix the schedule and tolerance band in advance.",
  },
  "PRO-PORT-011": {
    plain: "Measure the portfolio's result, not the individual trades, because the portfolio is what you actually own.",
    detail: "Trade-level statistics can look excellent while the portfolio underperforms, because they ignore correlation, cash drag and concentration. The portfolio's drawdown, its worst month and its behaviour in a falling market are the numbers that describe your experience.",
    example: "A 62% win rate and a profit factor of 2.1 at the trade level, alongside a 24% portfolio drawdown caused by six positions falling together.",
    interaction: "expectancy",
    flow: "judge",
    question: "Trade statistics look strong but portfolio drawdown is severe. What does that indicate?",
    choices: ["The statistics are wrong", "Positions are correlated — individually fine, collectively one bet", "Position sizing is too small", "Nothing — trade stats are what matter"],
    correct: 1,
    correctFeedback: "Correct. Trade-level statistics are blind to how positions behave together.",
    incorrectFeedback: "Good trade statistics with a deep portfolio drawdown is the signature of correlated positions.",
    takeaway: "Trade statistics ignore correlation. Judge the book by its drawdown and its worst period.",
  },
  "PRO-PORT-012": {
    plain: "Sometimes the right action is to reduce everything rather than to adjust individual positions.",
    detail: "When the whole book is exposed to one thing that has changed — a market regime, a volatility spike, a portfolio drawdown limit — trimming the worst position does not address the problem. A broad reduction is the only action that reduces the exposure that is actually causing the loss.",
    example: "Every position falling together in a market-wide event. Cutting the weakest one leaves the same underlying exposure spread across the rest.",
    interaction: "risk",
    flow: "judge",
    question: "Every position is falling together in a market-wide event. What actually reduces the exposure?",
    choices: ["Selling the worst performer", "Reducing everything, since the exposure is shared rather than specific", "Adding an uncorrelated position", "Widening the stops"],
    correct: 1,
    correctFeedback: "Correct. When the exposure is common, only a broad reduction changes it.",
    incorrectFeedback: "Trimming one name leaves the shared exposure intact across everything else. The reduction has to be broad.",
    takeaway: "When the exposure is shared, reduce broadly. Trimming one position changes almost nothing.",
  },
};
