import type { Authored } from "../curriculum.ts";

/** Stock screening at Applied level, and the systematic version at Professional level.
 *  The through-line for both: a screen produces candidates, and every filter you add buys
 *  a smaller list by paying with the names it wrongly removed. */
export const screeningContent: Record<string, Authored> = {
  // ── Stock Screening (Applied) ───────────────────────────────────────────────
  "APP-SCR-001": {
    plain: "A stock screener is a tool that keeps only the shares matching conditions you set.",
    detail: "You write rules — price above this, volume above that, price above its 200-day average — and it returns the names that satisfy all of them. It performs no analysis; it is a very fast filter applied to a very long list.",
    example: "Set price above ₹100 and average volume above 5 lakh shares against an 18-name universe, and 13 come back. The screener did arithmetic, not judgement.",
    interaction: "screener",
    flow: "build",
    question: "What does a screener actually do?",
    choices: ["Ranks stocks by how likely they are to rise", "Returns the names that satisfy every condition you wrote", "Identifies chart patterns", "Predicts sector rotation"],
    correct: 1,
    correctFeedback: "Correct. It applies your conditions literally and returns what survives. Nothing more.",
    incorrectFeedback: "A screener has no view. It tests conditions and returns matches — the judgement is entirely yours.",
    takeaway: "A screener applies your conditions to a list. Every conclusion in the output was put there by you.",
  },
  "APP-SCR-002": {
    plain: "You screen because you cannot look at two thousand charts, and the alternative is looking at whatever you happened to hear about.",
    detail: "Without a screen your candidate list is set by news flow, tips and whatever your platform puts on its home page — a sample chosen by other people for other reasons. A screen replaces that with a sample chosen by you, for stated reasons.",
    example: "Reviewing 20 charts a day takes an hour. Reviewing 2,000 takes a hundred hours. The screen is what makes the hour meaningful instead of arbitrary.",
    interaction: "screener",
    flow: "cause",
    question: "What does screening replace?",
    choices: ["Chart analysis", "A candidate list chosen by news flow and tips rather than by you", "Risk management", "Position sizing"],
    correct: 1,
    correctFeedback: "Correct. Without a screen you still have a sample — you just did not choose it.",
    incorrectFeedback: "Screening replaces the source of your candidates, not the analysis you do on them.",
    takeaway: "The choice is not screening versus nothing. It is choosing your sample versus letting news choose it.",
  },
  "APP-SCR-003": {
    plain: "Screening finds names worth looking at; selecting a trade decides which one you actually take.",
    detail: "They are separate activities with separate standards. A screen can be mechanical and generous. Selection is slow, chart-by-chart, and should reject most of what it sees. Traders get into trouble when they let the screen's output feel like a decision.",
    example: "Six names pass the screen. Selection asks each one: where is the level, where is the stop, how much can I hold, what is coming up. Five fail one of those.",
    interaction: "screener",
    flow: "compare",
    sides: {
      left: "Screening",
      right: "Selecting",
      rows: [
        ["Mechanical, applied to thousands", "Manual, applied to a handful"],
        ["Generous — keeps anything plausible", "Strict — rejects most of what it sees"],
        ["Output: a candidate list", "Output: at most one or two trades"],
      ],
    },
    question: "Why should a screen be generous and selection strict?",
    choices: ["Screens are less accurate", "A tight screen silently discards good trades; strict selection only costs you time", "Selection is automated", "It reduces brokerage"],
    correct: 1,
    correctFeedback: "Correct. Removing a name at the screen stage means you never see it. Rejecting it at selection is deliberate.",
    incorrectFeedback: "The asymmetry is what matters: a screen's mistakes are invisible, selection's mistakes are in front of you.",
    takeaway: "Screen generously and select strictly. A screen's false rejections are the ones you never find out about.",
  },
  "APP-SCR-004": {
    plain: "A fundamental screener filters on the business — revenue, profit, debt, size, returns.",
    detail: "These measures change quarterly, so they are useful for holds measured in months rather than days. They tell you what kind of company you would own; they say nothing about whether now is a reasonable moment to buy it.",
    example: "Revenue growth above 15%, debt-to-equity below 1, return on equity above 15%. Six names qualify — including one that has been falling for four months.",
    interaction: "screener",
    flow: "define",
    question: "What can a fundamental screen not tell you?",
    choices: ["How profitable the company is", "Whether now is a reasonable moment to buy it", "How much debt it carries", "How fast revenue is growing"],
    correct: 1,
    correctFeedback: "Correct. Quarterly data cannot speak to timing, which is why fundamental screens pair with a chart.",
    incorrectFeedback: "Fundamental data describes the business. Timing is a question only price structure can answer.",
    takeaway: "Fundamental screens describe the company. They are silent about timing, and update only quarterly.",
  },
  "APP-SCR-005": {
    plain: "A technical screener filters on price and volume — trend, distance from averages, momentum, activity.",
    detail: "These update every day, which makes them useful for shorter holds. They are also entirely backward-looking: every condition describes what price has already done, so a technical screen tells you what has been happening, not what will.",
    example: "Price above both averages, RSI between 40 and 70, volume above 1.5× average. Ten names qualify — all because of movement that already occurred.",
    interaction: "screener",
    flow: "compare",
    sides: {
      left: "Fundamental screen",
      right: "Technical screen",
      rows: [
        ["Updates each quarter", "Updates each day"],
        ["Describes the business", "Describes recent price behaviour"],
        ["Suits months-long holds", "Suits days-to-weeks holds"],
      ],
    },
    question: "What do all technical screen conditions have in common?",
    choices: ["They predict the next move", "They describe movement that has already happened", "They are more accurate than fundamentals", "They work in all conditions"],
    correct: 1,
    correctFeedback: "Correct. Every technical condition is computed from history, so the output is a description of the past.",
    incorrectFeedback: "Technical conditions are computed from past price. They describe; they do not forecast.",
    takeaway: "Technical screens update daily and describe the past. Fundamental screens update quarterly and describe the business.",
  },
  "APP-SCR-006": {
    plain: "A liquidity filter keeps only the shares that trade enough for you to enter and leave.",
    detail: "The right threshold depends on your position size, not on a universal number. A useful rule of thumb is that your full position should be a small fraction of a normal day's volume — otherwise your own order is the largest thing happening in that stock.",
    example: "A ₹5,00,000 position in a ₹300 stock is about 1,700 shares. Against 2 lakh shares a day that is fine; against 20,000 a day it is a problem you created.",
    interaction: "screener",
    flow: "calculate",
    question: "What decides the right liquidity threshold?",
    choices: ["A standard industry figure", "Your position size relative to a normal day's volume", "The stock's market cap", "The exchange it is listed on"],
    correct: 1,
    correctFeedback: "Correct. Liquidity is only adequate or inadequate relative to the size you intend to trade.",
    incorrectFeedback: "There is no universal number. The threshold is set by how large your position is against daily volume.",
    takeaway: "Set the liquidity filter from your own position size. It is a relationship, not a constant.",
  },
  "APP-SCR-007": {
    plain: "A price filter removes shares priced too low for costs and tick sizes to make sense.",
    detail: "On a ₹20 share a single tick can be a meaningful percentage, and fixed costs consume more of each move. A floor of ₹50 or ₹100 is common. It also removes some genuinely good opportunities, which is the trade you are making.",
    example: "A price floor of ₹100 removes two names from an 18-stock list — including one growing revenue at 27% a year.",
    interaction: "screener",
    flow: "build",
    question: "What is the honest cost of a ₹100 price floor?",
    choices: ["Nothing — low-priced shares are always poor", "It removes some genuinely good candidates along with the unsuitable ones", "It increases brokerage", "It reduces liquidity"],
    correct: 1,
    correctFeedback: "Correct. Every filter has false rejections, and a price floor is a blunt one.",
    incorrectFeedback: "Low price is not low quality. The floor is a convenience that costs you some real candidates.",
    takeaway: "A price floor is a blunt convenience filter. It removes unsuitable names and good ones together.",
  },
  "APP-SCR-008": {
    plain: "A volume filter can mean two different things: how much trades normally, or how much traded today.",
    detail: "Average volume is a liquidity test — can I trade this at all. Today's volume against its average is an activity test — did something change. Confusing them is common: a stock can be perfectly liquid and completely quiet.",
    example: "Sarva Bank: 42 lakh shares average, today 1.4× that. Very liquid, mildly active. Zanskar Metals: 28 lakh average, today 3.1×. Liquid and something is happening.",
    interaction: "screener",
    flow: "compare",
    sides: {
      left: "Average volume",
      right: "Volume ratio (today ÷ average)",
      rows: [
        ["Can I trade this size at all?", "Did something change today?"],
        ["Changes slowly", "Changes every session"],
        ["A tradeability test", "An attention test"],
      ],
    },
    question: "A stock has high average volume but today's volume is 0.8× normal. What does that say?",
    choices: ["It is illiquid", "It is easy to trade and nothing much is happening in it today", "It is about to break out", "The data is wrong"],
    correct: 1,
    correctFeedback: "Correct. Liquidity and activity are separate questions, and this stock answers them differently.",
    incorrectFeedback: "High average volume means liquid. A below-average day means quiet. Both can be true at once.",
    takeaway: "Average volume tests tradeability; the volume ratio tests whether anything changed. Use both, separately.",
  },
  "APP-SCR-009": {
    plain: "A market-cap filter selects the size of company you want to trade.",
    detail: "Larger companies move less, absorb bigger positions and get more scrutiny. Smaller ones move more, are thinner, and can produce larger percentage moves in both directions. The filter is a decision about volatility and capacity, not about quality.",
    example: "Above ₹50,000 crore leaves five names in this universe, all of which travel under 2.1% a day. Below ₹10,000 crore leaves names travelling 3–4% a day.",
    interaction: "screener",
    flow: "classify",
    question: "What is a market-cap filter really selecting?",
    choices: ["Company quality", "The volatility and position capacity you are willing to work with", "Valuation", "Growth rate"],
    correct: 1,
    correctFeedback: "Correct. Size correlates with how much a stock moves and how much of it you can hold, not with how good it is.",
    incorrectFeedback: "Market cap is not a quality measure. It maps to typical volatility and to how large a position the stock can carry.",
    takeaway: "Market cap selects volatility and capacity. Small does not mean bad, and large does not mean safe.",
  },
  "APP-SCR-010": {
    plain: "A volatility filter selects how far the stock typically travels in a day.",
    detail: "Usually expressed as ATR divided by price. A low-volatility filter gives you calmer charts and tighter stops, and smaller moves to profit from. A high-volatility filter gives the opposite. Neither is better — but the choice must match the horizon and the position size you intend.",
    example: "ATR under 2.5% of price keeps the large caps. Marwar Realty at 4.2% is excluded — its ordinary day is twice the size of theirs.",
    interaction: "screener",
    flow: "calculate",
    question: "You filter for ATR under 2% because you want tighter stops. What did that cost?",
    choices: ["Nothing", "The larger moves that higher-volatility names produce", "Liquidity", "Access to fundamental data"],
    correct: 1,
    correctFeedback: "Correct. Tight stops and large moves come from opposite ends of the volatility range.",
    incorrectFeedback: "Lower volatility means smaller stops and smaller moves together. You cannot filter for one without the other.",
    takeaway: "A volatility filter chooses stop distance and move size at the same time. They move together.",
  },
  "APP-SCR-011": {
    plain: "A moving-average filter keeps stocks trading above or below an average of their recent price.",
    detail: "'Above the 200-day average' is the most common trend filter in existence. It is genuinely useful as a side-selector: it keeps you working with stocks the market has been favouring. It is not a signal, and a stock can be above its average and still going nowhere.",
    example: "Above both the 50-day and 200-day averages leaves ten names. One of them, Konkan Cement, has been sideways for months — it satisfies the condition and has no trend.",
    interaction: "screener",
    flow: "build",
    question: "A stock passes 'price above SMA 200'. What does that establish?",
    choices: ["It is in an uptrend", "It is above a line computed from its own past prices — often, but not always, a trend", "It is a buy", "It will keep rising"],
    correct: 1,
    correctFeedback: "Correct. Konkan Cement is above both averages and clearly ranging. The condition is satisfied; the trend is not there.",
    incorrectFeedback: "The condition tests position relative to an average. Trend is a separate reading, made from structure.",
    takeaway: "Moving-average filters choose a side. Whether a trend exists is a question for the chart.",
  },
  "APP-SCR-012": {
    plain: "An RSI filter keeps stocks whose recent momentum sits inside a range you choose.",
    detail: "A band such as 40 to 70 removes the collapsing and the exhausted at once. The cost is real: the strongest movers often read above 70, so a band that feels prudent quietly excludes the leaders you were trying to find.",
    example: "An RSI band of 40–70 removes Marwar Realty at 71 — the single strongest performer in the universe, up 37 points against the index.",
    interaction: "screener",
    flow: "judge",
    question: "Your RSI band of 40–70 excluded the strongest stock in the list. What should you conclude?",
    choices: ["The band is correct and the stock is too extended", "The filter has a known cost — it removes leaders — and you should decide deliberately whether to accept it", "RSI is useless", "Widen the band until nothing is excluded"],
    correct: 1,
    correctFeedback: "Correct. The exclusion may be right for your method. What matters is knowing it happens rather than discovering it later.",
    incorrectFeedback: "There is no automatically correct answer here. The point is that the filter has a cost you should choose knowingly.",
    takeaway: "An RSI band excludes leaders as well as laggards. Know what your filter throws away.",
  },
  "APP-SCR-013": {
    plain: "A breakout filter looks for stocks trading above a level they have not exceeded recently.",
    detail: "Usually phrased as near or above an N-day high. It finds names where price has cleared old supply. What it cannot see is whether the move was accepted or immediately rejected — which is the difference between a breakout and a poke, and it is only visible on the chart.",
    example: "A 60-day-high filter returns four names. Two closed strongly above the level; two spiked through it intraday and closed back inside.",
    interaction: "screener",
    flow: "cause",
    question: "Why does a breakout filter need a chart check afterwards?",
    choices: ["The data is often wrong", "The filter cannot distinguish a move that held from one that was immediately rejected", "Breakouts are always false", "Charts are more accurate"],
    correct: 1,
    correctFeedback: "Correct. Acceptance beyond the level is the informative part, and no single-number filter captures it.",
    incorrectFeedback: "The filter sees a price relationship. Whether the market accepted that price is a structural question.",
    takeaway: "Breakout filters find the crossing. Whether price stayed there is only visible on the chart.",
  },
  "APP-SCR-014": {
    plain: "A relative-strength filter keeps stocks that have outperformed the index over a chosen period.",
    detail: "It answers 'strong compared with what' and is one of the more durable screening ideas. It also arrives late by construction: a stock shows relative strength because it already outperformed, so you are always selecting after the outperformance began.",
    example: "Outperforming the index over three months keeps nine names and removes Nilgiri Software, which is up but trailing the market by 8 points.",
    interaction: "screener",
    flow: "build",
    question: "What is built into every relative-strength filter?",
    choices: ["A prediction of future outperformance", "Lateness — the outperformance has already happened by the time it qualifies", "A liquidity check", "A valuation check"],
    correct: 1,
    correctFeedback: "Correct. That lateness is the bet: that strength persists a while longer.",
    incorrectFeedback: "Relative strength is measured from past returns, so qualifying always happens after the move started.",
    takeaway: "Relative strength selects after the fact, and bets that strength persists. That is the whole trade.",
  },
  "APP-SCR-015": {
    plain: "A 52-week-high screen finds stocks near their highest price of the year; a 52-week-low screen finds the opposite.",
    detail: "Near a high there is nobody holding at a loss waiting to sell into a recovery, which is the structural argument for these screens. Near a low the opposite is true, and the same argument explains why 'cheap because it fell' lists are dangerous.",
    example: "Within 10% of the 52-week high returns nine names. Below 25% from the high returns four — three with falling profits.",
    interaction: "screener",
    flow: "cause",
    question: "What is the structural argument for buying near 52-week highs rather than lows?",
    choices: ["Highs always continue", "There is little trapped supply overhead — nobody is waiting to sell at break-even", "Low prices are riskier", "Highs have more volume"],
    correct: 1,
    correctFeedback: "Correct. It is an argument about who is holding what, not about momentum magic.",
    incorrectFeedback: "The argument is about overhead supply: near a high, few holders are waiting to escape at their entry price.",
    takeaway: "Near highs there is little trapped supply. Near lows there is a lot — and often a reason for it.",
  },
  "APP-SCR-016": {
    plain: "An unusual-volume screen finds stocks trading far more than they normally do.",
    detail: "It reliably tells you that attention arrived. It does not tell you why, from whom, or in which direction — the same spike appears on good news, bad news, index changes and large block trades. It is a flag to investigate, and it is only that.",
    example: "Three times normal volume returns four names: one on results, one on a sector move, one on an index change, and one with no visible reason at all.",
    interaction: "screener",
    flow: "judge",
    question: "A stock appears on an unusual-volume screen. What is the correct next step?",
    choices: ["Buy it — volume confirms the move", "Find out what happened, since the screen flags attention without saying why", "Ignore it — volume is noise", "Short it"],
    correct: 1,
    correctFeedback: "Correct. Unusual volume is the beginning of an investigation, never the end of one.",
    incorrectFeedback: "The spike is real information and incomplete information. Establishing the cause is the next step, not the trade.",
    takeaway: "Unusual volume flags attention. The cause and the direction are separate questions you must answer.",
  },
  "APP-SCR-017": {
    plain: "Combining filters means every extra condition removes more names, and they compound quickly.",
    detail: "Each filter looks reasonable alone. Applied together, five moderate conditions can take a universe from eighteen names to two, and the two survivors are not necessarily the best — they are the ones that happened to satisfy all five simultaneously.",
    example: "Eighteen names → price and liquidity leave 13 → both averages leave 10 → RSI band leaves 9 → volume expansion leaves 6 → large cap leaves 2.",
    interaction: "screener",
    flow: "build",
    question: "Five sensible filters reduce eighteen names to two. What are those two?",
    choices: ["The two best trades", "The two that happened to satisfy all five conditions at once", "The two most liquid", "A representative sample"],
    correct: 1,
    correctFeedback: "Correct. Surviving a conjunction of conditions is not the same as being the best candidate.",
    incorrectFeedback: "Combined filters select for simultaneous satisfaction, which is a different thing from quality.",
    takeaway: "Filters compound fast. The survivors satisfied every condition at once — that is all you know about them.",
  },
  "APP-SCR-018": {
    plain: "Over-filtering is adding so many conditions that almost nothing survives, and what does survives by luck.",
    detail: "The tell is a screen that returns zero or one name most days. At that point you are not sampling the market, you are describing one specific stock. Each added condition should be paid for with a stated reason, and three or four well-chosen ones usually beat ten.",
    example: "Adding a sector condition to five existing filters takes the list from two names to one. That one name is now the output of a screen with no room for error anywhere.",
    interaction: "screener",
    flow: "judge",
    question: "Your screen returns zero or one name on most days. What is the likeliest problem?",
    choices: ["The market has no opportunities", "You have over-filtered, and the survivors are chosen by coincidence", "The data feed is broken", "You need one more filter"],
    correct: 1,
    correctFeedback: "Correct. A screen this tight is describing a stock rather than sampling a market.",
    incorrectFeedback: "Consistently empty screens usually indicate conditions stacked too tightly, not an empty market.",
    takeaway: "If a screen almost always returns nothing, it is over-filtered. Three good conditions beat ten anxious ones.",
  },
  "APP-SCR-019": {
    plain: "A false positive is a stock that passes every filter and is still a bad trade.",
    detail: "They are guaranteed, because filters see numbers and not situations. A stock can be liquid, trending, above its averages and expanding on volume — and be one day from results, or extended after a 30% run, or the only strong name in a collapsing sector.",
    example: "Aravali Pharma passes every technical filter cleanly. It is also at a 52-week high with RSI 68 after a 22-point run — you would be buying the end of a move.",
    interaction: "screener",
    flow: "judge",
    question: "Why are false positives unavoidable in screening?",
    choices: ["Screener software is unreliable", "Filters test numbers, and the reasons to reject a trade are usually situational", "Filters are too loose", "Data is delayed"],
    correct: 1,
    correctFeedback: "Correct. Extension, event risk and sector context do not reduce to a threshold.",
    incorrectFeedback: "The limitation is structural, not technical. Numbers cannot capture situation, and situation is what rejects most candidates.",
    takeaway: "Every screen produces false positives, because situations do not reduce to thresholds.",
  },
  "APP-SCR-020": {
    plain: "The whole chain runs screener → candidates → analysis → setup → risk → trade, and skipping the middle is where money is lost.",
    detail: "Each stage answers a different question: which names are worth reading, what the chart says, whether there is a defined setup, where the invalidation is, and how large the position can be. A screen that jumps straight to a buy has skipped every question that determines the outcome.",
    example: "Six candidates. Analysis rejects three on extension, setup rejects two with no clean level, risk sizes the last one at 180 shares. One trade from six names.",
    interaction: "screener",
    flow: "plan",
    question: "You have run the screen and have six candidates. What is the next stage?",
    choices: ["Buy the strongest one", "Analysis — read each chart and reject the ones without a usable setup", "Size the position", "Set a target"],
    correct: 1,
    correctFeedback: "Correct. Analysis comes next, and it is the stage that removes most of the list.",
    incorrectFeedback: "Sizing and targets come after there is a setup. Analysis is what turns a candidate into one.",
    takeaway: "Screener → candidates → analysis → setup → risk → trade. The middle stages are the ones doing the work.",
  },

  // ── Systematic Screening (Professional) ─────────────────────────────────────
  "PRO-SSCR-001": {
    plain: "Systematic screening replaces yes-or-no filters with a score that ranks every name in the universe.",
    detail: "A filter throws away a stock that misses a threshold by one basis point. A ranking keeps it and places it 47th. That difference matters because thresholds are arbitrary, and a ranked list degrades gracefully where a filtered list falls off a cliff.",
    example: "A filter of 'RSI above 50' rejects a stock at 49.8. A ranking on the same measure places it just behind the one at 50.2, which is what the data actually says.",
    interaction: "ranking",
    flow: "compare",
    sides: {
      left: "Filtering",
      right: "Ranking",
      rows: [
        ["Binary — in or out", "Ordered — every name has a place"],
        ["A threshold decides everything", "A threshold decides nothing"],
        ["Output size varies wildly", "Output size is whatever you choose"],
      ],
    },
    question: "What is the main structural advantage of ranking over filtering?",
    choices: ["Rankings are more accurate", "Arbitrary thresholds stop determining whether a name survives", "Rankings run faster", "Rankings need less data"],
    correct: 1,
    correctFeedback: "Correct — and you get a list of predictable length rather than one that empties in some conditions.",
    incorrectFeedback: "Ranking is not more accurate. It removes the cliff edge that a threshold creates.",
    takeaway: "Ranking removes the threshold cliff and gives a list of predictable length.",
  },
  "PRO-SSCR-002": {
    plain: "The universe is the fixed list of instruments your screen is allowed to consider.",
    detail: "Defining it explicitly matters more than it sounds. An undefined universe silently changes as listings, liquidity and index membership change, so results from different periods stop being comparable — and a universe defined by today's membership imports hindsight into every historical test.",
    example: "'Top 500 by market cap, reviewed quarterly, using the membership in force at each date' is a universe. 'Whatever my platform shows' is not.",
    interaction: "ranking",
    flow: "define",
    question: "Why must the universe be defined as it stood at each historical date?",
    choices: ["To reduce computation", "Otherwise today's membership imports knowledge that did not exist then", "To satisfy regulators", "Because membership rarely changes"],
    correct: 1,
    correctFeedback: "Correct. This is survivorship bias entering through the universe definition rather than through the price data.",
    incorrectFeedback: "Using today's list applies knowledge of which companies would survive and be included — information unavailable at the time.",
    takeaway: "Define the universe explicitly and point-in-time. An undefined universe imports hindsight quietly.",
  },
  "PRO-SSCR-003": {
    plain: "Ranking means sorting the whole universe on a measure and taking the top slice.",
    detail: "You choose how many names you want rather than discovering it. The slice size is a real decision: too narrow and results depend on a handful of names, too wide and you dilute whatever signal the ranking carried.",
    example: "Rank 500 names by three-month relative strength and take the top 10%. Fifty names, every month, regardless of what the market is doing.",
    interaction: "ranking",
    flow: "build",
    question: "What does taking a fixed top slice guarantee that a filter does not?",
    choices: ["Better performance", "A list of known length in every market condition", "Lower turnover", "Higher liquidity"],
    correct: 1,
    correctFeedback: "Correct. In a bad month a filter can return nothing; a ranking still returns your top 10%, of a weaker universe.",
    incorrectFeedback: "The guarantee is list length, not quality. In a weak market the top decile is simply the best of a weak set.",
    takeaway: "A ranked slice always returns a list. Remember that in a weak market it returns the best of a weak set.",
  },
  "PRO-SSCR-004": {
    plain: "A composite score combines several measures into one number so the ranking can use all of them.",
    detail: "The hard part is weighting. Each measure has a different scale and a different distribution, so they must be standardised before being combined, and the weights themselves are parameters that can be overfitted just like any other.",
    example: "Standardise relative strength, volume expansion and distance from the 52-week high, then combine them 50/25/25. Those three weights are three fitted parameters.",
    interaction: "ranking",
    flow: "calculate",
    question: "What is the hidden risk in a composite score?",
    choices: ["It is slow to compute", "The weights are parameters, and can be overfitted like any other", "It requires fundamental data", "It cannot be ranked"],
    correct: 1,
    correctFeedback: "Correct. Tuning weights until the backtest improves is overfitting wearing a respectable name.",
    incorrectFeedback: "Weights are fitted numbers. Every one you tune adds a degree of freedom to fit the past with.",
    takeaway: "Standardise before combining, and treat the weights as parameters that can be overfitted.",
  },
  "PRO-SSCR-005": {
    plain: "Rebalancing is re-running the screen on a schedule and updating the shortlist.",
    detail: "The schedule is a genuine trade-off, not an implementation detail. Daily rebalancing reacts fast and generates heavy turnover and cost; monthly is cheap and can leave you holding names the screen would no longer choose. Fix the schedule in advance so it is not decided by how the positions feel.",
    example: "Weekly rebalancing on a fifty-name list replaces perhaps eight names a week. Daily rebalancing on the same rules replaces far more, at a cost that must be earned back.",
    interaction: "ranking",
    flow: "judge",
    question: "What does a faster rebalance schedule buy and cost?",
    choices: ["Better accuracy at no cost", "Faster reaction, paid for in turnover and transaction costs", "Lower risk", "A shorter list"],
    correct: 1,
    correctFeedback: "Correct — and the extra cost has to be earned back by the improved reaction before it is worth anything.",
    incorrectFeedback: "Speed is not free. Every rebalance is trades, and trades are costs deducted from the strategy's edge.",
    takeaway: "Fix the rebalance schedule in advance. Speed is paid for in turnover.",
  },
  "PRO-SSCR-006": {
    plain: "A regime-conditional screen changes which measures it ranks on depending on market conditions.",
    detail: "Momentum ranking works in trends and bleeds in chop; mean-reversion ranking does the reverse. Switching between them sounds obviously right and is genuinely difficult, because regime detection lags — you tend to switch just as the regime you detected is ending.",
    example: "Rank on relative strength while the index is above its 200-day average, and on distance-from-mean below it. The switch fires weeks after each change actually began.",
    interaction: "ranking",
    flow: "judge",
    question: "What is the main difficulty with regime-conditional screening?",
    choices: ["It requires too much data", "Regime detection lags, so the switch often fires as the detected regime ends", "The measures are hard to compute", "It increases the universe size"],
    correct: 1,
    correctFeedback: "Correct. The idea is sound and the timing is the problem, which is why gradual weighting beats hard switching.",
    incorrectFeedback: "The concept is straightforward. The difficulty is that any detector arrives late by construction.",
    takeaway: "Regime-conditional screens are right in principle and late in practice. Blend weights rather than flipping them.",
  },
  "PRO-SSCR-007": {
    plain: "Turnover is how much of your shortlist changes each period, and it is a direct cost.",
    detail: "A screen replacing 40% of its names each month is trading roughly five times a year per slot, each with brokerage, taxes and slippage. That total is subtracted from the edge before you see a rupee, and it is the first thing to compute when a promising screen looks marginal.",
    example: "Fifty positions, 40% monthly turnover, ₹85 average cost per round trip: about ₹20,400 a year in costs on the shortlist alone.",
    interaction: "ranking",
    flow: "calculate",
    question: "Fifty positions with 40% monthly turnover. Roughly how many round trips per year?",
    choices: ["50", "120", "240", "600"],
    correct: 2,
    correctFeedback: "Correct: 20 replacements a month × 12 = 240 round trips, each carrying its full cost.",
    incorrectFeedback: "40% of 50 is 20 names replaced per month, and there are 12 months: 240 round trips.",
    takeaway: "Compute turnover in round trips per year and cost it before judging any screen.",
  },
  "PRO-SSCR-008": {
    plain: "Screen decay is a screen that used to work slowly ceasing to work.",
    detail: "It happens when enough participants run the same conditions that the edge is priced in before you can act on it, or when the market behaviour the screen relied on changes. The symptom is gradual: a screen does not usually break, it fades over quarters while still looking plausible.",
    example: "A screen delivering 4 points of annual outperformance for five years delivers 1 point for the next two. Nothing looks broken at any single point.",
    interaction: "overfitting",
    flow: "cause",
    question: "Why is screen decay hard to detect?",
    choices: ["The data becomes unavailable", "It happens gradually, so no single period looks like a failure", "Screens fail suddenly", "It only affects fundamental screens"],
    correct: 1,
    correctFeedback: "Correct. Gradual decay is indistinguishable from a bad patch until quite a lot of time has passed.",
    incorrectFeedback: "Decay is slow. That is exactly what makes it hard to separate from ordinary variation.",
    takeaway: "Screens fade rather than break. Track performance against expectation over quarters, not months.",
  },
  "PRO-SSCR-009": {
    plain: "Testing a screen honestly means measuring it against what you would otherwise have held.",
    detail: "A screen returning 14% in a year the market returned 16% did harm, not good. The benchmark is the universe itself, and the test must include costs, turnover and realistic fills — all three of which are usually the difference between an attractive screen and a break-even one.",
    example: "Screen returns 14%, the universe returns 16%. Before costs the screen underperformed; after turnover it underperformed considerably.",
    interaction: "expectancy",
    flow: "judge",
    question: "Your screen returned 14% while its universe returned 16%. What did the screen add?",
    choices: ["14 percentage points of return", "Negative value — you would have done better holding the universe", "Nothing measurable", "It depends on the number of names"],
    correct: 1,
    correctFeedback: "Correct, and that is before subtracting the turnover cost the screen incurred to underperform.",
    incorrectFeedback: "The comparison is against the universe. Returning less than the thing you filtered means the filtering hurt.",
    takeaway: "Benchmark a screen against its own universe, after costs. Absolute return says nothing.",
  },
  "PRO-SSCR-010": {
    plain: "Capacity is the largest amount of money a screen's output can actually absorb.",
    detail: "A screen that favours small, thin names may test beautifully and be untradeable at size, because your own orders would move the prices the test assumed. Capacity should be estimated from the shortlist's typical daily turnover, and it caps the strategy regardless of how good the signal is.",
    example: "A shortlist averaging 3 lakh shares a day at ₹200 turns over about ₹6 crore. A fund taking 5% of daily volume can deploy ₹30 lakh per name — no more.",
    interaction: "ranking",
    flow: "calculate",
    question: "A screen tests well but favours thin small-caps. What is the practical constraint?",
    choices: ["Data availability", "Capacity — your own orders would move the prices the test assumed", "Rebalancing frequency", "Sector concentration"],
    correct: 1,
    correctFeedback: "Correct. Beyond a certain size the strategy stops being the strategy that was tested.",
    incorrectFeedback: "The binding constraint is capacity. The backtest assumed fills that your own size would prevent.",
    takeaway: "Estimate capacity from the shortlist's turnover. Beyond it, the tested strategy no longer exists.",
  },
  "PRO-SSCR-011": {
    plain: "Screening data has to be correct at the moment of each historical decision, not merely correct today.",
    detail: "Restated results, prices adjusted after corporate actions, market caps recomputed on today's share count — each quietly puts future knowledge into a past decision. These errors do not crash anything; they produce a plausible, better-looking result, which is why they survive review.",
    example: "Ranking on profit figures that were later restated means the screen was choosing on numbers nobody had at the time.",
    interaction: "overfitting",
    flow: "cause",
    question: "Why are point-in-time data errors especially dangerous in screening?",
    choices: ["They cause the screen to fail", "They improve results plausibly, so nothing looks wrong", "They only affect small caps", "They are easy to spot"],
    correct: 1,
    correctFeedback: "Correct. An error that made results worse would be found immediately. One that flatters them is not.",
    incorrectFeedback: "These errors do not break anything. They quietly improve the result, which is what makes them hard to catch.",
    takeaway: "Use point-in-time data. Errors that flatter results are the ones that survive review.",
  },
  "PRO-SSCR-012": {
    plain: "A screen should be retired on criteria written before it was deployed.",
    detail: "Deciding during a drawdown means deciding when you most want to believe the screen still works. Useful criteria pair a performance condition with a mechanism condition: underperformance beyond a stated margin over a stated number of periods, or evidence that the behaviour the screen relied on has changed.",
    example: "Retire if the screen underperforms its universe by more than 3 points over eight consecutive quarters, or if the ranking measure stops separating the top and bottom deciles at all.",
    interaction: "ranking",
    flow: "sequence",
    steps: [
      "Write the retirement criteria at deployment, alongside the expected performance.",
      "Track performance against the universe, after costs, every period.",
      "Check separately whether the ranking measure still separates the deciles at all.",
      "When a criterion triggers, retire the screen — then investigate, not before.",
    ],
    question: "Why write retirement criteria before deployment?",
    choices: ["Regulators require documentation", "Because during a drawdown you will most want to believe the screen still works", "It speeds up the decision", "It improves the backtest"],
    correct: 1,
    correctFeedback: "Correct. The criteria exist to overrule the version of you that is looking at losses.",
    incorrectFeedback: "The reason is behavioural. Criteria written in advance survive the drawdown; judgement made during one does not.",
    takeaway: "Write retirement criteria at deployment, and pair a performance test with a mechanism test.",
  },
};
