import type { Authored } from "../curriculum.ts";

/** Swing trading. Every setup lesson here follows the same discipline: what the technique is
 *  trying to capture, why it might work, when it tends to make sense, when it fails, and how
 *  risk is controlled. None of these are presented as signals that pay. */
export const swingContent: Record<string, Authored> = {
  "APP-SWG-001": {
    plain: "Swing trading means buying a stock and holding it for a few days to a few weeks to capture one move.",
    detail: "You are not trying to catch every wiggle, and you are not betting on the business. You are betting that one identifiable move — a breakout, a pullback ending, a bounce from a level — continues far enough to pay for the risk you took.",
    example: "Buy Kaveri Tech at ₹1,595 as it clears a six-week ceiling, stop at ₹1,540, hold nine sessions, exit at ₹1,720.",
    interaction: "swing",
    flow: "define",
    question: "What is a swing trader trying to capture?",
    choices: ["Every move in the stock", "One identifiable move, over days to weeks", "The company's long-term growth", "Intraday volatility"],
    correct: 1,
    correctFeedback: "Correct. One move, with a defined start, a defined failure point and a plan for the end.",
    incorrectFeedback: "Swing trading targets a single move over days to weeks — not every fluctuation and not the business.",
    takeaway: "Swing trading captures one move over days to weeks, with the failure point defined before entry.",
  },
  "APP-SWG-002": {
    plain: "Most swing trades last between two days and four weeks.",
    detail: "The range is not a rule but a consequence: a move that resolves in hours was an intraday trade, and one that takes three months has become a positional hold with a stop sized for days. If your trades routinely run much longer, the stop and size no longer match the horizon.",
    example: "Twenty swing trades: eleven closed within a week, six within three weeks, three ran longer and were the ones where the original stop had stopped making sense.",
    interaction: "horizon",
    flow: "classify",
    question: "A swing trade you sized for two weeks has now run eleven weeks. What is the problem?",
    choices: ["Nothing — it is profitable", "The stop and position size were set for a horizon that no longer applies", "It should be closed immediately", "The stock changed sector"],
    correct: 1,
    correctFeedback: "Correct. The trade has drifted into a different horizon while carrying the wrong risk settings.",
    incorrectFeedback: "Profit does not fix the mismatch. A two-week stop on an eleven-week hold is now inside ordinary noise.",
    takeaway: "Two days to four weeks. When a trade outgrows its horizon, its stop and size no longer fit it.",
  },
  "APP-SWG-003": {
    plain: "Swing trading holds overnight; intraday trading does not.",
    detail: "That single difference produces all the others. Holding overnight means gap risk and no need to watch the screen; closing daily means a deadline, more trades, more costs and constant attention. Neither is safer — they fail in different ways.",
    example: "The same idea in Deccan Motors: intraday it must work by 3:20 p.m.; as a swing trade it has three weeks and one results announcement to survive.",
    interaction: "horizon",
    flow: "compare",
    sides: {
      left: "Swing",
      right: "Intraday",
      rows: [
        ["Holds overnight — gap risk", "Flat by the close — no gap risk"],
        ["Daily chart, checked once a day", "5-minute chart, watched continuously"],
        ["Few trades, low total cost", "Many trades, costs compound"],
      ],
    },
    question: "What does an intraday trader avoid, and what do they pay for it?",
    choices: ["Gap risk, paid for with a deadline and higher total costs", "Slippage, paid for with wider stops", "Brokerage, paid for with attention", "Nothing — intraday is strictly safer"],
    correct: 0,
    correctFeedback: "Correct. No overnight exposure, in exchange for a hard deadline and many more round trips.",
    incorrectFeedback: "Closing daily removes gap risk. The cost is the deadline and the cost of trading far more often.",
    takeaway: "Swing accepts gaps to avoid the deadline. Intraday accepts the deadline to avoid gaps.",
  },
  "APP-SWG-004": {
    plain: "A swing trader exits on a price level; an investor exits on a change in the business.",
    detail: "This matters most when a swing trade goes wrong. The temptation is to say 'it is a good company, I will hold' — which silently converts a two-week trade with a ₹55 stop into an investment with no stop at all, at a size chosen for the trade.",
    example: "A swing position stops out at ₹1,540. Deciding to hold instead because the company is sound leaves you with a position sized for a ₹55 risk and no exit rule.",
    interaction: "swing",
    flow: "judge",
    question: "Your swing trade hits its stop but you believe in the company. What is the real problem with holding?",
    choices: ["Nothing, if the company is good", "You now hold an investment sized for a trade, with no exit rule", "You will pay more brokerage", "The stock will keep falling"],
    correct: 1,
    correctFeedback: "Correct. The conversion is silent, and it leaves the position with a size that no longer matches its risk.",
    incorrectFeedback: "The company may well be good. The problem is that the position size and the missing stop belong to a trade you have abandoned.",
    takeaway: "Do not convert a stopped-out trade into an investment. The size was chosen for the trade.",
  },
  "APP-SWG-005": {
    plain: "A trending stock is one making higher highs and higher lows on the daily chart.",
    detail: "Swing setups work best when the broader move is already going your way, because the setup only needs to catch a continuation rather than start something new. Checking this first removes most candidates before you look at any pattern.",
    example: "Deccan Motors: swing highs at 566, 612, 640 with each pullback stopping higher. Chola Consumer: highs at 534, 519, 508 with each bounce failing lower.",
    interaction: "swing",
    flow: "classify",
    question: "Why check the trend before looking for a setup?",
    choices: ["Trends are more predictable", "A continuation setup only works if there is something to continue", "Trending stocks have more volume", "It saves time"],
    correct: 1,
    correctFeedback: "Correct. Most swing setups are continuation setups, and they need an established move behind them.",
    incorrectFeedback: "The reason is structural: a continuation pattern with nothing to continue is describing noise.",
    takeaway: "Establish the trend first. Continuation setups need an existing move to continue.",
  },
  "APP-SWG-006": {
    plain: "A breakout setup buys a stock as it clears a level that has been capping it.",
    detail: "It tries to capture the move that follows once overhead supply is gone. It makes sense after a genuine consolidation on contracting volume, and it fails often — obvious levels attract clustered orders, and a push through one can be exactly what consumes them. The stop belongs back inside the base.",
    example: "Kaveri Tech ranges 1,500–1,590 for six weeks, then closes at 1,608 on the heaviest volume of the base. Stop at 1,540, back inside the range.",
    interaction: "swing",
    flow: "build",
    question: "Where does the stop belong on a breakout entry, and why?",
    choices: ["A fixed 2% below entry", "Back inside the base — if price returns there, the breakout did not hold", "At the previous day's low", "At the 200-day average"],
    correct: 1,
    correctFeedback: "Correct. The base is what defines the idea, so re-entering it is what invalidates the idea.",
    incorrectFeedback: "The stop marks where the thesis dies. For a breakout, that is price accepting itself back inside the range.",
    takeaway: "Breakouts try to capture the move after supply clears. They fail often, so the stop sits back inside the base.",
  },
  "APP-SWG-007": {
    plain: "A pullback setup buys after a trending stock has given back part of its last push.",
    detail: "It tries to capture the resumption of an existing trend at a better price than chasing. It makes sense while the pullback stays above the prior swing low; it fails when the pullback turns out to be the start of a reversal, which looks identical until it does not.",
    example: "Deccan Motors pushes 566 → 640, pulls back to 618, holds above the prior swing low of 612. Entry on the first close back above the previous day's high.",
    interaction: "swing",
    flow: "build",
    question: "What separates a pullback from the start of a reversal, in advance?",
    choices: ["Volume", "Nothing reliable in advance — which is why the prior swing low is the stop", "RSI", "The number of down days"],
    correct: 1,
    correctFeedback: "Correct. They look the same until one of them breaks the prior low. That is precisely why the stop goes there.",
    incorrectFeedback: "No indicator separates them in advance. The prior swing low is what tells you afterwards, and that is where the stop belongs.",
    takeaway: "Pullbacks buy a better price for a lower probability the trend is intact. The prior swing low settles it.",
  },
  "APP-SWG-008": {
    plain: "A support or resistance setup trades a bounce from an area where price has previously turned.",
    detail: "It tries to capture the reaction at a level where buyers or sellers have shown up before. It makes sense when the level has been tested a small number of times and the broader trend agrees. It fails as levels get tested repeatedly — each test consumes the orders that made the level work.",
    example: "A stock has bounced from ₹296 twice. The third test is a weaker proposition than the first, because much of the buying interest that created the level has already been used.",
    interaction: "swing",
    flow: "cause",
    question: "Why does a level tend to get weaker with each test?",
    choices: ["Levels expire after a fixed time", "Each test consumes some of the orders that made the level hold", "More traders notice it", "Volatility falls"],
    correct: 1,
    correctFeedback: "Correct. The level is made of resting interest, and testing it spends that interest.",
    incorrectFeedback: "Levels are made of orders. Every test uses some of them up, so repeated tests leave less behind.",
    takeaway: "Levels are resting orders, and testing spends them. The third test is weaker than the first.",
  },
  "APP-SWG-009": {
    plain: "Relative strength picks the stock that has been outperforming the market and its own sector.",
    detail: "In swing selection its job is narrow: among several stocks with a similar setup, prefer the one already leading. It is a tie-breaker, not a setup, and the leaders are also the most extended — the same strength that qualifies a stock is what makes its stop distance uncomfortable.",
    example: "Three auto stocks show the same pullback. One is up 19 points against the index over three months, one is flat, one is down 9. The setup is identical; the company behind it is not equally in demand.",
    interaction: "ranking",
    flow: "judge",
    question: "Three stocks show the same setup. How should relative strength be used?",
    choices: ["As the setup itself", "As a tie-breaker between candidates that already qualified", "To decide the stop", "To decide the target"],
    correct: 1,
    correctFeedback: "Correct. Relative strength ranks candidates. It does not create one.",
    incorrectFeedback: "Relative strength is a selection input among qualified setups, not a reason to enter on its own.",
    takeaway: "Use relative strength to choose between setups, never as the setup.",
  },
  "APP-SWG-010": {
    plain: "Volume confirmation means checking whether the move that triggered your setup had participation behind it.",
    detail: "A breakout on twice the usual volume involved many participants at those prices; the same breakout on 60% of normal volume involved few. That is genuine context and it is not confirmation of anything — plenty of real moves start quietly, and plenty of heavy-volume moves fail.",
    example: "Kaveri Tech clears its ceiling on 2.1× average volume. Marwar Realty clears its own on 3.4× — and reverses through the base within four sessions.",
    interaction: "swing",
    flow: "cause",
    question: "A breakout occurs on 3.4× normal volume and then fails. What does that show?",
    choices: ["The volume data was wrong", "Heavy volume shows participation, not outcome", "Volume should be ignored", "The breakout was not a real breakout"],
    correct: 1,
    correctFeedback: "Correct. Participation is real information about who was involved, and it does not determine what happens next.",
    incorrectFeedback: "The breakout and the volume were both real. Volume describes participation; it does not confirm the outcome.",
    takeaway: "Volume shows how many took part. Treat it as context, never as confirmation.",
  },
  "APP-SWG-011": {
    plain: "A moving-average setup uses an average as the reference level a pullback is measured against.",
    detail: "In a steady uptrend, pullbacks often stall near a rising average, which gives a visible, repeatable place to look for the resumption. It works because it approximates where recent buyers sit — and it stops working the moment the trend does, at which point price cuts straight through.",
    example: "Deccan Motors pulls back to its rising 20-day average three times over two months and resumes each time. The fourth pullback goes straight through and keeps going.",
    interaction: "swing",
    flow: "build",
    question: "Why does a moving-average pullback setup stop working?",
    choices: ["The average becomes inaccurate", "It relies on the trend, and when the trend ends price cuts straight through", "Too many traders use it", "The lookback needs adjusting"],
    correct: 1,
    correctFeedback: "Correct. The setup is a trend setup wearing an indicator's clothes. No trend, no setup.",
    incorrectFeedback: "The average keeps computing correctly. What ends is the trend that made pullbacks to it hold.",
    takeaway: "Moving-average pullbacks are trend setups. They end exactly when the trend does.",
  },
  "APP-SWG-012": {
    plain: "In swing trading RSI is used to describe how stretched a move is, not to generate entries.",
    detail: "An RSI of 78 after a fast run tells you the stock has moved a long way quickly, which is useful for deciding whether to wait for a pullback rather than chase. Used as a signal — sell above 70, buy below 30 — it fights the trend the rest of your method is trying to follow.",
    example: "A stock you want to buy on a pullback reads RSI 76 after four strong sessions. That is a reason to wait for a better entry, not a reason to short it.",
    interaction: "rsi",
    flow: "judge",
    question: "Your swing candidate reads RSI 76. What is the useful reading?",
    choices: ["Short it — it is overbought", "It has moved far and fast, so waiting for a pullback may give a better entry", "Buy immediately — strength confirms", "Ignore the reading"],
    correct: 1,
    correctFeedback: "Correct. RSI informs the entry timing here. It is not a reason to trade against the trend you identified.",
    incorrectFeedback: "A high RSI in an uptrend describes speed, not a top. Use it to time the entry, not to reverse the direction.",
    takeaway: "In swing trading RSI describes extension and informs entry timing. It is not a signal generator.",
  },
  "APP-SWG-013": {
    plain: "Multi-timeframe swing analysis uses the weekly chart for context and the daily chart for the setup.",
    detail: "The weekly answers whether the broader move supports the trade and where the significant levels are; the daily provides the entry and the stop. Reading below the daily rarely helps a multi-week trade — it produces detail smaller than the decision.",
    example: "Weekly shows a two-year base with resistance at 1,600. Daily shows the six-week consolidation under it. The weekly tells you the level matters; the daily tells you when.",
    interaction: "swing",
    flow: "sequence",
    steps: [
      "Weekly chart: is the broader structure supportive, and where are the significant levels?",
      "Daily chart: is there a defined setup near one of those levels?",
      "Daily chart: where does the setup fail, and how far is that from the entry?",
      "Size the position from that distance — then stop looking at finer timeframes.",
    ],
    question: "What job does the weekly chart do in a swing trade?",
    choices: ["Timing the entry", "Establishing the broader structure and the levels that matter", "Setting the stop", "Calculating position size"],
    correct: 1,
    correctFeedback: "Correct. Context above, execution below. The weekly never times anything.",
    incorrectFeedback: "Entry, stop and size all come from the daily. The weekly supplies context and significant levels.",
    takeaway: "Weekly for context and levels, daily for setup, entry and stop. Nothing finer.",
  },
  "APP-SWG-014": {
    plain: "A gap is when a stock opens at a very different price from where it closed the previous day.",
    detail: "Gaps are the defining risk of holding overnight, because they happen while you cannot act. A gap can open below your stop, and the stop will then fill at the opening price rather than the level you chose — which is why the loss on a gapped trade can be several times what you planned.",
    example: "Stop at ₹1,540 on a ₹55 risk. Results disappoint and the stock opens at ₹1,462. The stop fills near ₹1,462, and the loss is ₹133 — 2.4 times the plan.",
    interaction: "swing",
    flow: "calculate",
    question: "Entry ₹1,595, stop ₹1,540, and the stock gaps open at ₹1,462. What is the loss per share?",
    choices: ["₹55, as planned", "About ₹133 — the stop had no chance to work", "Nothing until you sell", "₹78"],
    correct: 1,
    correctFeedback: "Correct: 1,595 − 1,462 ≈ ₹133. A stop is an instruction, and instructions need an open market.",
    incorrectFeedback: "The stop cannot execute at a price the market never traded. The fill is near the open: 1,595 − 1,462.",
    takeaway: "A gap can open past your stop. Plan the loss as a multiple of the intended risk, not equal to it.",
  },
  "APP-SWG-015": {
    plain: "ATR tells you how far the stock normally travels in a day, which is what a swing stop must clear.",
    detail: "A stop inside one ATR will be hit by an ordinary session. Swing stops are commonly placed at 1.5 to 3 ATR from entry, or at the structural level if that is further. The multiple is a choice; the principle is that the stop must sit outside routine movement.",
    example: "Kaveri Tech's ATR is ₹31. A ₹20 stop is inside one ordinary day. A ₹55 stop at the base low is about 1.8 ATR — outside the noise and anchored to structure.",
    interaction: "swing",
    flow: "calculate",
    question: "ATR is ₹31 and you place a ₹20 stop. What have you built?",
    choices: ["A tight, efficient stop", "A stop that an ordinary day's movement will trigger", "A stop that is too wide", "A stop unrelated to volatility"],
    correct: 1,
    correctFeedback: "Correct. Inside one ATR, the stop measures noise rather than being wrong.",
    incorrectFeedback: "If the stock routinely travels ₹31 in a day, a ₹20 stop is inside its ordinary range.",
    takeaway: "Swing stops sit outside one ATR, and preferably at a structural level further out.",
  },
  "APP-SWG-016": {
    plain: "Entry selection is choosing between a better price and better evidence — you cannot have both.",
    detail: "Buying the breakout gives the most confirmation and the worst price. Buying the pullback gives a better price and less certainty the move continues. Buying in anticipation gives the best price and the weakest evidence. All three are defensible; picking one and applying it consistently is what makes the results readable.",
    example: "The same setup offers entry at 1,608 on the breakout, 1,575 on the retest, or 1,545 in anticipation. The stop stays at 1,540 in all three, so the risk per share is ₹68, ₹35 or ₹5.",
    interaction: "swing",
    flow: "judge",
    question: "The stop stays at 1,540 while the entry varies. What changes across the three entries?",
    choices: ["Only the price paid", "The risk per share, and therefore the position size and the reward-to-risk", "Nothing important", "The probability of success only"],
    correct: 1,
    correctFeedback: "Correct. Entry choice changes risk per share, which changes size, which changes everything downstream.",
    incorrectFeedback: "Entry price sets the distance to the stop, which sets the risk per share and therefore the size.",
    takeaway: "Entry choice trades price against evidence and rewrites the risk per share. Choose one style and keep it.",
  },
  "APP-SWG-017": {
    plain: "The stop goes where the setup stops being true, not where the loss feels acceptable.",
    detail: "For a breakout that is back inside the base; for a pullback it is below the prior swing low; for a level trade it is beyond the level. Once that price is identified, the position size adapts to it. Setting the stop from comfort and the size from habit is the most common way a plan fails.",
    example: "Base low at 1,540 and a comfortable loss of ₹2,000. Risk per share is ₹55, so the size is 36 shares — not a round 100 with the stop moved up to make it fit.",
    interaction: "risk",
    flow: "calculate",
    question: "Structural stop is ₹55 away and your risk budget is ₹2,000. What is the position?",
    choices: ["100 shares", "36 shares", "55 shares", "Move the stop closer to allow 100 shares"],
    correct: 1,
    correctFeedback: "Correct: 2,000 ÷ 55 ≈ 36 shares. The structure sets the stop; the stop sets the size.",
    incorrectFeedback: "Divide the budget by the structural risk per share: 2,000 ÷ 55. Never move the stop to reach a preferred size.",
    takeaway: "Structure sets the stop, the stop sets the size. Reversing that order breaks the risk model.",
  },
  "APP-SWG-018": {
    plain: "A trailing stop moves up as the trade works, converting an open profit into a floor.",
    detail: "It tries to stay in a move that keeps going while ensuring a winner does not become a loser. The cost is real: any trail tight enough to protect much profit will also remove you from ordinary pullbacks. Trailing below successive swing lows respects structure better than a fixed percentage does.",
    example: "Entry 1,595, stop 1,540. Price reaches 1,690 and a new swing low forms at 1,640, so the stop moves there. The trade can no longer lose, and a normal pullback will now end it.",
    interaction: "swing",
    flow: "judge",
    question: "What does every trailing stop trade away?",
    choices: ["Nothing — it is strictly better", "Staying power: a tight trail exits on ordinary pullbacks", "The ability to take profit", "Position size"],
    correct: 1,
    correctFeedback: "Correct. Protection and staying power are the two ends of the same dial.",
    incorrectFeedback: "Trailing stops protect profit by exiting earlier. The tighter the protection, the more ordinary pullbacks end the trade.",
    takeaway: "Trailing stops trade staying power for protection. Trail below structure, not by a fixed percentage.",
  },
  "APP-SWG-019": {
    plain: "A profit target is a price where you have decided in advance to take the money.",
    detail: "Targets make the trade's economics explicit before entry and remove the decision from the moment you are least able to make it. They also cap the occasional large winner, which matters more if your method depends on those. Placing a target below an obvious level is usually better than above it.",
    example: "Entry 1,595, stop 1,540, target 1,705 just under the prior high at 1,712 — because that is where sellers appeared last time.",
    interaction: "swing",
    flow: "judge",
    question: "Why place a target just below a prior high rather than just above it?",
    choices: ["To pay less brokerage", "Because sellers appeared at that level before, so getting filled below it is more likely", "Because targets must be round numbers", "To increase reward-to-risk"],
    correct: 1,
    correctFeedback: "Correct. Queue ahead of the level rather than behind everyone waiting at it.",
    incorrectFeedback: "The prior high is where supply showed up. A target just under it is more likely to fill than one just beyond it.",
    takeaway: "Set targets in advance and place them ahead of known supply, not behind it.",
  },
  "APP-SWG-020": {
    plain: "Reward-to-risk compares the distance to your target with the distance to your stop.",
    detail: "It is computed before entry from the two levels the chart gave you, not chosen to look attractive. If the honest numbers produce 1:1, the answer is to skip the trade or find a better entry — not to move the stop closer until the ratio improves.",
    example: "Entry 1,595, stop 1,540, target 1,705: risk ₹55, reward ₹110, so 1:2. Moving the stop to 1,570 to reach 1:3.7 does not improve the trade; it just guarantees the stop is hit.",
    interaction: "expectancy",
    flow: "calculate",
    question: "Honest levels give you 1:1. What is the disciplined response?",
    choices: ["Move the stop closer to improve the ratio", "Skip the trade or wait for a better entry", "Widen the target", "Take it anyway with double size"],
    correct: 1,
    correctFeedback: "Correct. The ratio is an output of the chart. Improving it by moving levels is fiction.",
    incorrectFeedback: "Adjusting levels to reach a nicer ratio changes the arithmetic, not the trade. Skip or wait for a better entry.",
    takeaway: "Reward-to-risk is computed from the chart's levels. If the honest number is poor, the trade is poor.",
  },
  "APP-SWG-021": {
    plain: "Swing position sizing divides your rupee risk by the distance from entry to stop.",
    detail: "The one addition swing trading makes is that the stop can be jumped by an overnight gap, so the realistic worst case is larger than the calculation suggests. Many swing traders size on the arithmetic and then reduce, treating the planned loss as a floor rather than a maximum.",
    example: "₹5,00,000 capital, 1% risk is ₹5,000. Risk per share ₹55 gives 90 shares. Allowing for gap risk, 70 shares is the position that survives a bad open.",
    interaction: "risk",
    flow: "calculate",
    question: "Capital ₹5,00,000, risk 1%, entry ₹640, stop ₹612. What is the arithmetic size?",
    choices: ["78 shares", "178 shares", "500 shares", "1,000 shares"],
    correct: 1,
    correctFeedback: "Correct: ₹5,000 ÷ ₹28 ≈ 178 shares — before any reduction for gap risk.",
    incorrectFeedback: "Risk per share is 640 − 612 = ₹28. Then ₹5,000 ÷ ₹28 ≈ 178.",
    takeaway: "Size = risk budget ÷ (entry − stop), then reduce for the gap the stop cannot protect against.",
  },
  "APP-SWG-022": {
    plain: "Overnight risk is everything that can happen to your position while you cannot trade it.",
    detail: "It is managed by size rather than by stops, because stops do not operate when the market is shut. Practically that means smaller positions than the arithmetic allows, fewer positions exposed to the same event, and avoiding a full-sized position into a known announcement.",
    example: "Three swing positions in different auto stocks look diversified. A single policy announcement on vehicle taxation gaps all three the same morning.",
    interaction: "risk",
    flow: "judge",
    question: "How is overnight risk actually managed?",
    choices: ["With a tighter stop", "With smaller size and fewer positions exposed to the same event", "By checking the news before the close", "It cannot be managed"],
    correct: 1,
    correctFeedback: "Correct. Stops are unavailable overnight, so size and correlation are the only controls that still work.",
    incorrectFeedback: "A stop cannot execute while the market is shut. Only size and exposure to shared events remain under your control.",
    takeaway: "Stops do not work overnight. Manage gap risk with size and by not stacking positions behind one event.",
  },
  "APP-SWG-023": {
    plain: "Results announcements and scheduled events can move a stock further in one open than a normal month.",
    detail: "The dates are usually known in advance, which makes this the most avoidable risk in swing trading. Choices are to close before the event, reduce the position, or hold deliberately — but 'I did not check' is not among them, and it accounts for a large share of outsized swing losses.",
    example: "A well-behaved swing position with a ₹28 stop moves ₹95 on a results morning. The date was published three weeks earlier.",
    interaction: "swing",
    flow: "sequence",
    steps: [
      "Before entering, check the next scheduled event date for that stock.",
      "If it falls inside the intended holding period, decide now: close before, reduce, or hold knowingly.",
      "If holding through, size for a gap several times the stop, not for the stop.",
      "Record the decision, so a bad outcome can be judged against the plan rather than the result.",
    ],
    question: "What makes event risk different from other swing risks?",
    choices: ["It is larger", "The date is usually known in advance, so it is avoidable", "It only affects small caps", "Stops work normally through it"],
    correct: 1,
    correctFeedback: "Correct. Knowing the date converts it from a risk into a decision.",
    incorrectFeedback: "The distinguishing feature is that it is scheduled. That makes it a choice rather than an accident.",
    takeaway: "Check the event calendar before entering. A known date makes the exposure a decision, not bad luck.",
  },
  "APP-SWG-024": {
    plain: "A failed breakout is when price clears the level, then falls back through it and keeps going.",
    detail: "It is the characteristic swing loss, and it is worse than an ordinary one because everyone who bought the breakout must now exit into the same fall. It is why the stop goes inside the base and why the position is sized for the stop being reached, not for the setup working.",
    example: "Marwar Realty clears its base at 322 on 3.4× volume, runs for four sessions, then reverses through the base and keeps falling for two weeks.",
    interaction: "swing",
    flow: "plan",
    question: "The same breakout shape produced a clean trend in one stock and a failure in another. What does that establish?",
    choices: ["One of the setups was flawed and should have been spotted", "The setup does not determine the outcome — which is why the stop and size are the parts you control", "Breakouts should be avoided", "Volume should have been the deciding factor"],
    correct: 1,
    correctFeedback: "Correct. The failing breakout had heavier volume than the one that worked. Outcome is not readable from the setup.",
    incorrectFeedback: "Both setups were legitimate and the volume favoured the one that failed. The difference was outcome, not quality.",
    takeaway: "Identical setups produce opposite outcomes. Stop placement and size are the parts you actually control.",
  },
  "APP-SWG-025": {
    plain: "Some setups should be skipped even when they look correct.",
    detail: "The usual reasons: results within the holding period, no structural level close enough to make the stop affordable, a stock too thin for the size, the broader market falling hard, or the move already extended so far that the stop must sit uncomfortably wide. Skipping is a decision, and it is most of the job.",
    example: "A clean pullback setup where the nearest structural stop is 9% away. At 1% risk the position becomes so small that costs consume the result. Skip.",
    interaction: "swing",
    flow: "judge",
    question: "A textbook setup has its nearest structural stop 9% away. Why skip it?",
    choices: ["The setup is invalid", "The position becomes so small that costs eat the outcome", "Wide stops are always wrong", "9% exceeds the risk limit"],
    correct: 1,
    correctFeedback: "Correct. The risk limit is respected — the position just becomes too small to be worth taking.",
    incorrectFeedback: "The setup and the risk rule are both fine. The problem is that the resulting position is too small to matter.",
    takeaway: "Skip setups where the honest stop makes the position pointless, where events intrude, or where you cannot exit.",
  },
  "APP-SWG-026": {
    plain: "Planning a swing trade means answering six questions in order, before any money is committed.",
    detail: "Trend, setup, entry, stop, size, invalidation — and none of them can be skipped or reordered. Working the chart in this sequence is what turns 'this looks good' into a position with a known worst case, and it is the same sequence whether the trade works or not.",
    example: "Kaveri Tech: uptrend, six-week base, entry on acceptance above 1,595, stop 1,540, ₹5,000 risk gives 90 shares, invalidated by a close back inside the base.",
    interaction: "swing",
    flow: "plan",
    question: "You have identified the trend and the setup. What must be settled before the entry price?",
    choices: ["The target", "Where the setup fails — because that distance decides everything downstream", "The sector", "The holding period"],
    correct: 1,
    correctFeedback: "Correct. Invalidation comes before size, and size comes before you can judge whether the entry is worth taking.",
    incorrectFeedback: "The failure point must be known first: it sets the risk per share, which sets the size and the reward-to-risk.",
    takeaway: "Trend → setup → entry → stop → size → invalidation. Same order every time, whatever the outcome.",
  },
};
