import type { Authored } from "../curriculum.ts";

/** The find-a-trade workflow. This module exists to connect what the rest of the course
 *  teaches separately: regime, sector, screening, chart reading, invalidation, sizing and
 *  the exit plan are one chain, and the chain is the skill. */
export const workflowContent: Record<string, Authored> = {
  "APP-FIND-001": {
    plain: "Finding a trade is a sequence of steps, not a moment when a chart looks right.",
    detail: "The steps run market → sector → screen → shortlist → chart → setup → entry → invalidation → stop → size → exit plan. Each one either narrows the field or supplies a number the next step needs. Skipping any of them does not save time; it removes a number that something later depended on.",
    example: "A trader who starts at 'this chart looks good' has no market read to size against, no sector context, and no reason to believe this chart is the best available.",
    interaction: "workflow",
    flow: "build",
    question: "What is lost by starting at the chart instead of the market?",
    choices: ["Nothing, if the chart is good", "The context that sets exposure and the comparison that shows whether this is the best candidate", "Time", "Access to fundamental data"],
    correct: 1,
    correctFeedback: "Correct. The earlier steps supply exposure calibration and a comparison set. A single chart supplies neither.",
    incorrectFeedback: "Starting at the chart removes the market read that sets exposure, and the shortlist that would show whether this candidate is the best one.",
    takeaway: "The workflow is a chain. Each step narrows the field or supplies a number the next step needs.",
  },
  "APP-FIND-002": {
    plain: "Step one is reading the broad market, because it decides how aggressive to be.",
    detail: "You are answering two things: is the market trending or ranging, and is volatility expanding or contracting. Those two answers set how many positions you carry and at what size. They do not select anything — this step never produces a stock.",
    example: "Index above a rising 200-day average with contracting volatility: full position count at normal size. Below a falling one with volatility expanding: half the count at half the size.",
    interaction: "workflow",
    flow: "sequence",
    steps: [
      "Is the broad index trending or ranging?",
      "Is volatility expanding or contracting?",
      "From those two, set the position count and the size multiplier for the week.",
      "Write it down before looking at any individual stock.",
    ],
    question: "What is the output of step one?",
    choices: ["A shortlist of stocks", "A position count and a size multiplier", "An entry price", "A sector"],
    correct: 1,
    correctFeedback: "Correct. Step one calibrates exposure. It never names a stock.",
    incorrectFeedback: "The market read produces exposure settings, not candidates. Candidates come three steps later.",
    takeaway: "Step one outputs how much, not what. Write the exposure settings before looking at any stock.",
  },
  "APP-FIND-003": {
    plain: "Step two is finding which sectors are being bought, because most of a stock's move comes from its group.",
    detail: "Rank the sectors by relative performance over your holding period and work from the top two or three. This step narrows the universe by roughly 80% for a reason you can state, rather than by whichever names you happened to remember.",
    example: "Ranking sectors over three months puts metals and pharma at the top and chemicals and FMCG at the bottom. The screen now runs on the top groups.",
    interaction: "workflow",
    flow: "sequence",
    steps: [
      "Rank sectors by performance over roughly your intended holding period.",
      "Take the top two or three and note the bottom two.",
      "Restrict the candidate universe to the leading groups.",
      "Record which groups you excluded, so a missed move can be attributed later.",
    ],
    question: "Why restrict the universe by sector before screening?",
    choices: ["It makes the screen run faster", "Most of a stock's movement comes from its group, so the group is a large part of the odds", "Sectors are easier to analyse", "Screeners require a sector input"],
    correct: 1,
    correctFeedback: "Correct. Narrowing by sector is narrowing by the largest single driver of a stock's return.",
    incorrectFeedback: "The sector supplies a large share of a stock's movement. Restricting to leading groups improves the odds before any chart is read.",
    takeaway: "Step two narrows the universe by the largest driver of a stock's return: its sector.",
  },
  "APP-FIND-004": {
    plain: "Step three runs the screen on the reduced universe to produce candidates.",
    detail: "Liquidity first, then trend conditions, then whatever else your method requires. Keep the conditions few and generous — the screen's job is to hand you a readable list, and every extra condition is a chance to silently discard something you would have wanted.",
    example: "Within the leading sectors: average volume above 5 lakh, price above both averages, price within 15% of the 52-week high. Six names come back.",
    interaction: "screener",
    flow: "build",
    question: "How many conditions should the screen typically carry?",
    choices: ["As many as possible", "Few and generous — the screen produces a readable list, not a decision", "Exactly ten", "One"],
    correct: 1,
    correctFeedback: "Correct. The strict filtering happens at the chart, where you can see what you are rejecting.",
    incorrectFeedback: "A tight screen discards candidates invisibly. Keep it generous and reject deliberately at the chart stage.",
    takeaway: "Screen generously. Reject at the chart, where the rejections are visible to you.",
  },
  "APP-FIND-005": {
    plain: "Step four turns the screen output into a shortlist by removing names for stated reasons.",
    detail: "Results within the holding period, no structural level to place a stop against, extension after a large run, insufficient liquidity for your size. Each removal is written down, which is what makes the process reviewable later — you can find out whether your rejection reasons were any good.",
    example: "Six names: one has results in nine days, two are extended after 20% runs, one is too thin for the intended size. Two survive.",
    interaction: "ranking",
    flow: "build",
    question: "Why record the reason each candidate was rejected?",
    choices: ["For tax purposes", "So you can later check whether your rejection reasons were any good", "To satisfy the broker", "It is not necessary"],
    correct: 1,
    correctFeedback: "Correct. Unrecorded rejections cannot be reviewed, so a bad rejection habit never gets found.",
    incorrectFeedback: "Rejections are decisions. Without a record you can only review the trades you took, which is half the process.",
    takeaway: "Write down why each candidate was rejected. Otherwise half your decisions are never reviewed.",
  },
  "APP-FIND-006": {
    plain: "Step five reads the chart of each survivor at the timeframe that matches your horizon.",
    detail: "You are looking for structure: the trend on the timeframe above, the recent swings, and the levels that would matter. This is where most of the remaining candidates die, and that is the stage doing its job.",
    example: "Two survivors. One shows a clean six-week base under a defined ceiling; the other is in an uptrend with no recent structure anywhere near the current price.",
    interaction: "swing",
    flow: "classify",
    question: "A candidate is in a clear uptrend with no recent structure near the current price. What does that mean?",
    choices: ["It is the best candidate", "There is no nearby level to define failure, so it cannot be sized sensibly", "It should be bought at market", "The trend makes structure unnecessary"],
    correct: 1,
    correctFeedback: "Correct. A trend without a nearby invalidation level is not yet a trade.",
    incorrectFeedback: "A strong trend with no nearby structure gives you nothing to place a stop against, and therefore no defensible size.",
    takeaway: "The chart stage looks for structure, not for enthusiasm. No nearby level means no sizeable trade.",
  },
  "APP-FIND-007": {
    plain: "Step six names the setup — breakout, pullback, or a reaction at a level — in one sentence.",
    detail: "Naming it forces the thesis to become specific enough to be wrong. 'It looks strong' cannot be invalidated; 'it is basing under ₹1,590 and I expect acceptance above it' can be, and the invalidation is already implied by the sentence.",
    example: "'Six-week base between 1,500 and 1,590; I expect acceptance above 1,590 to lead to continuation of the prior trend.'",
    interaction: "workflow",
    flow: "define",
    question: "What does naming the setup in a sentence accomplish?",
    choices: ["It sounds professional", "It makes the thesis specific enough to be proven wrong", "It selects the timeframe", "It calculates the size"],
    correct: 1,
    correctFeedback: "Correct — and a sentence that can be wrong usually contains its own invalidation level.",
    incorrectFeedback: "The purpose is falsifiability. A thesis you cannot state precisely cannot be invalidated precisely either.",
    takeaway: "Name the setup in one sentence. If it cannot be wrong, it is not yet a setup.",
  },
  "APP-FIND-008": {
    plain: "Step seven chooses the entry: the breakout, the retest, or in anticipation.",
    detail: "Each buys a different mix of price and evidence, and each produces a different distance to the same stop — which changes the position size and the reward-to-risk. There is no correct choice; there is a choice you make consistently so that your results can be attributed to it.",
    example: "Stop fixed at 1,540. Entry at 1,608 gives ₹68 of risk; at 1,575 on the retest, ₹35; in anticipation at 1,552, ₹12.",
    interaction: "swing",
    flow: "judge",
    question: "Why does entry choice matter beyond the price paid?",
    choices: ["It does not", "It changes the distance to the stop, and therefore the size and the reward-to-risk", "It changes the target", "It changes the sector"],
    correct: 1,
    correctFeedback: "Correct. The stop is fixed by structure, so the entry alone determines the risk per share.",
    incorrectFeedback: "With the stop fixed by structure, moving the entry moves the risk per share — and everything computed from it.",
    takeaway: "Entry choice sets the risk per share. Pick one style and apply it consistently.",
  },
  "APP-FIND-009": {
    plain: "Step eight states the price at which the idea is wrong, before anything else is calculated.",
    detail: "It comes from the setup sentence: if the thesis is acceptance above a level, the invalidation is acceptance back below it. This has to be settled before the stop and the size, because both are derived from it — and settling it afterwards means fitting the thesis to the position you wanted.",
    example: "Thesis: acceptance above 1,590. Invalidation: a daily close back below 1,540, inside the base. That is the idea failing, not the price being uncomfortable.",
    interaction: "workflow",
    flow: "define",
    question: "Why must invalidation be settled before the stop and the size?",
    choices: ["It is faster", "Both are derived from it, so deciding it later means fitting the thesis to the position", "Regulators require it", "It improves the reward-to-risk"],
    correct: 1,
    correctFeedback: "Correct. Invalidation is the input; the stop and the size are outputs.",
    incorrectFeedback: "Stop and size are computed from the invalidation. Choosing it last means it was chosen to justify a size you already wanted.",
    takeaway: "State invalidation first. The stop and the size are derived from it, not the other way round.",
  },
  "APP-FIND-010": {
    plain: "Step nine places the stop just beyond the invalidation level, not at it.",
    detail: "Placing it exactly at the level puts it where everyone else's is, which is where price is most likely to trade briefly before reversing. A small buffer past the level costs a little more per share and avoids being removed by the exact move the level was supposed to survive.",
    example: "Invalidation at a close below 1,540. Stop at 1,532 rather than 1,540, accepting ₹8 more risk per share to sit behind the cluster.",
    interaction: "risk",
    flow: "judge",
    question: "Why place the stop slightly beyond the invalidation level rather than exactly on it?",
    choices: ["To reduce risk", "Because orders cluster at the level, and price often trades briefly through it", "Brokers require a buffer", "It improves the reward-to-risk"],
    correct: 1,
    correctFeedback: "Correct — and the buffer costs a little more per share, which the size calculation then accounts for.",
    incorrectFeedback: "A buffer increases risk per share. It buys avoidance of the brief overshoot that clustered stops attract.",
    takeaway: "Place the stop beyond the level, not on it. The buffer costs risk per share and avoids the cluster.",
  },
  "APP-FIND-011": {
    plain: "Step ten divides your risk budget by the distance from entry to stop.",
    detail: "This is the step that turns everything above it into a number of shares. It also applies the exposure setting from step one — in poor conditions the same calculation runs against a halved budget, which is how the market read actually reaches the position.",
    example: "₹5,00,000 capital, 1% base risk, halved to 0.5% by the market read: ₹2,500. Entry 1,608, stop 1,532, risk ₹76. Size: 32 shares.",
    interaction: "risk",
    flow: "calculate",
    question: "Risk budget ₹2,500, entry ₹1,608, stop ₹1,532. What is the position?",
    choices: ["32 shares", "76 shares", "156 shares", "329 shares"],
    correct: 0,
    correctFeedback: "Correct: risk per share is ₹76, so ₹2,500 ÷ ₹76 ≈ 32 shares.",
    incorrectFeedback: "Risk per share is 1,608 − 1,532 = ₹76. Then ₹2,500 ÷ ₹76 ≈ 32.",
    takeaway: "Size = adjusted risk budget ÷ risk per share. This is where the market read reaches the position.",
  },
  "APP-FIND-012": {
    plain: "Step eleven decides in advance how the trade ends if it works.",
    detail: "A target at the next level, a trailing rule, a time limit, or a combination — decided now, while nothing is at stake. Without it the exit is improvised at the moment you are least capable of deciding well, which is where a large share of planned profit is given back.",
    example: "Exit rule: half at the prior high of 1,712, trail the remainder below each new weekly swing low, close everything if the position has not moved after four weeks.",
    interaction: "workflow",
    flow: "judge",
    question: "Why write the exit plan before entering rather than when the trade is working?",
    choices: ["It saves time later", "Because a decision made with an open profit on screen is a different decision", "Brokers require it", "It improves the entry"],
    correct: 1,
    correctFeedback: "Correct. Pre-committed exits are the only ones made in a calm state.",
    incorrectFeedback: "The reason is behavioural. An open profit changes how you evaluate the same information.",
    takeaway: "Decide the exit before entering. An open profit changes the decision you would make.",
  },
  "APP-FIND-013": {
    plain: "Running the whole workflow means every step produces its output before the next one begins.",
    detail: "Market read, sector, screen, shortlist, chart, setup, entry, invalidation, stop, size, exit plan — eleven outputs, in order, before any money moves. Most candidates die somewhere in the middle, and a session that ends with no trade means the process worked rather than failed.",
    example: "Universe of 18 → leading sectors leave 9 → screen leaves 6 → shortlist rejections leave 2 → chart structure leaves 1 → sized at 32 shares with a written exit plan.",
    interaction: "workflow",
    flow: "plan",
    question: "You run the full workflow and reach the end with no candidate surviving. What happened?",
    choices: ["The workflow failed", "The process worked — nothing met the standard today", "The filters were too tight", "You should lower the standard until something qualifies"],
    correct: 1,
    correctFeedback: "Correct. A process that always produces a trade is a process you are overriding.",
    incorrectFeedback: "Reaching the end with nothing is a legitimate output. Relaxing the standard to produce a trade is the failure.",
    takeaway: "Eleven outputs, in order, before money moves. No trade is a valid result of a working process.",
  },
};
