"use client";

import { useState } from "react";

const money = (value: number) => `₹${Math.round(value).toLocaleString("en-IN")}`;
const marketPoints = [42,48,45,56,52,64,59,72,67,78];

function Slider({ label, value, min, max, step=1, onChange, display }: { label:string; value:number; min:number; max:number; step?:number; onChange:(value:number)=>void; display?:string }) {
  return <label className="fv-slider"><span>{label}</span><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={event=>onChange(Number(event.target.value))}/><b>{display ?? value}</b></label>;
}
function Stat({ label, value, tone="" }: { label:string; value:string; tone?:string }) { return <div className={`fv-stat ${tone}`}><span>{label}</span><b>{value}</b></div>; }

function OrderVisual({ lesson }: { lesson:number }) {
  const [qty,setQty]=useState(300); const [market,setMarket]=useState(100.10); const [limit,setLimit]=useState(99.95); const [trigger,setTrigger]=useState(99.70);
  const asks=[[100.10,100],[100.20,200],[100.35,300]]; let left=qty,cost=0,filled=0;
  const fills=asks.map(([price,available])=>{const take=Math.min(left,available);left-=take;filled+=take;cost+=take*price;return {price,available,take}});
  const average=cost/Math.max(1,filled); const volatile=lesson===9; const current=volatile?100.65:market;
  const titles=["","Market order: speed over price","Limit order: price over certainty","Stop-loss: trigger, then execution","Stop-limit: trigger plus a price boundary","Entry order: define how you get in","Exit order: reverse the position deliberately","Stop and target: define both outcomes","Partial fill: manage what actually filled","Volatility: the book can move before you arrive","Execution quality changes the result"];
  const body=lesson===1?`${filled} filled across ${fills.filter(x=>x.take).length} ask levels at ${money(average)} average.`:
    lesson===2?(current<=limit?`Limit can fill at ${money(current)} or better.`:`Best ask ${money(current)} is above your ${money(limit)} limit. The order waits.`):
    lesson===3?(current<=trigger?`Trigger crossed. A market sell is now attempted; the trigger is not the fill price.`:`Price has not reached the ${money(trigger)} trigger.`):
    lesson===4?(current<=trigger?`Triggered, but no sale below the ${money(limit)} limit. Protection may remain unfilled.`:`Dormant until ${money(trigger)} is reached.`):
    lesson===5?`Entry choice: market accepts available prices; limit accepts the risk of no position.`:
    lesson===6?`A long exits with a sell; a short exits with a buy. Closing is a new order, not an undo button.`:
    lesson===7?`Entry ${money(100)}, stop ${money(trigger)}, target ${money(101.20)}: risk ${money(100-trigger)} to seek ${money(1.2)} per share.`:
    lesson===8?`${Math.min(qty,180)} shares filled; ${Math.max(0,qty-180)} remain open. Risk now applies to the filled quantity.`:
    lesson===9?`The visible ask moved from ₹100.10 to ${money(current)}. Urgency costs ${money((current-100.10)*qty)} on ${qty} shares.`:
    `Gross edge ${money(300)} − spread/slippage ${money((average-100.10)*qty)} − charges ${money(85)} = net ${money(215-(average-100.10)*qty)}.`;
  return <div className="lesson-sim fv-sim"><div className="fv-head"><div><small>ORDER WORKBENCH</small><h3>{titles[lesson]}</h3></div><Stat label="CURRENT / BEST ASK" value={money(current)} tone={volatile?"warn":""}/></div>
    {(lesson===1||lesson===8||lesson===9||lesson===10)&&<Slider label="Order quantity" value={qty} min={50} max={600} step={50} onChange={setQty}/>} 
    {(lesson===2||lesson===4)&&<Slider label="Limit price" value={limit} min={99.5} max={100.5} step={.05} onChange={setLimit} display={money(limit)}/>} 
    {(lesson===3||lesson===4||lesson===7)&&<Slider label="Trigger / stop" value={trigger} min={98.5} max={100.5} step={.05} onChange={setTrigger} display={money(trigger)}/>} 
    {(lesson===2||lesson===3||lesson===4)&&<Slider label="Market price" value={market} min={98.5} max={101} step={.05} onChange={setMarket} display={money(market)}/>} 
    <div className="fv-order-grid"><div className="fv-ticket"><span>INSTRUCTION</span><b>{lesson===2?"LIMIT BUY":lesson===3?"STOP-MARKET SELL":lesson===4?"STOP-LIMIT SELL":lesson===6?"CLOSING ORDER":lesson===7?"BRACKET PLAN":"MARKET BUY"}</b><small>{lesson===4?`Trigger ${money(trigger)} · limit ${money(limit)}`:lesson===2?`Maximum ${money(limit)}`:`Quantity ${qty}`}</small></div><div className="fv-result" aria-live="polite"><span>WHAT THE ORDER CAN PROMISE</span><p>{body}</p></div></div>
    {(lesson===1||lesson===8||lesson===10)&&<div className="fv-depth">{fills.map(row=><div key={row.price} className={row.take?"used":""}><b>{money(row.price)}</b><span>{row.available} offered</span><i>{row.take?`${row.take} used`:"waiting"}</i></div>)}</div>}
  </div>;
}

function ChartVisual({ lesson }: { lesson:number }) {
  const [open,setOpen]=useState(100),[high,setHigh]=useState(112),[low,setLow]=useState(94),[close,setClose]=useState(106); const [view,setView]=useState(0);
  const safeHigh=Math.max(high,open,close), safeLow=Math.min(low,open,close); const timeframes=["5-minute","Daily","Weekly"];
  if(lesson===2||lesson===12) return <div className="lesson-sim fv-sim"><div className="fv-head"><div><small>SAME MARKET · DIFFERENT BUCKET</small><h3>Match the chart to the decision horizon</h3></div></div><div className="fv-tabs">{timeframes.map((name,i)=><button key={name} className={view===i?"active":""} onClick={()=>setView(i)}>{name}</button>)}</div><div className="fv-timeframe"><div className="fv-bars">{marketPoints.slice(0,view===0?10:view===1?6:3).map((point,i)=><i key={i} style={{height:`${point}%`}}/>)}</div><div><Stat label="DETAIL" value={["High","Balanced","Low"][view]}/><Stat label="BEST FOR" value={["Intraday execution","Days to weeks","Months and context"][view]}/><p>Aggregation changes what is visible, not what happened. Use finer bars for execution and broader bars for context.</p></div></div></div>;
  if(lesson===1||lesson===11) return <div className="lesson-sim fv-sim"><div className="fv-head"><div><small>PRICE RECORD</small><h3>{lesson===1?"A chart stores price against time":"Line versus candlestick"}</h3></div></div><div className="fv-tabs"><button className={view===0?"active":""} onClick={()=>setView(0)}>Closing-price line</button><button className={view===1?"active":""} onClick={()=>setView(1)}>OHLC candles</button></div><div className={`fv-series ${view?"candles":"line"}`}>{marketPoints.map((point,i)=><i key={i} style={{height:`${point}%`}}><span/></i>)}</div><p className="fv-note">{view?"Each bar retains open, high, low and close—the intraperiod path is still hidden.":"The line is cleaner because it keeps one value per period, usually the close; highs and lows disappear."}</p></div>;
  return <div className="lesson-sim fv-sim"><div className="fv-head"><div><small>BUILD THE PERIOD</small><h3>Change the four prices and read the candle</h3></div><Stat label="PERIOD" value={close>=open?"BULLISH":"BEARISH"}/></div><div className="fv-candle-lab"><div className="fv-candle"><i style={{height:`${Math.max(20,(safeHigh-safeLow)*8)}px`}}/><b className={close>=open?"up":"down"} style={{height:`${Math.max(12,Math.abs(close-open)*8)}px`}}/></div><div><Slider label="Open" value={open} min={90} max={110} onChange={setOpen}/><Slider label="High" value={safeHigh} min={100} max={118} onChange={setHigh}/><Slider label="Low" value={safeLow} min={84} max={104} onChange={setLow}/><Slider label="Close" value={close} min={90} max={114} onChange={setClose}/></div></div><p className="fv-note">Body: open to close. Wicks: extremes beyond the body. The candle records four prices—not the order of events or the next move.</p></div>;
}

function HorizonVisual({ lesson }: { lesson:number }) {
  const [pick,setPick]=useState(1); const [risk,setRisk]=useState(2000); const [stop,setStop]=useState(20);
  const rows=[
    {name:"Intraday",hold:"Minutes–hours",chart:"1–15 minute",events:"No overnight exposure if closed",attention:"During the session"},
    {name:"Swing",hold:"Days–weeks",chart:"Daily",events:"Gaps and announcements",attention:"Daily review"},
    {name:"Positional",hold:"Weeks–months",chart:"Daily + weekly",events:"Multiple scheduled events",attention:"Several reviews weekly"},
    {name:"Investing",hold:"Months–years",chart:"Business evidence + broader chart",events:"Business-cycle exposure",attention:"Periodic thesis review"},
  ]; const chosen=rows[pick]; const size=Math.floor(risk/stop);
  return <div className="lesson-sim fv-sim"><div className="fv-head"><div><small>HORIZON PLANNER</small><h3>{lesson===7?"Same risk budget, different stop distance":lesson===9?"Choose a method your schedule can support":"Change the horizon; watch the trade change"}</h3></div></div><div className="fv-tabs">{rows.map((row,i)=><button key={row.name} className={pick===i?"active":""} onClick={()=>setPick(i)}>{row.name}</button>)}</div>{lesson===7&&<><Slider label="Risk budget" value={risk} min={500} max={5000} step={500} onChange={setRisk} display={money(risk)}/><Slider label="Stop distance" value={stop} min={2} max={80} step={2} onChange={setStop} display={money(stop)}/></>}<div className="fv-horizon-grid"><Stat label="HOLD" value={chosen.hold}/><Stat label="PRIMARY VIEW" value={chosen.chart}/><Stat label="EVENT EXPOSURE" value={chosen.events}/><Stat label="ATTENTION" value={chosen.attention}/>{lesson===7&&<Stat label="POSITION SIZE" value={`${size} shares`}/>}</div><p className="fv-note">There is no universal rupee stop or automatically “largest” horizon. Stop distance follows the instrument and invalidation; position size follows the risk budget.</p></div>;
}

const structures={up:[38,48,44,57,51,67,61,75,69,82],down:[82,72,76,64,68,55,60,47,52,39],range:[55,68,58,69,57,67,56,70,59,66]};
function StructureVisual({ lesson }: { lesson:number }) {
  const defaultMode=lesson===3?"down":lesson===4?"range":"up"; const [mode,setMode]=useState<keyof typeof structures>(defaultMode); const [selected,setSelected]=useState(0); const values=structures[mode];
  const names=["","Trend requires repeated progress","Uptrend: higher highs and higher lows","Downtrend: lower highs and lower lows","Range: repeated rejection at both edges","Higher high extends the advance","Higher low shows buyers stepping in sooner","Lower high shows sellers stepping in sooner","Lower low extends the decline","Support is a watched area, not a floor","Resistance is a watched area, not a ceiling","Breakout requires acceptance beyond the area","False breakout returns inside the prior area","Reversal is a sequence, not one candle","Context changes what the same candle means"];
  const highlight=(i:number)=> lesson===5?i===7||i===9:lesson===6?i===6||i===8:lesson===7?i===2||i===4:lesson===8?i===5||i===7:lesson===9?values[i]<53:lesson===10?values[i]>68:lesson===11?i===9:lesson===12?i>=8:false;
  return <div className="lesson-sim fv-sim"><div className="fv-head"><div><small>STRUCTURE MAP</small><h3>{names[lesson]}</h3></div><Stat label="WINDOW" value={mode.toUpperCase()}/></div><div className="fv-tabs">{(["up","range","down"] as const).map(name=><button key={name} className={mode===name?"active":""} onClick={()=>{setMode(name);setSelected(0)}}>{name==="up"?"Uptrend":name==="down"?"Downtrend":"Range"}</button>)}</div><div className="fv-structure">{values.map((value,i)=><button aria-label={`Inspect swing ${i+1}`} key={i} className={`${highlight(i)?"key":""} ${selected===i?"selected":""}`} style={{height:`${value}%`}} onClick={()=>setSelected(i)}><i/><span>{highlight(i)?lesson===9?"support":lesson===10?"resistance":lesson===11?"accepted":lesson===12?"failed":i%2?"swing high":"swing low":""}</span></button>)}</div><div className="fv-result"><span>SELECTED SWING {selected+1}</span><p>{lesson===11?"A print above resistance is not enough. Look for closing acceptance and follow-through.":lesson===12?"Price traded beyond the boundary, then returned inside: the attempted breakout failed.":lesson===13?"Reversal evidence builds: trend weakens, a key swing breaks, then the opposite sequence develops.":lesson===14?"Read this swing in the surrounding sequence; the same candle can mean continuation, pause or failure.":"Compare successive swing highs and lows. Structure is the relationship between them, not the colour of one bar."}</p></div></div>;
}

function VolumeVisual({ lesson }: { lesson:number }) {
  const [activity,setActivity]=useState(55); const [range,setRange]=useState(5); const [stop,setStop]=useState(6); const units=Math.round(activity*4200); const atr=range;
  const price=[46,52,50,57,55,63,60,70,66,74], volume=[30,35,28,42,38,55,48,activity,52,64];
  return <div className="lesson-sim fv-sim"><div className="fv-head"><div><small>PRICE · VOLUME · RANGE</small><h3>{lesson<=4?"Activity and direction are different questions":lesson===8?"ATR averages recent true ranges":lesson===9?"Fit the stop to normal movement":"Volatility measures movement, not direction"}</h3></div><Stat label={lesson<=4?"UNITS TRADED":"ILLUSTRATIVE ATR"} value={lesson<=4?units.toLocaleString("en-IN"):money(atr)}/></div>{lesson<=4&&<Slider label="Selected bar volume" value={activity} min={10} max={100} onChange={setActivity}/>} {lesson>=5&&<Slider label="Average daily range" value={range} min={1} max={15} onChange={setRange} display={money(range)}/>} {lesson===9&&<Slider label="Stop distance" value={stop} min={1} max={20} onChange={setStop} display={money(stop)}/>}<div className="fv-market-stack"><div className="fv-price-bars">{price.map((v,i)=><i key={i} style={{height:`${v}%`}}/>)}</div><div className="fv-volume-bars">{volume.map((v,i)=><i key={i} className={i===7?"active":""} style={{height:`${v}%`}}/>)}</div></div><div className="fv-metrics"><Stat label="PRICE CHANGE" value="+2.1%"/><Stat label="ACTIVITY" value={`${(units/100000).toFixed(1)} lakh units`}/>{lesson>=5&&<Stat label="STOP VS ATR" value={`${(stop/atr).toFixed(1)}× ATR`} tone={stop<atr?"warn":""}/>}</div><p className="fv-note">{lesson<=4?"Volume counts shares or contracts traded—not the number of people and not whether buyers outnumbered sellers.":lesson===9?(stop<atr?"The stop sits inside ordinary movement; it may answer ‘did price wiggle?’ rather than ‘was the trade invalidated?’":"The stop is outside one average range. Structure must still decide the actual invalidation level."):"A wide high-to-low journey can be volatile even when the close finishes near the open."}</p></div>;
}

function IndicatorVisual({ lesson }: { lesson:number }) {
  const [window,setWindow]=useState(5); const [gain,setGain]=useState(3); const [loss,setLoss]=useState(1); const prices=[94,97,95,101,105,103,108,111,107,114,116,113]; const avg=prices.slice(-window).reduce((a,b)=>a+b,0)/Math.min(window,prices.length); const rs=gain/Math.max(1,loss); const rsi=Math.round(100-100/(1+rs));
  const rsiLesson=lesson>=6&&lesson<=9; const atrLesson=lesson===10; const lagLesson=lesson===11;
  return <div className="lesson-sim fv-sim"><div className="fv-head"><div><small>DERIVED, NOT PREDICTIVE</small><h3>{rsiLesson?"Build RSI from relative gains and losses":atrLesson?"ATR measures range, not direction":lagLesson?"Smoothing creates lag by construction":lesson===12?"Agreement is not independent confirmation":lesson===13?"Structure first; indicator second":"Watch a moving average re-describe price"}</h3></div><Stat label={rsiLesson?"RSI":atrLesson?"ATR":"MOVING AVERAGE"} value={rsiLesson?`${rsi}`:atrLesson?"₹5.4":money(avg)}/></div>{rsiLesson?<><Slider label="Average recent gain" value={gain} min={1} max={10} onChange={setGain}/><Slider label="Average recent loss" value={loss} min={1} max={10} onChange={setLoss}/><div className="fv-rsi-track"><i style={{width:`${rsi}%`}}/><b style={{left:`${rsi}%`}}>{rsi}</b><span>30</span><span>70</span></div></>:<Slider label={lagLesson?"Smoothing window":"Average window"} value={window} min={2} max={12} onChange={setWindow} display={`${window} periods`}/>}<div className="fv-indicator-chart">{prices.map((value,i)=><i key={i} style={{height:`${value-75}%`}}/>)}<span style={{bottom:`${avg-75}%`}}>MA {avg.toFixed(1)}</span></div><p className="fv-note">{rsiLesson?"Below 30 describes unusually strong recent losses relative to gains. It is not a floor and does not automatically mean Buy.":lesson===12?"Three momentum indicators built from the same closes are correlated evidence. Add structure, volume or context—not another calculation of the same input.":lesson===13?"The indicator compresses the same price history. Use market structure to locate invalidation and the indicator to summarise momentum or range.":"A shorter window reacts faster and whipsaws more. A longer window is smoother and slower. There is no setting without a trade-off."}</p></div>;
}

function RiskVisual({ lesson }: { lesson:number }) {
  const [riskPct,setRiskPct]=useState(1); const [stop,setStop]=useState(6); const [winRate,setWinRate]=useState(50); const [avgWin,setAvgWin]=useState(1200); const [avgLoss,setAvgLoss]=useState(800); const capital=100000,risk=capital*riskPct/100,size=Math.floor(risk/stop); const expectancy=winRate/100*avgWin-(1-winRate/100)*avgLoss; const after5=capital*Math.pow(1-riskPct/100,5); const drawdown=(1-after5/capital)*100; const recovery=drawdown>=100?Infinity:drawdown/(100-drawdown)*100;
  const calc=lesson===3?`${money(risk)} ÷ ${money(stop)} = ${size} shares`:lesson===5?`Risk ${money(stop)} · target ${money(stop*2)} · 1:2`:lesson===6?`${winRate}% wins does not reveal payoff size`:lesson===7?`${money(expectancy)} expected per trade`:lesson===8?`${money(after5)} after five losses`:lesson===9?`${drawdown.toFixed(1)}% down needs ${recovery.toFixed(1)}% recovery`:lesson===10?`${money(capital*Math.pow(1.02,12))} after 12 × 2% gains`:lesson===11?`₹5 lakh exposure: a 4% move = ₹20,000`:lesson===12?`${riskPct}% risk leaves ${money(after5)} after five losses`:money(risk);
  return <div className="lesson-sim fv-sim"><div className="fv-head"><div><small>RISK DECISION LAB</small><h3>{lesson===3?"Size follows risk budget and stop distance":lesson===7?"Expectancy combines frequency and payoff":lesson===9?"Drawdown and recovery are asymmetric":lesson===11?"Leverage scales exposure, not skill":lesson>=15?"Pre-commit the process before emotion arrives":"Change the size; watch survival change"}</h3></div><Stat label="CURRENT RESULT" value={calc} tone={riskPct>5?"warn":""}/></div>{![6,7,11,15,16,17,18].includes(lesson)&&<Slider label="Risk per trade" value={riskPct} min={.5} max={20} step={.5} onChange={setRiskPct} display={`${riskPct}%`}/>} {[3,4,5].includes(lesson)&&<Slider label="Entry-to-stop distance" value={stop} min={1} max={25} onChange={setStop} display={money(stop)}/>} {[6,7].includes(lesson)&&<><Slider label="Win rate" value={winRate} min={20} max={90} onChange={setWinRate} display={`${winRate}%`}/><Slider label="Average win" value={avgWin} min={200} max={3000} step={100} onChange={setAvgWin} display={money(avgWin)}/><Slider label="Average loss" value={avgLoss} min={200} max={3000} step={100} onChange={setAvgLoss} display={money(avgLoss)}/></>}<div className="fv-risk-grid"><Stat label="PLANNED LOSS" value={money(risk)}/><Stat label="POSITION SIZE" value={`${size} shares`}/><Stat label="AFTER 5 LOSSES" value={money(after5)} tone={riskPct>5?"warn":""}/><Stat label="EXPECTANCY" value={money(expectancy)} tone={expectancy<0?"warn":"good"}/></div>{lesson>=15&&<div className="fv-process">{["Setup exists before entry","Invalidation and stop written","Size calculated from risk","Daily limit defined","Review a batch, not one result"].map((item,i)=><button key={item}><i>{i+1}</i><span>{item}</span></button>)}</div>}<p className="fv-note">{lesson===8?"A losing streak is possible and should be planned for; probability does not guarantee a particular sequence in the next sample.":lesson===17?"A winning streak does not make a losing run “due.” The next trade’s odds are unchanged; increasing size for emotional reasons increases exposure without increasing edge.":lesson>=15?"Rules reduce the number of decisions left for the stressed version of you. They do not remove losses.":"The chart chooses where the idea is invalidated. You choose the rupee risk. Position size connects the two."}</p></div>;
}

export function FoundationVisual({ lessonId, moduleCode }: { lessonId:string; moduleCode:string }) {
  const lesson=Number(lessonId.slice(-3));
  if(moduleCode==="ORD") return <OrderVisual lesson={lesson}/>;
  if(moduleCode==="CHART") return <ChartVisual lesson={lesson}/>;
  if(moduleCode==="HZN") return <HorizonVisual lesson={lesson}/>;
  if(moduleCode==="STRUCT") return <StructureVisual lesson={lesson}/>;
  if(moduleCode==="VOL") return <VolumeVisual lesson={lesson}/>;
  if(moduleCode==="IND") return <IndicatorVisual lesson={lesson}/>;
  if(moduleCode==="RISK") return <RiskVisual lesson={lesson}/>;
  return null;
}
