"use client";

import { useState, type ReactNode } from "react";

const Chip = ({ children }: { children: ReactNode }) => <span className="mf-badge">{children}</span>;

const assetTypes = [
  { label: "Shares", exchange: "An ownership interest in a company.", example: "Asha buys 10 listed shares of Infosys through NSE.", differs: "A share represents ownership; the other products below represent lending, exchange, physical goods or a contract." },
  { label: "Bonds", exchange: "A debt instrument through which an issuer borrows money.", example: "An investor buys an RBI or company bond and receives interest under its terms.", differs: "A bond is a lending claim with repayment terms, not an ownership interest in the issuer." },
  { label: "Currencies", exchange: "One currency exchanged for another.", example: "An importer converts rupees into US dollars to pay a supplier.", differs: "A currency trade exchanges money units; it does not give you ownership of a company." },
  { label: "Commodities", exchange: "Assets such as gold, crude oil or agricultural products.", example: "A jeweller hedges gold prices while a farmer manages crop-price risk.", differs: "A commodity is a physical or raw-material exposure, not a claim on company ownership." },
  { label: "Derivatives", exchange: "A contract whose value depends on an underlying asset, rate or measure.", example: "A trader uses a NIFTY futures contract to take index-price exposure.", differs: "A derivative is a contract linked to something else; it is not a company share itself." },
] as const;

const choices = {
  "FND-MKT-002": [["Capital formation", "Savings fund businesses and projects."], ["Liquidity", "Owners can transfer an asset without waiting for the issuer."], ["Price discovery", "Competing orders reveal the price available now."], ["Risk transfer", "Risk can move to someone more willing or able to carry it."]],
  "FND-MKT-013": [["Risk takers", "Retail traders, funds, insurers, banks, firms and hedgers take investment or trading risk."], ["Intermediaries", "Brokers and depository participants help clients transact or hold assets."], ["Infrastructure", "Exchanges, clearing corporations and depositories run core market systems."], ["Regulator", "SEBI writes and enforces the regulatory framework."]],
} as const;

export function MarketFoundationsVisual({ lessonId }: { lessonId: string }) {
  const [tab, setTab] = useState(0);
  const [assetTab, setAssetTab] = useState(0);
  const [a, setA] = useState(50);
  const [b, setB] = useState(55);
  const [c, setC] = useState(40);
  const [bookQuantity, setBookQuantity] = useState(50);

  if (lessonId === "FND-MKT-001") {
    const nodes = [["Saver / investor", "Provides capital or accepts financial risk"], ["Market + intermediaries", "Connects orders under rules"], ["Capital user", "Company, government or another participant"]];
    const asset = assetTypes[assetTab];
    return <div className="lesson-sim mf-sim"><div className="mf-flow">{nodes.map(node => <div key={node[0]}><b>{node[0]}</b><span>{node[1]}</span></div>)}</div><div className="mf-assets" role="tablist" aria-label="Financial asset types">{assetTypes.map((item, i) => <button key={item.label} id={`mf-asset-tab-${i}`} role="tab" aria-selected={assetTab === i} aria-controls={`mf-asset-panel-${i}`} tabIndex={assetTab === i ? 0 : -1} className={assetTab === i ? "active" : ""} onClick={() => setAssetTab(i)} onKeyDown={event => { if (event.key === "ArrowRight" || event.key === "ArrowDown") { event.preventDefault(); setAssetTab((i + 1) % assetTypes.length); } if (event.key === "ArrowLeft" || event.key === "ArrowUp") { event.preventDefault(); setAssetTab((i + assetTypes.length - 1) % assetTypes.length); } }}>{item.label}</button>)}</div><div className="mf-asset-panel" id={`mf-asset-panel-${assetTab}`} role="tabpanel" aria-labelledby={`mf-asset-tab-${assetTab}`}><div><b>What is exchanged</b><span>{asset.exchange}</span></div><div><b>Indian-market example</b><span>{asset.example}</span></div><div><b>Compared with a share</b><span>{asset.differs}</span></div></div><p>A stock exchange is one organised venue inside this wider ecosystem. It is not the whole financial market, and these products do not all trade in NSE or BSE’s equity segment.</p></div>;
  }

  if (lessonId === "FND-MKT-002" || lessonId === "FND-MKT-013") { const items = choices[lessonId]; return <div className="lesson-sim mf-sim"><div className="mf-function-grid">{items.map(item => <div key={item[0]}><b>{item[0]}</b><span>{item[1]}</span></div>)}</div><p>{lessonId === "FND-MKT-002" ? "Organised markets scale these functions; bank loans, private capital and bonds remain other funding routes." : "A participant can fit more than one role, but the role tells you what responsibility it carries in that transaction."}</p></div>; }
  if (lessonId === "FND-MKT-003") { const held = a; return <div className="lesson-sim mf-sim"><label className="mf-slider">Shares held out of 100 <input aria-label="Shares held out of one hundred" type="range" min="5" max="100" step="5" value={a} onChange={e => setA(Number(e.target.value))}/><b>{held}% interest</b></label><div className="mf-share-grid">{Array.from({length:20},(_,i)=><i key={i} className={i < held/5 ? "owned" : ""}/>)}</div><div className="mf-three"><Chip>Possible dividend</Chip><Chip>Price may rise</Chip><Chip>Loss is possible</Chip></div><p>You own an interest in the company, not {held}% of each desk, factory or bank account. Rights can also differ by share class.</p></div>; }
  if (lessonId === "FND-MKT-004") { const debt = tab === 0; return <div className="lesson-sim mf-sim"><div className="mf-tabs" role="tablist" aria-label="Funding type"><button role="tab" aria-selected={debt} className={debt ? "active" : ""} onClick={()=>setTab(0)}>Debt</button><button role="tab" aria-selected={!debt} className={!debt ? "active" : ""} onClick={()=>setTab(1)}>Equity</button></div><div className="mf-ledger"><b>{debt ? "Borrowed capital" : "New ownership capital"}</b><span>{debt ? "Contractual interest and repayment obligations" : "Normally no fixed repayment obligation"}</span><span>{debt ? "No ownership dilution" : "Existing owners hold a smaller percentage"}</span><span>{debt ? "Can strain cash flow" : "Can affect voting control"}</span></div><p>Companies choose a mix depending on expansion plans, acquisitions, balance-sheet strength, employee compensation and existing investor needs.</p></div>; }
  if (lessonId === "FND-MKT-005") { const primary = tab === 0; return <div className="lesson-sim mf-sim"><div className="mf-tabs" role="tablist" aria-label="Market route"><button role="tab" aria-selected={primary} className={primary ? "active" : ""} onClick={()=>setTab(0)}>New issue / IPO</button><button role="tab" aria-selected={!primary} className={!primary ? "active" : ""} onClick={()=>setTab(1)}>Later exchange trade</button></div><div className="mf-route"><b>{primary ? "Investor" : "Buyer"}</b><i>₹</i><b>{primary ? "Company issuing new shares" : "Existing shareholder"}</b></div><p>{primary ? "The issuer receives the issue proceeds and new shares enter investors’ hands." : "The company does not receive the proceeds from this particular trade. Liquidity still helps its shares remain easier to own, value and use in future fundraising."}</p></div>; }
  if (lessonId === "FND-MKT-006") { const chain = ["Investor", "Broker", "NSE / BSE", "Clearing corporation", "Depository"]; return <div className="lesson-sim mf-sim"><div className="mf-chain">{chain.map((item,i)=><button key={item} className={tab===i?"active":""} onClick={()=>setTab(i)}><i>{i+1}</i><b>{item}</b></button>)}</div><div className="mf-overseer"><span>SEBI · regulator and overseer</span></div><p>{["Starts an order through a registered broker.","Checks and routes the order.","Provides rules, matching, data and surveillance.","Manages clearing obligations and settlement risk.","Records securities held and transferred electronically."][tab]}</p></div>; }
  if (lessonId === "FND-MKT-007") { const weights=[50,30,20], vals=[a,b,c], bases=[50,55,40], setters=[setA,setB,setC]; const move=vals.reduce((sum,v,i)=>sum+(v-bases[i])*weights[i]/100,0); return <div className="lesson-sim mf-sim mf-index"><div className="sim-caption"><b>SIMPLIFIED MARKET-CAP-WEIGHTED MODEL</b><span>{move>=0?"+":""}{move.toFixed(1)}%</span></div>{vals.map((value,i)=><label key={i}><span>Company {String.fromCharCode(65+i)}<small>{weights[i]}% weight</small></span><input aria-label={`Company ${String.fromCharCode(65+i)} price move`} type="range" min={bases[i]-20} max={bases[i]+20} value={value} onChange={e=>setters[i](Number(e.target.value))}/><b>{value-bases[i]>=0?"+":""}{value-bases[i]}%</b></label>)}<p>Real indices follow published rules. Some use free-float market capitalisation, some equal weights, and others different methods.</p></div>; }
  if (lessonId === "FND-MKT-008") { const publicShares=a; return <div className="lesson-sim mf-sim"><label className="mf-slider">Shares available to public investors <input aria-label="Percentage of shares available to public investors" type="range" min="10" max="90" value={a} onChange={e=>setA(Number(e.target.value))}/><b>{publicShares}% free float</b></label><div className="mf-float"><i style={{width:`${100-publicShares}%`}}>Strategic / promoter</i><i className="free" style={{width:`${publicShares}%`}}>Free float</i></div><p>NIFTY 50 contains 50 eligible NSE companies, is periodically reviewed, and weights constituents by free-float market capitalisation—not by total company size or one vote each.</p></div>; }
  if (lessonId === "FND-MKT-009") { const nifty=tab===0; return <div className="lesson-sim mf-sim"><div className="mf-tabs" role="tablist" aria-label="Benchmark index"><button role="tab" aria-selected={nifty} className={nifty?"active":""} onClick={()=>setTab(0)}>NIFTY 50</button><button role="tab" aria-selected={!nifty} className={!nifty?"active":""} onClick={()=>setTab(1)}>SENSEX</button></div><div className="mf-ledger"><b>{nifty?"NSE equity benchmark":"BSE equity benchmark"}</b><span>{nifty?"50 constituents":"30 constituents"}</span><span>Free-float market-cap weighted</span><span>Own published eligibility and review methodology</span></div><p>They often move similarly because large-company and sector exposure overlaps—not because either index is derived from the other.</p></div>; }
  if (lessonId === "FND-MKT-010") { const broad=tab===1; return <div className="lesson-sim mf-sim"><div className="mf-tabs" role="tablist" aria-label="Risk type"><button role="tab" aria-selected={!broad} className={!broad?"active":""} onClick={()=>setTab(0)}>One-company event</button><button role="tab" aria-selected={broad} className={broad?"active":""} onClick={()=>setTab(1)}>Market-wide event</button></div><div className="mf-risk-bars">{[70,62,76,68,72].map((v,i)=><i key={i} style={{height:`${broad?v-35:i===2?20:v}%`}}><span>{String.fromCharCode(65+i)}</span></i>)}</div><p>{broad?"A systemic shock can pull many constituents down together, so the index can fall sharply.":"One constituent’s problem is diluted inside a diversified basket according to its weight."}</p><b className="mf-rule">Diversification reduces company-specific risk; it does not remove market risk.</b></div>; }
  if (lessonId === "FND-MKT-011" || lessonId === "FND-MKT-012") { const discovery=lessonId === "FND-MKT-012"; const asks=[[100.10,100],[100.20,300],[100.30,200]]; const maxQuantity=discovery?100:120; let left=bookQuantity, cost=0, filled=0, latest:number|null=null; const consumed:number[]=[]; for(const [price,qty] of asks){const take=Math.min(left,qty);if(take){cost+=take*price;filled+=take;left-=take;consumed.push(price);latest=price;}if(!left)break;} const average=filled?cost/filled:null; const status=discovery?`Market buyer accepts the best ask ₹100.10; latest execution is ₹${latest?.toFixed(2)}.`:`${filled} shares are bought and sold in the execution; participant counts can still differ.`; return <div className="lesson-sim mf-sim mf-book"><div><span>BIDS · WAITING BUY QTY</span>{[[99.90,120],[99.80,250],[99.70,400]].map(x=><b key={x[0]}>₹{x[0].toFixed(2)} <i>{x[1]}</i></b>)}</div><div><span>OFFERS · WAITING SELL QTY</span>{asks.map(x=><b key={x[0]}>₹{x[0].toFixed(2)} <i>{x[1]}</i></b>)}</div><label>Incoming market-buy quantity <input aria-label="Incoming market buy quantity" type="range" min="10" max={maxQuantity} value={bookQuantity} onChange={e=>setBookQuantity(Number(e.target.value))}/><b>{bookQuantity}</b></label><div className="mf-book-result"><span>FILLED / AVERAGE / LATEST</span><b>{filled} shares · {average?`₹${average.toFixed(2)}`:"—"} avg · {latest?`₹${latest.toFixed(2)}`:"—"}</b></div><p>{status} {left?`${left} shares wait for more liquidity.`:`The order consumed ${consumed.length} visible offer level${consumed.length === 1 ? "" : "s"}.`} Every executed share still has one buyer and one seller.</p></div>; }
  if (lessonId === "FND-MKT-014") { const institutional=tab===1; return <div className="lesson-sim mf-sim"><div className="mf-tabs" role="tablist" aria-label="Participant type"><button role="tab" aria-selected={!institutional} className={!institutional?"active":""} onClick={()=>setTab(0)}>Retail tendency</button><button role="tab" aria-selected={institutional} className={institutional?"active":""} onClick={()=>setTab(1)}>Institutional tendency</button></div><div className="mf-ledger"><b>{institutional?"Organisation deploying substantial capital":"Individual deploying personal capital"}</b><span>{institutional?"Mandate, regulation and reporting constraints":"Flexible mandate and usually smaller orders"}</span><span>{institutional?"More research and execution resources":"Can enter or exit without much market impact"}</span><span>{institutional?"Capital may be pooled, beneficiary, corporate or proprietary":"Small size is a genuine execution advantage"}</span></div><p>These are tendencies, not rules. Neither label guarantees better information, discipline or results.</p></div>; }
  if (lessonId === "FND-MKT-015") { const trader=tab===1; return <div className="lesson-sim mf-sim"><div className="mf-tabs" role="tablist" aria-label="Decision process"><button role="tab" aria-selected={!trader} className={!trader?"active":""} onClick={()=>setTab(0)}>Investor thesis</button><button role="tab" aria-selected={trader} className={trader?"active":""} onClick={()=>setTab(1)}>Trader setup</button></div><div className="mf-ledger"><b>{trader?"Return sought from a defined price move":"Return sought from long-term business economics"}</b><span>{trader?"Planned entry, invalidation and exit horizon":"Business quality, cash flows and valuation"}</span><span>{trader?"Turnover and transaction costs matter frequently":"Usually lower turnover, but price and risk still matter"}</span><span>Charts and fundamental information can inform either approach</span></div><p>Investor and trader are ends of a spectrum. The intention and process matter more than a single holding-period cut-off.</p></div>; }
  return null;
}
